### ISSUE TITLE
Small Temple All multiple problems

### ISSUE THREAD

**Issue by Syst3mSh0ck** [Keriew/augustus#100]
I noticed when placing Small Temple All that it is a temple for Ceres and not the others. Advisor screen shows only Ceres being happy. Right clicking on the temple also shows Ceres and not All. Also once placing the building, the second ghost will show a building for Neptune, the other temples seem to build and work fine. I don't remember there being a Small Temple for All Gods in vanilla C3. This seems bugged. I haven't seen this reported anywhere. Configuration file attached. Thanks.

[augustus.zip](https://github.com/Keriew/augustus/files/4874992/augustus.zip)

**Comment by crudelios** [comment]
The "All" option doesn't build a temple for all gods, it allows building one temple of each type without having to constantly go to the building menu.

**Comment by Syst3mSh0ck** [comment]
Ah that makes sense! Doh. Thanks :)
