### ISSUE TITLE
Garden arch, green tree arch display error

### ISSUE THREAD

**Issue by maoxp09** [Keriew/augustus#1003]
Many pedestrians with larger volumes, such as immigrants and carriages, may make visual errors when passing through garden arches and green tree arches. I found that it is a problem with the architectural images. If allowed, I am willing to try modifying the texture.

**Comment by crudelios** [comment]
This is likely a limitation with the game engine.

We do try to get around these issues the best we can, but some are simply unavoidable.

**Comment by maoxp09** [comment]
> 这可能是游戏引擎的限制。
> 
> 我们确实尽力避开这些问题，但有些问题是不可避免的。
Thanks for your reply
