### ISSUE TITLE
could you please restore the zoom in and zoom out functionality for the Unstable build of the game using the scroll wheel, similar to the 3.2.0 version?

### ISSUE THREAD

**Issue by BenChen3842** [Keriew/augustus#1006]
Hello Game Improvement Team, could you please restore the zoom in and zoom out functionality for the Unstable build of the game using the scroll wheel, similar to the 3.2.0 version?

**Comment by crudelios** [comment]
Hi,

You need to set them again manually on the hotkey config window for now, as they're assignable hotkeys.

We're planning on making the old mouse wheel up/down the default hotkeys for zooming again, but we haven't done that yet so you need to do it manually.

**Comment by maoxp09** [comment]
> 你好，游戏改进团队，可以请你使用滚轮恢复游戏的不稳定版本的放大和缩小功能，类似于3.2.0版本吗？
Hey buddy, in the hotkey settings interface, you can change it to mouse wheel zoom
