### ISSUE TITLE
Game crashed upon save attempt.

### ISSUE THREAD

**Issue by Zeg4** [Keriew/augustus#1011]
I was just playing normally when the game suddenly crashed after trying to save it, resulting in a small loss of gameplay time.

The crash log reads as follows:

INFO:  Creating atlas texture with size 585x585
INFO:  Window 1 exposed
INFO:  Window 1 exposed
INFO:  Window 1 exposed
INFO:  Window 1 exposed
INFO:  Saving game  3 Data.svx
ERROR:  Oops, crashed :(
INFO:  Exception: Access violation (0xc0000005)
INFO:  Loading saved game  3 Data.svx (message repeats 1 time)
INFO:  Savegame version  155 (message repeats 1 time)
INFO:  Exception Address: 0x00ef2120
INFO:  Stacktrace:
INFO:  (0) src\scenario\scenario.c L:374(scenario_save_state+0) [0x00ef2120]
INFO:  (1) src\game\file_io.c L:829(game_file_io_write_saved_game+0) [0x00eca992]
INFO:  (2) src\window\file_dialog.c L:645(confirm_save_file+0) [0x00f5fcc8]
INFO:  (3) src\graphics\window.c L:139(window_draw+0) [0x00f0bedd]
INFO:  (4) src\game\game.c L:195(game_draw+0) [0x00ecb252]
INFO:  (5) src\platform\augustus.c L:181(run_and_draw+0) [0x00e51ac5]
INFO:  (6) src\platform\augustus.c L:410(SDL_main+0) [0x00e52050]

Not sure of what it says, but it mentions the game window itself, I think? I play on windowed mode, if that helps.

Latest unstable version.

**Comment by crudelios** [comment]
Hi,

Is the crash consistent or was it a one-off?

If it was consistent, can you provide the savefile please?

By latest unstable you mean 4.0.0.2, right?

**Comment by Zeg4** [comment]
It was a one-off. I tried to replicate it, but it only happened once.

Yes, 4.0.0.2 is my version.

**Comment by crudelios** [comment]
Thanks.

Technical time:

@UberWaffe Based on the provided stack trace, the crash seems to happen when saving custom scenario variables.

The crash may be because the buffer size is incorrectly calculated or because the game is fetching bogus memory to save (ie invalid dereference). Maybe you got a better idea what may be causing the issue?

**Comment by Zeg4** [comment]
Oh, I forgot to mention: I am playing the regular campaign, currently on Tingis (Praetor rank). Just in case that is relevant.

**Comment by crudelios** [comment]
This is likely fixed by the latest commit, so I'm closing this.

Let me know if it happens again, hopefully it won't.
