### ISSUE TITLE
Unable to build some housing right beside highway

### ISSUE THREAD

**Issue by calhix** [Keriew/augustus#1017]
![Screenshot from 2024-01-13 16-04-05](https://github.com/Keriew/augustus/assets/64714934/044104cb-5571-49e4-9561-c31d15f45ebe)

Hello, trying out the new highways and it seems I'm unable to create new housing in certain areas right by it but some are fine. As you can see the two houses are able to be built with no issue but I get errors when trying to build any of the rest in the image. Save file here: https://drive.google.com/file/d/1m4ws2-cltgj-S4A0uqOt7AOhoo0KgEKf/view?usp=sharing

**Comment by crudelios** [comment]
Hi,

Highways don't count as road access. The reason the houses next to the bridge develop is because the bridge is a road and not a highway.

So, you'll always need a road at most two tiles away from the house, otherwise it'll disappear.
