### ISSUE TITLE
Web browser version does not allow selecting a folder with c3 on ipad

### ISSUE THREAD

**Issue by sdwvit** [Keriew/augustus#1036]
Ios browser disallows selecting folder in web version of augustus. Please consider changing the file input to accept folders on ios. Maybe this helps https://stackoverflow.com/questions/12942436/how-to-get-folder-directory-from-html-input-type-file-or-any-other-way.

Love the project, thank you 😊

**Comment by crudelios** [comment]
I believe there is no way to do that. You can still provide a zip file which will work fine.

**Comment by sdwvit** [comment]
@crudelios providing a zip file on ipad pro m1 8gb ram crashes the tab.

**Comment by sdwvit** [comment]
I can create a separate issue for this but I believe unzipping in browser may be crashing with OOM

**Comment by crudelios** [comment]
I don't have ios to check but it seems to be an old issue with ios itself that apple seems reluctant to fix.

I'll try updating the zip library but if it doesn't work, I can't really fix it.
