### ISSUE TITLE
latest unstable 38 breaks while launching

### ISSUE THREAD

**Issue by destinationwalker** [Keriew/augustus#1038]
No save game attached because the game does not start. Latest stable starts. I used Version 4.0.0.6 so far and that worked.

greetings
dw

[augustus-log.txt](https://github.com/Keriew/augustus/files/14182486/augustus-log.txt)

**Comment by crudelios** [comment]
Hi,

This seems to be an issue with the latest version of SDL, that only happens on x86 builds.

As a workaround, you can use the older version of `SDL2.dll`, which seems to work fine. Get it from here and simply replace your `SDL2.dll` (located in `D:\Spiele\Ausfuehrbar\Caesar3\Augustus\SDL2.dll`) with this one:

https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-2.28.5-win32-x86.zip

I'll need to check if this is an issue with the game or the SDL library, so for now please use this workaround.

Thanks!

**Comment by crudelios** [comment]
Should be fixed now
