### ISSUE TITLE
Augustus 3.2.0 crashed

### ISSUE THREAD

**Issue by geralt1989** [Keriew/augustus#1039]
As soon as I start a save, the game crashes and I have to force close it.
I attach log and screen of the error.

![image](https://github.com/Keriew/augustus/assets/55511928/adceb798-dd10-4d25-a5c9-d8c0aa8e63cf)

thanks
[augustus-log.txt](https://github.com/Keriew/augustus/files/14195551/augustus-log.txt)

**Comment by crudelios** [comment]
Should be fixed now
