### ISSUE TITLE
Screen resolution problem

### ISSUE THREAD

**Issue by SnakeSortITA** [Keriew/augustus#1047]
Hi everyone.
I commend you for the enormous work you do to make Cesar 3 a great game.
I wanted to report a problem in the settings that I encountered.
The game does not keep in memory the selected speed (basic and 70%) even if I set it to 300% when I start the game and it is always at 70%, but however the value I give it remains marked in the settings!!!
Second problem encountered is the screen resolution, if I set it to 1600x1900 (this is an example) the game adapts and there is no problem, but if I exit the game and restart it, the resolution returns to the base value of 640x720!! !
I think it's a fairly simple problem to solve.
I hope my report is helpful to you.
Keep it up, you're doing a great job!!!

**Comment by crudelios** [comment]
Hi!

This usually happens when you don't have permissions to write to the C3 folder.

You can either try moving the C3 folder out of `Program Files`, or running Augustus as administrator. That should allow the settings file to be overwritten and your changes to be remembered on the next game boot.

**Comment by SnakeSortITA** [comment]
OK, thanks a lot. I'll try. but where is the C3 folder located??? because I only see files with the words C3!!! at most send me a photo with the searched file/folder to move.
thanks so much again

**Comment by crudelios** [comment]
You should have an `ugusus-log.txt` file on the same folder where you placed augustus, can you post its contents here, please? That will show what the c3 install folder is.

**Comment by SnakeSortITA** [comment]
![Immagine](https://github.com/Keriew/augustus/assets/161051551/1644067d-5164-43fe-8cf4-e550abee1c87)

**Comment by crudelios** [comment]
Okay regarding the game speed, it's by design.

We changed the game so every save loads at 70% speed so you aren't taken by surprise when loading a new save.

But the resolution should stick when quitting and reopening the game.

Please open your `augustus-log.txt` file and post it here.

**Comment by SnakeSortITA** [comment]
Resolved. in the settings there is a box to press "full screen" which I had selected thinking that it would automatically be set to 1600x900 of my screen. And instead it kept reporting the value to 640 x 360 (or something like that) I'll post a photo for you to understand. So I deselected it and now it keeps me at the selected resolution
![Uploading Immagine.png…]()

**Comment by crudelios** [comment]
Oh I see, that setting below is resolution in windowed mode.

Anyway, glad you got that sorted out!
