### ISSUE TITLE
Crash in the map editor when loading scenario events

### ISSUE THREAD

**Issue by ninemiroslav** [Keriew/augustus#1052]
Hi, I was running the map editor to try to load some scenario events and the program immediately crashed.

I have the Italian version of Caesar3 with the 1.1 patch applied and Augustus runs on Ubuntu 22.04.

I attach the map, scenario events that I wanted to load and the log.

Greetings

Mirko
[files.zip](https://github.com/Keriew/augustus/files/14522213/files.zip)

**Comment by crudelios** [comment]
Hi,

Sorry it took me so long to answer.

This crash is already fixed on the latest unstable.

However, it seems you're trying to load messages as events, which obviously won't work.
