### ISSUE TITLE
UI-Button for mothball

### ISSUE THREAD

**Issue by destinationwalker** [Keriew/augustus#1067]
I am on the latest unstable 152:
UI-Button for mothballing buildings is bugged. See the screenshots.
![Mothball1](https://github.com/Keriew/augustus/assets/159162256/dc2e8a94-3b9b-4e8f-9c62-b604bda8c1ec)
![Mothball2](https://github.com/Keriew/augustus/assets/159162256/7f7bd741-e4ab-417e-8563-c1c2f869c59c)
![Mothball3](https://github.com/Keriew/augustus/assets/159162256/0fbfbb95-adb5-47ea-b6b5-d560b9b67a01)
![Mothball4](https://github.com/Keriew/augustus/assets/159162256/059dbb3d-5c52-4030-a91f-2a4796667a1c)

**Comment by Areldir** [comment]
Thank you for the report. This was an oversight on my part and I have fixed it in commit: a78dce3. If you come across any other visual bugs, feel free to post them and I will try to resolve them as soon as possible.
