### ISSUE TITLE
Suggestion: Quick Information on the Info Overlay

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#107]
Please exclude this thread.

**Comment by crudelios** [comment]
I'm not so sure about this, actually. You can already press a single hotkey to go to the chief advisor and have acces to all the relevant information, so at first glance there's little to gain from this feature.

**Comment by arkimedes1967** [comment]
@crudelios, as you said, the relevant information is on the chief advisor but we could complement it with more refined information - like the consumption rates of food to estimate how many people we're able to feed with the active fields, for exemple.

I'll give you another exemple, the exports. Do you know for sure the missed quota of a certain export every year? Don't you think this is relevant?

**Comment by crudelios** [comment]
I don't think we should provide things like the consumption rate of food. People may figure it out, but you shouldn't tell them straight.

Regarding the missed quota of an export, if the info overlay is context sensitive, when should that information be displayed? I do think it would make sense to add the last year's exports in the trade advisor/empire map though.

**Comment by arkimedes1967** [comment]
I know that wheat farms can feed ruflly 320 people and half of that on the northen cities. I think it might be relevant to tell the player that, for exemple, their 4 wheat active fields can only feed 1.280 people. Tell the player the result not the ratio.

_Regarding the missed quota of an export, if the info overlay is context sensitive, when should that information be displayed?_

Montly.

EXPORTS
Pottery 40 (32)
Marble 25 (25)

**Comment by arkimedes1967** [comment]
On my point of view, the information below is relevant to be shown on the side bar (overlay). It's simple and direct. I think it's worth to think about.

![Relevant Information](https://user-images.githubusercontent.com/64329357/87338384-ffe30880-c53c-11ea-801e-f65546556e27.jpg)
