### ISSUE TITLE
Augustus No animation videos

### ISSUE THREAD

**Issue by Maverick0010** [Keriew/augustus#1072]
Hi All,

I don't have any videos/animations, including no intro video at the start of the game as well as no videos during the game. I installed ceasar 3 base version no problem  after adding Augusta no more videos, everything else is working. Using steam. Any suggestion what I can look for? Googled a lot and haven't found a post with that kind of problem yet. Many Thanks

**Comment by crudelios** [comment]
Hi,

For the intro videos, make sure you set the option "Play intro videos" in the config window, otherwise they will be skipped.

As for the remaining videos, do you have an `smk` folder on the game folder?

**Comment by Maverick0010** [comment]
Hey, thanks so much the information. It works now. I didn't see that tick,
awesome.
 Thank you so much

**Comment by crudelios** [comment]
Glad it's fixed!
