### ISSUE TITLE
Can I play on Windows XP?

### ISSUE THREAD

**Issue by dudekt** [Keriew/augustus#108]
Can I play on windows XP? Displays an incompatible version message. Julius works for me.

**Comment by Keriew** [comment]
Could you try the latest unstable build and tell me if it works? If it doesn't, could you copy the error message?

**Comment by dudekt** [comment]
> Could you try the latest unstable build and tell me if it works? If it doesn't, could you copy the error message?

Hi! Thanks for reply. I have tried the latest unstable version and I have the same message. I have windows XP SP2. I suppose some library is missing. The message is "augustus.exe is not a valid Win32 application".

Screen: [https://postimg.cc/TLjLzsY8](https://postimg.cc/TLjLzsY8)

**Comment by crudelios** [comment]
That's probably because WinXP is 32 bits and Julius is being compiled as a 64 bit application.

**Comment by dudekt** [comment]
> That's probably because WinXP is 32 bits and Julius is being compiled as a 64 bit application.

Julius works on Windows XP. I have a problem with Augustus.

**Comment by crudelios** [comment]
I meant Augustus, sorry.

**Comment by Keriew** [comment]
No, it's been compiled as 32 bit application for a while. I tried using some older toolchains, supporting windows xp, could you check if this works? 
[augustus.zip](https://github.com/Keriew/augustus/files/4921615/augustus.zip)

**Comment by dudekt** [comment]
> No, it's been compiled as 32 bit application for a while. I tried using some older toolchains, supporting windows xp, could you check if this works?
> [augustus.zip](https://github.com/Keriew/augustus/files/4921615/augustus.zip)

Thanks! It works!

**Comment by Keriew** [comment]
Okay, thanks. Will use them for the new releases.
