### ISSUE TITLE
Wrong Selection in Orig Campaign

### ISSUE THREAD

**Issue by destinationwalker** [Keriew/augustus#1081]
In Original Campaign when you decide next Mission Tarsus and Tingis are changed. Maybe since new campaign feature implemented? Tested it with 4.0.0.228

![Tarsus vs Tingis](https://github.com/Keriew/augustus/assets/159162256/b4f44b78-4369-4593-bd94-2dac3c1a0e32)

**Comment by crudelios** [comment]
Try the latest unstable please, there was a bug with the mission positions that was since fixed.

**Comment by crudelios** [comment]
I'm fairly certain this is already fixed, so I'm closing this.
