### ISSUE TITLE
Map Editor bug

### ISSUE THREAD

**Issue by eugenikus8** [Keriew/augustus#1105]
**Adjust trade route traded amount**
It is not possible to set a negative value. There is no button for this. Or rather, it is there, but invisible. If you move the cursor over its conditional location and click, the value will become negative, but now you cannot confirm the change. It is reset to zero.
I haven’t checked further yet, but perhaps there is a similar bug somewhere else.
#####
<img src="https://i.imgur.com/AXTZhNG.jpeg" />

**Comment by crudelios** [comment]
I'll guessing this sets an absolute value, not a relative one, so in that case it makes no sense to have negative values. But I'm only guessing.

**Comment by eugenikus8** [comment]
I thought if the value is negative, then the number of goods bought/sold will decrease by that much.

**Comment by crudelios** [comment]
I think that is the case for the original requests window, but not for custom events.
