### ISSUE TITLE
"troops require" request

### ISSUE THREAD

**Issue by eugenikus8** [Keriew/augustus#1112]
How do I complete the Emperor's request 'troops required'  to defend the city? I'm ready to send them. I've chosen which legions will serve the empire, and how do I send them?
![2024-06-10_041657](https://github.com/Keriew/augustus/assets/51211736/fea567be-98d4-4f62-9649-0721049a3c3f)
![2024-06-10_041639](https://github.com/Keriew/augustus/assets/51211736/8ef61275-308e-4c7c-8318-869ecaaf2589)
![2024-06-10_102753](https://github.com/Keriew/augustus/assets/51211736/99d19fdf-ee93-4382-a627-a747e918b6ab)

**Comment by crudelios** [comment]
That's clearly a bug. Can you provide the save file please?

**Comment by eugenikus8** [comment]
[444444.zip](https://github.com/user-attachments/files/15758651/444444.zip)

**Comment by crudelios** [comment]
Oh I see.

Now um curious if this issue can also happen on the original game. How did you do it exactly?

Internally troops for distant battle are considered a sort of special resource, but they shouldn't be available for you to select them the way you did.

**Comment by eugenikus8** [comment]
I don't know much about the editor's innovations. 
Just wanted to make a request for legions to defend a Roman city. I didn't know how to do this correctly, I thought it should be done through the request of the emperor.
After all, there appeared in the list of resources 'troops'. I thought that was it.
And it turns out that the legions request is made through the Invasion "distant battle".
I was amused by the line in the game in the query menu 'Troops in warehouses 0.
