### ISSUE TITLE
 Extra information in the control panel

### ISSUE THREAD

**Issue by agodiluggo** [Keriew/augustus#1121]
Hi, 
i have a problem with "Extra information in the control panel". I active the option but in User Interface I cannot see Ratings and Requests. 
How can i fix it? Thanks all for the support.
![Bug_Interface](https://github.com/Keriew/augustus/assets/172895418/5795057e-12aa-466a-a2c0-b742914106b9)

**Comment by eugenikus8** [comment]
Reduce UI Scale?

**Comment by agodiluggo** [comment]
Thanks! It works, now i can see all the options
