### ISSUE TITLE
Stray button

### ISSUE THREAD

**Issue by TheRealAyCe** [Keriew/augustus#1132]
![button](https://github.com/Keriew/augustus/assets/11407231/60348f6d-0f37-46cc-a7cf-a790971e7c6a)

Goods report button is there, probably forgot to hide

**Comment by TheRealAyCe** [comment]
Same problem with market

**Comment by eugenikus8** [comment]
Duplicate #1126

**Comment by crudelios** [comment]
Fixed by [dabc144](https://github.com/Keriew/augustus/commit/dabc144bf3a3459f1d7f2d08b87afaf12a0defb5)
