### ISSUE TITLE
Wishlist: Provide basic Linux binaries with releases

### ISSUE THREAD

**Issue by vv221** [Keriew/augustus#1135]
Please consider providing "classic" Linux binaries with releases, in addition to the AppImage.
This would help a lot in including Augustus in other projects.

---

I would like to add support for Augustus into [./play.it](https://git.dotslashplay.it/scripts/about/), a free/libre installer for DRM-free commercial games on Linux, that makes games installation easier by automating the build of native packages from a collection of games installers.

We currently support the Cæsar Ⅲ installers sold on gog.com, building packages that rely on Julius to run on Linux. I think it would be nice if we could provide support for Augustus as an alternative to Julius.

---

Please have a look at the similar request I sent to the Julius team a couple years ago, it might already answer some of the questions you might have about the usefulness of dynamic binaries in this context: https://github.com/bvschaik/julius/issues/383

For anything that does not have an answer there already, feel free to ask here.

**Comment by crudelios** [comment]
We got you covered 😉 

Linux x64 release build: https://augustus.josecadete.net/download/latest/release/linux

Linux x64 latest dev build: https://augustus.josecadete.net/download/latest/development/linux

**Comment by vv221** [comment]
Please don’t tell me these have been available for years and I failed to find them…
Thanks for sharing that, Augustus support in ./play.it is on its way!

**Comment by crudelios** [comment]
> Please don’t tell me these have been available for years and I failed to find them…

Ok, I won't tell you that, then 😉 

> Thanks for sharing that, Augustus support in ./play.it is on its way!

That's great to know! Don't forget to add the game assets as well 🙂

**Comment by vv221** [comment]
> That's great to know! Don't forget to add the game assets as well 🙂

Is that about assets provided by Augustus? Or the original game assets?
The later are already covered by our Julius support, that will be shared with the Augustus support.

**Comment by crudelios** [comment]
Yeah I mean the assets provided by augustus.

Release assets: https://augustus.josecadete.net/download/latest/release/assets

Latest dev assets: https://augustus.josecadete.net/download/latest/development/assets
