### ISSUE TITLE
augustus startup

### ISSUE THREAD

**Issue by Spike2701** [Keriew/augustus#1137]
what do I have to do here? this appears on startup
![Zrzut ekranu 2024-07-20 170002](https://github.com/user-attachments/assets/c826f061-03fa-4a00-b38c-2ae6923cf2c6)

**Comment by Keriew** [comment]
You have to select the folder where you have _Caesar 3_ installed. _Augustus_ requires the base game to run.

**Comment by Keriew** [comment]
I'll assume the solution worked. Please reopen if you have any further difficulties.
