### ISSUE TITLE
Change how culture rating is calculated

### ISSUE THREAD

**Issue by pavel-klavik** [Keriew/augustus#115]
I would add an option which would make culture rating interesting. Currently it is computed based on the number of people in your city and the number of building. This leads to massive building of libraries, theaters, academies somewhere outside the city in the end of the mission to satisfy the requirement (which is good for sinking employees there, but not that much fun). I would change this to calculate the number of houses which have coverage. This would lead to adding academies, etc. to all your housing blocks instead of this.

**Comment by cdsmith-umn** [comment]
I believe there is something in the works to make changes to this calculation. If I recall correctly, it was mentioned to be along these lines.

**Comment by Legionary2** [comment]
Yes a full culture update will eventually be in the works

**Comment by Areldir** [comment]
Culture rating is a long standing issue, and we are currently working on addressing it. You can expect a fix in the next major update. Also, to avoid issue duplication, I'm closing this one.
