### ISSUE TITLE
"Not Accepting" Granary still gets food from warehouses

### ISSUE THREAD

**Issue by cdsmith-umn** [Keriew/augustus#118]
I was playing Massilia over the weekend. I set up a few fruit farms so I could export fruit. I built a warehouse nearby, as well as a granary. I set the warehouse to only accept fruit and I set the granary to not accept fruit. The granary's cart pusher would still go to the warehouse and get fruit whenever there was a vacancy in the granary. The fruit would never actually be available to my population to eat; it would simply disappear.

Expected behaviour is that the granary cart pushers should completely ignore food sitting in warehouses that they are not allowed to store in the granary.

**Comment by Keriew** [comment]
I did a quick test and it seems to work as intended. Could you provide a save with the setup and the augustus.ini file so I can look what causes the problem? Also, are you playing 1.4.1a or one of the recent unstables?

**Comment by cdsmith-umn** [comment]
I'll get that for you this weekend. I'm using 1.4.1a.

**Comment by cdsmith-umn** [comment]
I tried to recreate the problem, but I couldn't. I don't have the original game in which that happened, as I hadn't saved it after starting the scenario. (I have each scenario in the campaign saved right at the start so I can play whichever one I want whenever I want.) So I'm going to close this issue. If it reoccurs, then I'll make sure to save the game and provide you a copy.
