### ISSUE TITLE
Return all legions to fort

### ISSUE THREAD

**Issue by TKharaishvili** [Keriew/augustus#121]
It would be great to be able to return all the legions to their respective forts with a single button click. Similar to refusing all goods in warehouses and such.

I'm sending a PR as well - https://github.com/Keriew/augustus/pull/122

No pressure, you don't have to review it if you don't like the suggestion itself. Otherwise I'm looking forward to your review!

**Comment by Areldir** [comment]
As this discussion is now over on the PR itself, I'm closing this issue.
