### ISSUE TITLE
Enable granaries to get all types of food

### ISSUE THREAD

**Issue by cdsmith-umn** [Keriew/augustus#124]
I would like granaries to be able to get all the types of food available. What I mean by this is that, on some maps, you might have only three types of food available between farming, fishing, and importing. The problem I'm encountering is that, when Mercury gives his blessing and the granary that received the food is not near housing, then my granaries near the housing cannot get the fourth type of food.

Let's use Londinium as an example. On this map, you can grow wheat, vegetables, and pigs (meat). When Mercury gives his blessing, then you also receive fruit. If the granary that received the fruit is not near housing, then the fruit sits unused in the granary and takes up space. I would like to be able to tell a granary that is near housing to get fruit, which would enable me to make use of it. Since the granaries cannot get this type of food, then I also cannot set them to not accept that type of food, either.

I have attached a screenshot of the granary special orders UI while playing the Londinium scenario.
![Londinium_granary_special_orders](https://user-images.githubusercontent.com/9805709/89782450-ee106900-dada-11ea-85cf-fcb12390b51e.png)

**Comment by cdsmith-umn** [comment]
That is not correct. The image above displays the food types available in Londinium, even after trade routes are available. Fruit is never available, except in the circumstance that Mercury has granted his blessing. Londinium is not the only map on which something like this happens. Tarsus is another one: only wheat and fish are available, with wheat being an import.

**Comment by Legionary2** [comment]
This is something can be  corrected. Blessing should not provide foods which aren’t available . And should also try to work within the confines of which granaries are accepting what - thanks for the post. Join gamerzakh discord if you want to see a more active community and updates

**Comment by CaptainKehoe** [comment]
@Legionary2 "Blessing" = 'Magical' Divine Powers... any foods can appear ... even Deep Fried Oreos if Mercury so chooses.

**Comment by Legionary2** [comment]
> @Legionary2 "Blessing" = 'Magical' Divine Powers... any foods can appear ... even Deep Fried Oreos if Mercury so chooses.

Lol would it be a luxury good ?

**Comment by Legionary2** [comment]
Also , festivals with the monument update will be getting some changes. As to what exactly , I can’t specify yet but there will be additional special bonuses for the monument temples once constructed.

**Comment by cdsmith-umn** [comment]
> Also , festivals with the monument update will be getting some changes. As to what exactly , I can’t specify yet but there will be additional special bonuses for the monument temples once constructed.

Now I have to figure out Discord and get in on this information!

**Comment by cdsmith-umn** [comment]
@Legionary2 Closing this issue since blessings are changing in the coming release and this will no longer be an issue.
