### ISSUE TITLE
Placed Roadblock doesn't display properly

### ISSUE THREAD

**Issue by Riww** [Keriew/augustus#141]
As the title says, roadblocks aren't correctly displayed. They are definitely there, it just looks like the road is only distorted somehow, no roadblock can be seen.

**Comment by crudelios** [comment]
What build are you using? If you're using a recent one you need to copy the `mods` folder to the C3 directory as well.

**Comment by Riww** [comment]
Thanks, didn't know that. In stable build this extra step isn't required.
