### ISSUE TITLE
[Windows 10] No graphics are displayed in Augustus v2.0.0 for any buildings added by the mod

### ISSUE THREAD

**Issue by Ivan-Cristian** [Keriew/augustus#142]
Steps:
1. Download v2.0.0 of Augustus
2. Extract it in a folder that is not the Caesar 3 installation folder
3. Run Augustus
4. Start any map
5. Build any new building added by v2, or a roadblock

Expected:
All new buildings are displayed correctly

Actual:
No new buildings are displayed correctly, it seems like the game is not loading them correctly

[screenshot of error](https://i.imgur.com/2R1hTMp.png)

**Comment by Legionary2** [comment]
You have to extract the contents , including the mod folder into the directory where you are launching the exe from
