### ISSUE TITLE
Can't delete ponds that blocked path to Rome

### ISSUE THREAD

**Issue by Flucin** [Keriew/augustus#144]
I accidentally blocked the path to Rome by placing a large and a small pond. After the message saying that it's blocked, it didn't get crushed, it just stayed there and I'm unable to delete it or build anything on top of it.

**Comment by Legionary2** [comment]
Hi there we will look into the issue . Currently as it stands , is the map effectively unplayable now since immigrants can’t enter the map ?

**Comment by Keriew** [comment]
Fixed with a29b1e3 . Thanks for the report!
