### ISSUE TITLE
french translation for 2.0

### ISSUE THREAD

**Issue by Trokinos** [Keriew/augustus#146]
Hello,

I noticed that the french translation 
https://github.com/Keriew/augustus/blob/master/src/translation/french.c
features 2 times the lines : 
#include "translation/common.h"
#include "translation/translation.h"

#include "translation/common.h"
#include "translation/translation.h"

I'm not sure it's on purpose so i prefered to report it as a bug.  

Additionally, Augustus 2.0 features lots of new texts that aren't yet translated in the french version.
As i'm not coder and tech savy enough to actually know how to make a pull request or compile the game correctly,  i hope i can help by adding those translated lines that are present in the english translation but currently missing from the current french translation (i hope i didn't made a mistake, it's just the extra missing entries, not the full french.c file ) :  

    {TR_BUILDING_ENGINEER_GUILD, "Guilde des ingénieurs" },
    {TR_BUILDING_ENGINEER_GUILD_DESC, "Ici, les ingénieurs travaillent sans relâche pour construire des monuments pour la gloire de Rome." },
    {TR_BUILDING_GRAND_TEMPLE_ADD_MODULE, "Accorder une épithète au temple" },
    {TR_BUILDING_GRAND_TEMPLE_CERES, "Cérès" },
    {TR_BUILDING_GRAND_TEMPLE_NEPTUNE, "Neptune" },
    {TR_BUILDING_GRAND_TEMPLE_MERCURY, "Mercure" },
    {TR_BUILDING_GRAND_TEMPLE_MARS, "Mars" },
    {TR_BUILDING_GRAND_TEMPLE_VENUS, "Venus" },
    {TR_BUILDING_PANTHEON, "Panthéon" },
    {TR_BUILDING_GRAND_TEMPLE_CERES_DESC, "Temple monumental de Cérès" },
    {TR_BUILDING_GRAND_TEMPLE_NEPTUNE_DESC, "Temple monumental de Neptune" },
    {TR_BUILDING_GRAND_TEMPLE_MERCURY_DESC, "Temple monumental de Mercure" },
    {TR_BUILDING_GRAND_TEMPLE_MARS_DESC, "Temple monumental de Mars" },
    {TR_BUILDING_GRAND_TEMPLE_VENUS_DESC, "Temple monumental de Venus" },
    {TR_BUILDING_PANTHEON_DESC, "Pantheon" },
    {TR_BUILDING_GRAND_TEMPLE_CERES_BONUS_DESC, "Les charretiers des fermes se déplacent 50% plus vite." },
    {TR_BUILDING_GRAND_TEMPLE_NEPTUNE_BONUS_DESC, "Accorde +1 distance pour les fontaines et puits et +2 pour les réservoirs. La main-d'œuvre des services d'eau est réduite de 50%. Les navires marchands voyagent 25% plus vite." },
    {TR_BUILDING_GRAND_TEMPLE_MERCURY_BONUS_DESC, "Les commerçants terrestres et maritimes ont une capacité supplémentaire de 50%. Les commerçants terrestres se déplacent 25% plus vite." },
    {TR_BUILDING_GRAND_TEMPLE_MARS_BONUS_DESC, "Forme les soldats comme une caserne. Quatre forts supplémentaires peuvent être construits." },
    {TR_BUILDING_GRAND_TEMPLE_VENUS_BONUS_DESC, "Les jardins, les statues et les temples de la ville brillent d'une beauté accrue, ce qui augmente leur attrait. Les maisons stockent plus de marchandises et décroissent plus lentement." },
    {TR_BUILDING_PANTHEON_BONUS_DESC, "Donne accès à tous les dieux. Organise des festivals annuels et réduit les taxes du temple de 25%." },
    {TR_BUILDING_GRAND_TEMPLE_CERES_MODULE_1_DESC, "Les prêtres réduisent la consommation alimentaire de 20%." },
    {TR_BUILDING_GRAND_TEMPLE_NEPTUNE_MODULE_1_DESC, "Les temples produisent des conducteurs de char pour l'hippodrome." },
    {TR_BUILDING_GRAND_TEMPLE_MERCURY_MODULE_1_DESC, "Les prêtres réduisent de 20% la consommation de poterie et de meubles." },
    {TR_BUILDING_GRAND_TEMPLE_MARS_MODULE_1_DESC, "Les temples génèrent de la nourriture, en fonction du nombre de maisons qu'ils couvrent, et la livrent au poste de ravitaillement." },
    {TR_BUILDING_GRAND_TEMPLE_VENUS_MODULE_1_DESC, "Le Temple monumental produit du vin en quantité adaptée à la population de la ville avec accès au temple de Vénus. Les temples le collectent et le distribuent dans les maisons." },
    {TR_BUILDING_GRAND_TEMPLE_CERES_MODULE_2_DESC, "Les prêtres collectent et distribuent à la fois de l'huile et un type de nourriture dans les entrepôts de la ville." },
    {TR_BUILDING_GRAND_TEMPLE_NEPTUNE_MODULE_2_DESC, "Les prêtres augmentent la capacité d'hébergement de 5%. Le Temple monumental fournit de l'eau comme un réservoir rempli." },
    {TR_BUILDING_GRAND_TEMPLE_MERCURY_MODULE_2_DESC, "Les prêtres réduisent de 20% la consommation d'huile et de vin." },
    {TR_BUILDING_GRAND_TEMPLE_MARS_MODULE_2_DESC, "Les prêtres réduisent de 10% la consommation de tous les biens." },
    {TR_BUILDING_GRAND_TEMPLE_VENUS_MODULE_2_DESC, "Les prêtres fournissent des divertissements et embellissent eux-mêmes les maisons, augmentant ainsi l'attractivité du quartier sans décoration supplémentaire." },
    {TR_BUILDING_PANTHEON_MODULE_1_DESC, "Tous les temples de la ville envoient des prêtres au Panthéon, répandant la foi et les bénédictions de leurs dieux." },
    {TR_BUILDING_PANTHEON_MODULE_2_DESC, "Les maisons avec accès au Panthéon peuvent évoluer d'une étape supplémentaire." },
    {TR_BUILDING_GRAND_TEMPLE_CERES_DESC_MODULE_1, "Temple de Ceres Promitor" },
    {TR_BUILDING_GRAND_TEMPLE_CERES_DESC_MODULE_2, "Temple de Ceres Reparator" },
    {TR_BUILDING_GRAND_TEMPLE_NEPTUNE_DESC_MODULE_1, "Temple de Neptunus Equester" },
    {TR_BUILDING_GRAND_TEMPLE_NEPTUNE_DESC_MODULE_2, "Temple de Neptunus Adiutor" },
    {TR_BUILDING_GRAND_TEMPLE_MERCURY_DESC_MODULE_1, "Temple de Mercurius Fortunus" },
    {TR_BUILDING_GRAND_TEMPLE_MERCURY_DESC_MODULE_2, "Temple de Mercurius Abundantia" },
    {TR_BUILDING_GRAND_TEMPLE_MARS_DESC_MODULE_1, "Temple de Mars Ultor" },
    {TR_BUILDING_GRAND_TEMPLE_MARS_DESC_MODULE_2, "Temple de Mars Quirinus" },
    {TR_BUILDING_GRAND_TEMPLE_VENUS_DESC_MODULE_1, "Temple de Venus Verticordia" },
    {TR_BUILDING_GRAND_TEMPLE_VENUS_DESC_MODULE_2, "Temple de Venus Genetrix" },
    {TR_BUILDING_PANTHEON_DESC_MODULE_1, "Pantheum Ara Maxima" },
    {TR_BUILDING_PANTHEON_DESC_MODULE_2, "Pantheum Roma Aeterna" },
    {TR_BUILDING_GRAND_TEMPLE_MENU, "Temple monumental" },
    {TR_BUILDING_WORK_CAMP, "Camp de travail" },
    {TR_BUILDING_WORK_CAMP_DESC, "Les ouvriers se rassemblent ici pour transporter les matériaux vers les chantiers de construction." },
	{TR_REQUIRED_RESOURCES, "Ressources livrées pour la phase actuelle:"},
    {TR_BUILDING_GRAND_TEMPLE_CONSTRUCTION_DESC, "La construction de temple monumentaux nécessite du matériel stocké dans un entrepôt, des ouvriers d'un camp de travail et des ingénieurs d'une guilde d'ingénieurs."},
    {TR_CONSTRUCTION_PHASE, "Construction phase:"},
    {TR_ADD_MODULE, "Reconsacrer temple?"},
    {TR_BUILDING_TEMPLE_MODULE_CONSTRUCTED, "Epithet accordée."},
    {TR_BUILDING_CERES_TEMPLE_QUOTE, "La première Cérès a appris à la biche qui travaillait à labourer\nLa Terre enceinte et à faire semer la graine.\nLa première pour l'homme a fourni une nourriture saine\nEt avec des lois justes fournies par le monde méchant.\n-Ovide, les Métamorphoses, Livre V "},
    {TR_BUILDING_NEPTUNE_TEMPLE_QUOTE, "Les flots tombent, tandis que Neptune pose sa masse\nSur la mer agitée et lisse son visage sillonné.\nDéjà Triton, à son appel, apparaît au-dessus des vagues;\na robe tyrienne qu'il porte;\nEt dans sa main une trompette tordue porte.\n-Ovide, les Métamorphoses, Livre I "},
    {TR_BUILDING_MERCURY_TEMPLE_QUOTE, "Le bétail et les gros moutons peuvent tous être obtenus pour le raid,\ntripodes pour le commerce et étalons à tête fauve.\nMais le souffle de vie d'un homme ne peut pas revenir -\npas de pillards en force, aucun commerce ne le ramène, \nquand il glisse entre les dents serrées d'un homme.\n-Homer, L'Iliade, Livre IX "},
    {TR_BUILDING_MARS_TEMPLE_QUOTE, "Pour Mars, réparez ses arbres d'axes cassés et sa guerre émoussée,\nEt renvoyez-le avec les armes fourrées,\nPour réveiller la guerre paresseuse avec les alarmes bruyantes des trompettes.\n-Virgil, l'Énéide, Livre VIII"},
    {TR_BUILDING_VENUS_TEMPLE_QUOTE, "Par Cupidon ailé et Vénus, sa tendre mère,\nQuelle grande joie j'ai eue!\nComment la passion m'a clairement touché!\nComment mon cœur a fondu là où je gisais!\n-Ovide, les Métamorphoses, Livre IX "},
    {TR_BUILDING_PANTHEON_QUOTE, "Les portes du ciel se dévoilent: Jupiter convoque tous\nLes dieux au conseil dans la salle commune.\nSubilement assis, il observe de loin\nLes champs, le camp, la fortune de la guerre,\nEt tout le monde inférieur . Du premier au dernier,\nLe sénat souverain en degrés est placé.\n-Virgile, L'Enéide, Livre X "},
    {TR_BUILDING_GRAND_TEMPLE_PHASE_1, "(Podium)"},
    {TR_BUILDING_GRAND_TEMPLE_PHASE_2, "(Portico)"},
    {TR_BUILDING_GRAND_TEMPLE_PHASE_3, "(Cella)"},
    {TR_BUILDING_GRAND_TEMPLE_PHASE_4, "(Praecinctum)"},
    {TR_BUILDING_GRAND_TEMPLE_PHASE_5, "(Dedicatio)"},
    {TR_BUILDING_GRAND_TEMPLE_PHASE_1_TEXT, "Les ouvriers construisent le podium qui élèvera le temple et fournira une base solide pour résister au passage du temps." },
    {TR_BUILDING_GRAND_TEMPLE_PHASE_2_TEXT, "Les artisans fabriquent le portique, qui porte l'autel sacrificiel du temple." },
    {TR_BUILDING_GRAND_TEMPLE_PHASE_3_TEXT, "Les ingénieurs sont en train de fabriquer la cella, l'intérieur du temple qui abrite les images sacrées." },
    {TR_BUILDING_GRAND_TEMPLE_PHASE_4_TEXT, "Les travaux sur le praecinctum du temple ont commencé, où les fidèles se rassembleront à l'extérieur pour des cérémonies publiques." },
    {TR_BUILDING_GRAND_TEMPLE_PHASE_5_TEXT, "Le temple étant presque terminé, les prêtres se rassemblent pour accomplir les rites de consécration." },
    {TR_BUILDING_MENU_TREES, "Arbres" },
    {TR_BUILDING_MENU_PATHS, "Chemins" },
    {TR_BUILDING_MENU_PARKS, "Parcs"},
    {TR_BUILDING_SMALL_POND, "Petit bassin"},
    {TR_BUILDING_LARGE_POND, "Grand bassin"},
    {TR_BUILDING_PINE_TREE, "Pin"},
    {TR_BUILDING_FIR_TREE, "Sapin" },
    {TR_BUILDING_OAK_TREE, "Chêne" },
    {TR_BUILDING_ELM_TREE, "Orme" },
    {TR_BUILDING_FIG_TREE, "Figuier" },
    {TR_BUILDING_PLUM_TREE, "Prunier" },
    {TR_BUILDING_PALM_TREE, "Palmier" },
    {TR_BUILDING_DATE_TREE, "Datier" },
    {TR_BUILDING_PINE_PATH, "Chemin de pin" },
    {TR_BUILDING_FIR_PATH, "Chemin de sapin" },
    {TR_BUILDING_OAK_PATH, "Chemin de chêne" },
    {TR_BUILDING_ELM_PATH, "Chemin d'orme" },
    {TR_BUILDING_FIG_PATH, "Chemin de figuier" },
    {TR_BUILDING_PLUM_PATH, "Chemin de prunier" },
    {TR_BUILDING_PALM_PATH, "Chemin de palmier" },
    {TR_BUILDING_DATE_PATH, "Chemin de datier" },
    {TR_BUILDING_BLUE_PAVILION, "Pavillon bleu" },
    {TR_BUILDING_RED_PAVILION, "Pavillon rouge"},
    {TR_BUILDING_ORANGE_PAVILION, "Pavillon orange"},
    {TR_BUILDING_YELLOW_PAVILION, "Pavillon jaune"},
    {TR_BUILDING_GREEN_PAVILION, "Pavillon vert" },
    {TR_BUILDING_SMALL_STATUE_ALT, "Statue de Déesse" },
    {TR_BUILDING_SMALL_STATUE_ALT_B, "Statue de Sénateur"},
    {TR_BUILDING_OBELISK, "Obelisque" },
    {TR_BUILDING_POND_DESC, "Les bassins se remplissent des réservoirs de la ville et fournissent de l'eau pour les plantes et les animaux et une oasis fraîche et relaxante pour les gens. Tous les citoyens aimeraient vivre près d'un basin." },
    {TR_BUILDING_WINDOW_POND, "Bassin"},
    {TR_BUILDING_OBELISK_DESC, "Un monument prestigieux, œuvre d'un ancien roi du Nil. Les Egyptiens ne l'utilisaient pas."},
    {TR_ADVISOR_FINANCE_LEVIES, "Taxes de construction"},
    {TR_CONFIRM_DELETE_MONUMENT, "Démolir ce monument"},
    {TR_SELECT_EPITHET_PROMPT_HEADER, "Sélectionnez l'épithète à accorder"},
    {TR_SELECT_EPITHET_PROMPT_TEXT, "Accorder une épithète consacrera en permanence votre temple à un aspect de sa divinité, conférant aux prêtres un pouvoir divin. Cela coûtera 1000 Dn." },
    {TR_BUILDING_INFO_MONTHLY_LEVY, "/Mois"},
    {TR_BUILDING_MESS_HALL, "Poste de ravitaillement"},
    {TR_BUILDING_MESS_HALL_DESC, "Le poste de ravitaillement recueille de la nourriture dans les greniers de la ville pour nourrir les soldats stationnés dans les forts de la ville. Un poste de ravitaillement mal approvisionné ralentira le recrutement et nuira au moral."},
    {TR_BUILDING_MESS_HALL_FULFILLMENT, "L'approvisionnement alimentaire du mois dernier:"},
    {TR_BUILDING_MESS_HALL_TROOP_HUNGER, "Les soldats sont: " },
    {TR_BUILDING_MESS_HALL_TROOP_HUNGER_1, "Bien nourris" },
    {TR_BUILDING_MESS_HALL_TROOP_HUNGER_2, "Nourris"},
    {TR_BUILDING_MESS_HALL_TROOP_HUNGER_3, "Affamés"},
    {TR_BUILDING_MESS_HALL_TROOP_HUNGER_4, "Très affamés"},
    {TR_BUILDING_MESS_HALL_TROOP_HUNGER_5, "En famine"},
    {TR_BUILDING_MESS_HALL_FOOD_TYPES_BONUS_1, "Le régime alimentaire varié de vos soldats augmente considérablement le moral."},
    {TR_BUILDING_MESS_HALL_FOOD_TYPES_BONUS_2, "Le régime alimentaire varié et nutritif dont bénéficient vos soldats augmente considérablement le moral."},
    {TR_BUILDING_MESS_HALL_NO_SOLDIERS, "Vous n'avezs pas de soldats à nourrir." },
    {TR_BUILDING_MESS_HALL_MONTHS_FOOD_STORED, "Mois de nourriture stockée:" },
    {TR_BUILDING_BARRACKS_FOOD_WARNING, "Les pénuries alimentaires à votre poste de ravitaillement ralentissent le recrutement des soldats."},
    {TR_BUILDING_BARRACKS_FOOD_WARNING_2, "Les pénuries alimentaires critiques à votre poste de ravitaillement paralysent le recrutement de soldats." },
    {TR_BUILDING_LEGION_FOOD_WARNING_1, "La récente pénurie alimentaire a fait baisser le moral"},
    {TR_BUILDING_LEGION_FOOD_WARNING_2, "La récente pénurie alimentaire a considérablement réduit le moral"},
    {TR_BUILDING_LEGION_STARVING, "Pénurie alimentaire" },
    {TR_ADVISOR_LEGION_FOOD_SATISFIED, "Vos soldats ont toute la nourriture dont ils ont besoin."},
    {TR_ADVISOR_LEGION_FOOD_NEEDED, "Vos soldats ont besoin de plus de nourriture." },
    {TR_ADVISOR_LEGION_FOOD_CRITICAL, "Vos soldats meurent de faim!"},
    {TR_ADVISOR_LEGION_MONTHS_FOOD_STORED, "Mois de nourriture stockée au poste de ravitaillement:" },
    {TR_CITY_MESSAGE_TITLE_MESS_HALL_NEEDS_FOOD, "Soldats affamés" },
    {TR_CITY_MESSAGE_TEXT_MESS_HALL_NEEDS_FOOD, "Votre poste de ravitaillement manque cruellement de nourriture et le moral de vos troupes diminue. Assurez-vous que votre poste de ravitaillement peut accéder à un grenier bien approvisionné."},
    {TR_CITY_MESSAGE_TEXT_MESS_HALL_MISSING, "Votre ville a perdu son poste de ravitaillement et vos troupes meurent de faim. Construisez immédiatement un poste de ravitaillement."},
    {TR_MARKET_SPECIAL_ORDERS_HEADER, "Marchandises à collecter"},
    {TR_WARNING_NO_MESS_HALL, "Vous devez d'abord construire un poste de ravitaillement pour nourrir vos soldats." },
    {TR_WARNING_MAX_GRAND_TEMPLES, "Seuls deux temples monumentaux être construits." },
    {TR_CITY_MESSAGE_TITLE_GRAND_TEMPLE_COMPLETE, "Temple monumental terminé"},
    {TR_CITY_MESSAGE_TEXT_GRAND_TEMPLE_COMPLETE, "Les prêtres et les fidèles affluent vers le nouveau temple monumental pour les rites de consécration. Votre peuple est impressionné par la majesté de vos œuvres et la divinité que vous avez choisie vous comble de faveur."},
    {TR_CITY_MESSAGE_TITLE_MERCURY_BLESSING, "Une bénédiction de Mercure" },
    {TR_CITY_MESSAGE_TEXT_MERCURY_BLESSING, "Ravi de votre dévouement, Mercure a béni votre industrie en découvrant des matières premières pour vos artisans."},
    {TR_FIGURE_TYPE_WORK_CAMP_WORKER, "Contremaître"},
    {TR_FIGURE_TYPE_WORK_CAMP_SLAVE, "Transporteur"},
    {TR_FIGURE_TYPE_WORK_CAMP_ENGINEER, "Ingénieur"},
    {TR_FIGURE_TYPE_MESS_HALL_BUYER, "Intendant"},
    {TR_FIGURE_TYPE_MESS_HALL_COLLECTOR, "Collecteur"},
    {TR_BUILDING_CERES_TEMPLE_MODULE_DESC, "Le temple monumental envoie des prêtres de Cérès pour aider à distribuer de la nourriture et de l'huile à vos citoyens affamés."},
    {TR_BUILDING_VENUS_TEMPLE_MODULE_DESC, "Le temple monumental permet aux prêtres de Vénus de fournir du vin sacré à vos citoyens." },
    {TR_BUILDING_MARS_TEMPLE_MODULE_DESC, "Le temple monumental forme les prêtres de Mars à fournir de la nourriture à votre poste de ravitaillement."},
    {TR_BUILDING_SMALL_TEMPLE_CERES_NAME, "Temple de Cérès"},
    {TR_BUILDING_SMALL_TEMPLE_NEPTUNE_NAME, "Temple de Neptune"},
    {TR_BUILDING_SMALL_TEMPLE_MERCURY_NAME, "Temple de Mercure"},
    {TR_BUILDING_SMALL_TEMPLE_MARS_NAME, "Temple de Mars"},
    {TR_BUILDING_SMALL_TEMPLE_VENUS_NAME, "Temple de Venus"},
    {TR_FIGURE_TYPE_PRIEST_BUYER, "Prêtre" },
    // Transcription of mission_exact4.wav
    {TR_PHRASE_FIGURE_MISSIONARY_EXACT_4, "\"Je ferai ce que je peux pour calmer ces barbares. Je suis sûr qu'ils arrêteront d'attaquer la ville quand j'aurai eu un mot avec eux.\"" },
    {TR_CITY_MESSAGE_TITLE_PANTHEON_FESTIVAL, "An annual festival"},
    {TR_CITY_MESSAGE_TEXT_PANTHEON_FESTIVAL_CERES, "Les fidèles affluent vers les temples pour la célébration de Cerealia, en l'honneur de Cérès. Les agriculteurs offrent des sacrifices pour de riches récoltes dans les années à venir."},
    {TR_CITY_MESSAGE_TEXT_PANTHEON_FESTIVAL_NEPTUNE, "C'est aujourd'hui la fête de Neptunalia, en l'honneur de Neptune. Les fidèles construisent des huttes de branches et de feuillages et se réjouissent sous la chaleur ardente du soleil d'été."},
    {TR_CITY_MESSAGE_TEXT_PANTHEON_FESTIVAL_MERCURY, "Les commerçants et les marchands se rassemblent en masse pour célébrer Mercuralia. De l'eau sacrée est aspergée sur les navires et les entrepôts dans l'espoir d'une protection divine contre le dieu Mercure."},
    {TR_CITY_MESSAGE_TEXT_PANTHEON_FESTIVAL_MARS, "Les citoyens se rassemblent à l'extérieur de la ville pour la célébration d'Equirria, pour chercher la faveur de Mars. L'air est rempli du tonnerre des sabots et du grincement des chars comme la race fidèle en l'honneur de leur dieu."},
    {TR_CITY_MESSAGE_TEXT_PANTHEON_FESTIVAL_VENUS, "Les fidèles se rassemblent pour la célébration de Veneralia, un jour sacré à Vénus. Vos citoyens la supplient de lui donner bonne fortune en matière de cœur."},    {TR_TOOLTIP_BUTTON_DELETE_READ_MESSAGES, "Delete read messages"},
    {TR_TOOLTIP_BUTTON_MOTHBALL_ON, "Désactivez ce bâtiment"},
    {TR_TOOLTIP_BUTTON_MOTHBALL_OFF, "Activez ce bâtiment"},
    {TR_TOOLTIP_BUTTON_ACCEPT_MARKET_LADIES, "Autoriser les vendeuses du marché à acheter à partir d'ici"},
    {TR_TOOLTIP_BUTTON_ACCEPT_TRADE_CARAVAN, "Autoriser les caravanes à commercer ici"},
    {TR_TOOLTIP_BUTTON_ACCEPT_TRADE_SHIPS, "Permettre aux navires de commerce de commercer ici"},
    {TR_CONFIG_HEADER_CITY_MANAGEMENT_CHANGES, "Gestion de la ville"},
    {TR_BUILDING_LIGHTHOUSE, "Phare"},
    {TR_BUILDING_LIGHTHOUSE_PHASE_1, "(Fondation)" },
    {TR_BUILDING_LIGHTHOUSE_PHASE_2, "(Piédestal)" },
    {TR_BUILDING_LIGHTHOUSE_PHASE_3, "(Tour)" },
    {TR_BUILDING_LIGHTHOUSE_PHASE_4, "(Couronne)" },
    {TR_BUILDING_LIGHTHOUSE_PHASE_1_TEXT, "Les ingénieurs posent des bases solides pour supporter le poids d'une grande tour de pierre." },
    {TR_BUILDING_LIGHTHOUSE_PHASE_2_TEXT, "Les maçons construisent le piédestal qui élèvera la flamme du phare bien au-dessus de l'horizon." },
    {TR_BUILDING_LIGHTHOUSE_PHASE_3_TEXT, "La tour du phare monte encore plus haut chaque jour alors que les maçons pratiquent soigneusement leur métier." },
    {TR_BUILDING_LIGHTHOUSE_PHASE_4_TEXT, "Les ingénieurs sont en train d'effectuer les dernières retouches sur le phare. Bientôt, il brillera sur des kilomètres, guidant les navires vers la maison." },
    {TR_BUILDING_LIGHTHOUSE_CONSTRUCTION_DESC, "La construction du phare nécessite du matériel stocké dans un entrepôt, des ouvriers d'un camp de travail et des ingénieurs d'une guilde d'ingénieurs." },
    {TR_BUILDING_LIGHTHOUSE_BONUS_DESC, "Les navires de pêche se déplacent 10% plus vite. Les tempêtes marines durent deux fois moins longtemps." },
    {TR_EDITOR_ALLOWED_BUILDINGS_MONUMENTS, "Monuments"},
    {TR_CITY_MESSAGE_TEXT_LIGHTHOUSE_COMPLETE, "Le phare achevé, une puissante tour de pierre, se profile à l'horizon. Que sa lumière guide les navires jusqu'à la fin des temps." },
    {TR_CITY_MESSAGE_TEXT_PANTHEON_COMPLETE, "Le Panthéon est terminé. Il est inégalé en tant que monument à la puissance impressionnante des dieux et du peuple de Rome." },
    {TR_CITY_MESSAGE_TITLE_MONUMENT_COMPLETE, "Monument terminé" },
    {TR_CITY_MESSAGE_TITLE_NEPTUNE_BLESSING, "Une bénédiction de Neptune"},
    {TR_CITY_MESSAGE_TEXT_NEPTUNE_BLESSING, "Récompensant le dévouement de votre ville, Neptune accorde un passage en douceur aux commerçants pendant douze mois, pendant lesquels vos exportations rapporteront la moitié du prix en plus."},
    {TR_CITY_MESSAGE_TITLE_VENUS_BLESSING, "Une bénédiction de Venus" },
    {TR_CITY_MESSAGE_TEXT_VENUS_BLESSING, "Ravie de la vénération joyeuse qui lui est témoignée, Vénus accorde jeunesse, santé et bonheur à votre peuple, augmentant ainsi la taille de votre population active." },
    {TR_BUILDING_MENU_STATUES, "Statues" },
    {TR_BUILDING_MENU_GOV_RES, "Demeures du gouverneur" },
    {TR_OVERLAY_ROADS, "Routes" },
    {TR_NO_MODS_TITLE, "Le dossier Mods ne peut être trouvé" },
    {TR_NO_MODS_MESSAGE,
        "Votre installation de Caesar 3 n'a pas de dossier mods correctement installé. "
        "Les nouveaux batiments ne seront pas correctement affichés.\n"
        "Veuillez vous assurer qu'un répertoire '/mods' existe dans le répertoire d'installation de Caesar 3." },
    {TR_WARNING_WATER_NEEDED_FOR_LIGHTHOUSE, "Le phare doit être placé près de l'eau"},
    {TR_TOOLTIP_OVERLAY_PANTHEON_ACCESS, "Cette maison a accès aux cinq dieux du Panthéon"},
    {TR_BUILDING_LEGION_FOOD_BONUS, "Une nourriture abondante remonte le moral" },
    {TR_BUILDING_LEGION_FOOD_STATUS, "Statut alimentaire"},
    {TR_TOOLTIP_BUTTON_ACCEPT_QUARTERMASTER, "Autoriser l'intendant à trouver de la nourriture ici"},
    {TR_WARNING_RESOURCES_NOT_AVAILABLE, "Vous ne pouvez pas obtenir le matériel nécessaire"},
    {TR_CONFIG_GP_CH_MONUMENTS_BOOST_CULTURE_RATING, "Les temples monumentaux terminés confèrent un bonus de culture de +8"},
    {TR_BUTTON_BACK_TO_MAIN_MENU, "Retour au menu principal" },
    {TR_LABEL_PAUSE_MENU, "Pause" },
    {TR_OVERLAY_LEVY, "Taxes" },
    {TR_TOOLTIP_OVERLAY_LEVY, " denarii payées en taxes par mois." }, 
    {TR_MAP_EDITOR_OPTIONS, "Scenario réglages" },

**Comment by Keriew** [comment]
Thank you, added that!
