### ISSUE TITLE
[Mac] new graphics do not work

### ISSUE THREAD

**Issue by GrandLTU** [Keriew/augustus#147]
Ceasar is extracted with `innoextract` to `~/Applications/caesar3/app` and `augustus.app` from `.dmg` is placed there.

Screenshot of roadblocks:
![Screenshot 2020-11-13 at 17 44 13](https://user-images.githubusercontent.com/6538692/99091543-b7198a00-25d8-11eb-9921-ce5e89576c81.png)

**Comment by Keriew** [comment]
Make sure that the mods folder included in the download is placed in the Caesar 3 installation folder.

**Comment by GrandLTU** [comment]
> Make sure that the mods folder included in the download is placed in the Caesar 3 installation folder.

thanks, that solves it
