### ISSUE TITLE
french translation formatting

### ISSUE THREAD

**Issue by Trokinos** [Keriew/augustus#149]
Hello, noticed some extra spacing in the french.c  that shouldn't be there if i compare to the english.c (certainly my fault), also there is a },  in the end of the translation that should probably be a } to avoid some problem. 

Really sorry for the trouble, should have checked more carefully.  Here is the updated full french.c file

edit :  github broke the formatting so i attached the updated zipped french.c file itself in the comment , sorry for inconvenience.

**Comment by Trokinos** [comment]
Hmm, for some reason github broke the formatting of my copy/paste, so here's the french.c file itself then

**Comment by Keriew** [comment]
Fixed, thank you for the help!
