### ISSUE TITLE
Game not loading with mods.

### ISSUE THREAD

**Issue by shadoww1028** [Keriew/augustus#150]
When I try to copy the mods folder over to the Caesar3 directory to get things like the roadblock to work correctly the game will not launch.  I just copy the maps and mods out of the zip file.  I'm on Arch linux (also tried it on mint 19.2 and got the same thing) with the 5.9 kernel.

Output:
INFO: Augustus version 2.0.0
INFO: Initializing SDL
INFO: SDL initialized
INFO: Loading game from working directory
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Loading game from base path /usr/bin/
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Loading game from user pref /home/shadoww/GOG Games/Ceasar3
INFO: Config key  ui_sidebar_info  1
INFO: Config key  ui_show_intro_video
INFO: Config key  ui_smooth_scrolling  1
INFO: Config key  ui_walker_waypoints
INFO: Config key  ui_show_water_structure_range  1
INFO: Config key  ui_show_construction_size  1
INFO: Config key  ui_zoom  1
INFO: Config key  ui_highlight_legions  1
INFO: Config key  ui_show_military_sidebar
INFO: Config key  ui_disable_map_drag
INFO: Config key  gameplay_change_jealous_gods
INFO: Config key  gameplay_change_global_labour
INFO: Config key  gameplay_change_retire_at_60
INFO: Config key  gameplay_change_fixed_workers
INFO: Config key  gameplay_wolves_block
INFO: Config key  gameplay_buyers_dont_distribute
INFO: Config key  gameplay_change_getting_granaries_go_offroad
INFO: Config key  gameplay_change_granaries_get_double
INFO: Config key  gameplay_change_tower_sentries_go_offroad
INFO: Config key  gameplay_change_farms_deliver_close
INFO: Config key  gameplay_change_only_deliver_to_accepting_granaries
INFO: Config key  gameplay_change_all_houses_merge
INFO: Config key  gameplay_change_random_mine_or_pit_collapses_take_money
INFO: Config key  gameplay_change_multiple_barracks
INFO: Config key  gameplay_change_warehouses_dont_accept
INFO: Config key  gameplay_change_houses_dont_expand_into_gardens
INFO: Config key  gameplay_change_monuments_boost_culture_rating
INFO: Config key  ui_language_dir
INFO: Config value  
INFO: Detected language:  English
INFO: Detected encoding:  1252
INFO: Creating screen 2560 x 1440, fullscreen, driver: x11
INFO: Creating renderer
INFO: Textures created (2560 x 1440)
INFO: Model loaded
INFO: Loading mod file  mods/aesthetics.xml
libpng warning: iCCP: known incorrect sRGB profile
free(): double free detected in tcache 2
Aborted (core dumped)

**Comment by BeWorld2018** [comment]
Here on MorphOS (bigendian), game crash and machine crash (no logs...) when loading mod (xml)... maybe endianess problem but not sur.

**Comment by crudelios** [comment]
The game should be big endian compatible.

The crash is due to a problem in libpng, I am already looking into it, hopefully I can figure out a fix!

**Comment by BeWorld2018** [comment]
Thanks you !!

**Comment by shadoww1028** [comment]
Thank you very much keep up the great work!

**Comment by pulsar68** [comment]
Hi,
Same issue on my Arch too: 5.9.8-arch1-1 x86_64 GNU/Linux (tested with AppImage, linux zip archive and my own compiled version with libpng 1.6.37-3)

**Comment by schrojf** [comment]
Tested Linux build `2.0.0.16-5888670` and still same issue on `Ubuntu 18.04` `5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

*zip*:
```
➜  augustus-2.0.0.16-5888670-linux-x86_64 ./augustus
INFO: Augustus version 2.0.0.16-5888670
INFO: Initializing SDL
INFO: SDL initialized
INFO: Loading game from working directory
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Loading game from base path /home/viliam/opt/Caesar III/augustus-2.0.0.16-5888670-linux-x86_64/
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Loading game from user pref /home/viliam/opt/Caesar III/app
INFO: Config key  ui_sidebar_info  1
INFO: Config key  ui_show_intro_video
INFO: Config key  ui_smooth_scrolling  1
INFO: Config key  ui_walker_waypoints  1
INFO: Config key  ui_show_water_structure_range  1
INFO: Config key  ui_show_construction_size  1
INFO: Config key  ui_zoom  1
INFO: Config key  ui_highlight_legions  1
INFO: Config key  ui_show_military_sidebar  1
INFO: Config key  ui_disable_map_drag
INFO: Config key  gameplay_change_jealous_gods
INFO: Config key  gameplay_change_global_labour  1
INFO: Config key  gameplay_change_retire_at_60  1
INFO: Config key  gameplay_change_fixed_workers
INFO: Config key  gameplay_wolves_block
INFO: Config key  gameplay_buyers_dont_distribute
INFO: Config key  gameplay_change_getting_granaries_go_offroad
INFO: Config key  gameplay_change_granaries_get_double  1
INFO: Config key  gameplay_change_tower_sentries_go_offroad  1
INFO: Config key  gameplay_change_farms_deliver_close
INFO: Config key  gameplay_change_only_deliver_to_accepting_granaries
INFO: Config key  gameplay_change_all_houses_merge  1
INFO: Config key  gameplay_change_random_mine_or_pit_collapses_take_money  1
INFO: Config key  gameplay_change_multiple_barracks  1
INFO: Config key  gameplay_change_warehouses_dont_accept  1
INFO: Config key  gameplay_change_houses_dont_expand_into_gardens  1
INFO: Config key  gameplay_change_monuments_boost_culture_rating  1
INFO: Config key  ui_language_dir
INFO: Config value  
INFO: Detected language:  English
INFO: Detected encoding:  1252
INFO: Creating screen 3840 x 2160, fullscreen, driver: x11
INFO: Creating renderer
INFO: Textures created (3840 x 2160)
INFO: Model loaded
INFO: Loading mod file  mods/aesthetics.xml
libpng warning: iCCP: known incorrect sRGB profile
free(): double free detected in tcache 2
[1]    8375 abort (core dumped)  ./augustus
```

*appimage*:
```
➜  augustus-2.0.0.16-5888670-linux-x86_64 ./augustus-2.0.0.16-5888670-linux.AppImage 
INFO: Augustus version 2.0.0.16-5888670
INFO: Initializing SDL
INFO: SDL initialized
INFO: Loading game from working directory
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Loading game from base path /tmp/.mount_augustkCEZVx/usr/bin/
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Loading game from user pref /home/viliam/opt/Caesar III/app
INFO: Config key  ui_sidebar_info  1
INFO: Config key  ui_show_intro_video
INFO: Config key  ui_smooth_scrolling  1
INFO: Config key  ui_walker_waypoints  1
INFO: Config key  ui_show_water_structure_range  1
INFO: Config key  ui_show_construction_size  1
INFO: Config key  ui_zoom  1
INFO: Config key  ui_highlight_legions  1
INFO: Config key  ui_show_military_sidebar  1
INFO: Config key  ui_disable_map_drag
INFO: Config key  gameplay_change_jealous_gods
INFO: Config key  gameplay_change_global_labour  1
INFO: Config key  gameplay_change_retire_at_60  1
INFO: Config key  gameplay_change_fixed_workers
INFO: Config key  gameplay_wolves_block
INFO: Config key  gameplay_buyers_dont_distribute
INFO: Config key  gameplay_change_getting_granaries_go_offroad
INFO: Config key  gameplay_change_granaries_get_double  1
INFO: Config key  gameplay_change_tower_sentries_go_offroad  1
INFO: Config key  gameplay_change_farms_deliver_close
INFO: Config key  gameplay_change_only_deliver_to_accepting_granaries
INFO: Config key  gameplay_change_all_houses_merge  1
INFO: Config key  gameplay_change_random_mine_or_pit_collapses_take_money  1
INFO: Config key  gameplay_change_multiple_barracks  1
INFO: Config key  gameplay_change_warehouses_dont_accept  1
INFO: Config key  gameplay_change_houses_dont_expand_into_gardens  1
INFO: Config key  gameplay_change_monuments_boost_culture_rating  1
INFO: Config key  ui_language_dir
INFO: Config value  
INFO: Detected language:  English
INFO: Detected encoding:  1252
INFO: Creating screen 3840 x 2160, fullscreen, driver: x11
INFO: Creating renderer
INFO: Textures created (3840 x 2160)
INFO: Model loaded
INFO: Loading mod file  mods/aesthetics.xml
libpng warning: iCCP: known incorrect sRGB profile
free(): double free detected in tcache 2
[1]    8459 abort (core dumped)  ./augustus-2.0.0.16-5888670-linux.AppImage
```

**Comment by BeWorld2018** [comment]
here i test with last fix : https://github.com/Keriew/augustus/commit/2bb7fc82d2d962c094db42ab91498474e5f6bcf5
And workinnnnnnngg ! thanks

**Comment by BeWorld2018** [comment]
Missing one convert for bigendian in png_read() function

this : png_set_bgr(png_ptr); corrupt color order
and missing : png_set_swap_alpha(data.png_ptr);

https://github.com/Keriew/augustus/blob/2bb7fc82d2d962c094db42ab91498474e5f6bcf5/src/core/png_read.c#L93

**Comment by crudelios** [comment]
Can you show me a screenshot please?

**Comment by BeWorld2018** [comment]
Here unless my patch 

![image](https://user-images.githubusercontent.com/36823759/99257402-4318f500-2817-11eb-9be1-f86ce52f643f.png)

**Comment by BeWorld2018** [comment]
Yes, maybe need to test on linux PPC or MacOS PPC to confirm that.
But in my case yes :-)

**Comment by crudelios** [comment]
How about saving screenshots? (Press `F12` then look in yout c3 folder)

**Comment by BeWorld2018** [comment]
F12 = crash.... arff...

**Comment by crudelios** [comment]
Can you test in Julius too, please? You may be the first person actually using a big endian machine...

**Comment by BeWorld2018** [comment]
Ok :-) Julius same crash

**Comment by crudelios** [comment]
I'll get around to fixing the mod loading bug here (so this can then be closed) and I'll have a look at the screenshot crash at the new issue I created for Julius.

If you don't mind, can you post your crashing Julius log on the new issue I opened?

**Comment by BeWorld2018** [comment]
ok i building with internal lib, it's ok for me with Screenshot crash.
But i need png_set_swap_alpha and not png_set_bgr. 
Maybe you can use something like that #if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__

**Comment by crudelios** [comment]
I have changed the png reading code to (hopefully) need none of those shinenigans. I've uploaded the code to the release branch, can you please test it?

**Comment by BeWorld2018** [comment]
yes i test it, working, no more need swap_alpha !! great thanks

**Comment by crudelios** [comment]
Thanks for all the help. Finally closing this.
