### ISSUE TITLE
some improvement for the french translation

### ISSUE THREAD

**Issue by Trokinos** [Keriew/augustus#151]
Thanks to the new build i could give a try to the current french translation to check if i did some mistake or not, building the new content and reading menu and descriptions (Augustus and Julius are a really amazing piece of work) .  
This allowed me to see a few problems, most of them due to french language being wordy and long where the english one isnt, truncating a few texts unfortunately, as shown in those few screenshots.  
https://imgur.com/a/nUGc8ob  
  
Additionally, i noticed the horrible translation i did of the ancient texts from Ovid, Homer etc... on each greater temple descriptions, i should really have re-read myself a few times , so i reworked them so the meaning is actually true to the real text.  
Also due to french longer words and expressions, there was some truncated text problem there too.  
  
I think i fixed all those problems now, here is the updated french.c , i hope it's much better. 
[french.zip](https://github.com/Keriew/augustus/files/5548091/french.zip)

**Comment by Keriew** [comment]
Thanks for the help, implemented in 548d882

**Comment by Trokinos** [comment]
Thank you, i just tested the new unstable build and the truncated problems are all fixed.
