### ISSUE TITLE
Forts set to Empire Service do not consume food when home

### ISSUE THREAD

**Issue by rahmanhamed** [Keriew/augustus#157]
A fort may not consume food when it's set as Empire service and it's actually sent to fight when Emperor requests army. But when it's home it should still consume food whether it's Empire Service or not. Now it does not consume food when set as Empire Service but soldiers are home.

**Comment by theradeonxt** [comment]
@rahmanhamed 
How can you check that it consumes food or not?

I tried to do this on a map of 6 legions, activating the Empire service one by one, expecting I would get more food available for more months in the Supply Post info box.
But it stays the same...

**Comment by Keriew** [comment]
Fixed in 411461e
