### ISSUE TITLE
mods directory not recognized by augustus Linux AppImage

### ISSUE THREAD

**Issue by dbart** [Keriew/augustus#158]
On startup Augustus complains that the mods folder can't be found even though there is one present in the Caesar III game directory. The folder is currently empty, as I have not loaded any mods. I created the dir to get rid of the annoying message, but augustus doesn't appear to recognize its existence.

[Screenshot](https://imgur.com/a/x9YY0bw)

Steps to reproduce: Launch augustus AppImage.

**Comment by crudelios** [comment]
You must place the mods folder provided with the zip (so the game detects the files), otherwise the game will complain the folder can't be found.

**Comment by dbart** [comment]
If that is the case, then the error message needs to be rewritten.
