### ISSUE TITLE
Intro movies corrupted my hard drive

### ISSUE THREAD

**Issue by aslak01** [Keriew/augustus#159]
2013 iMac, macOS Mojave: Running the game with movies enabled corrupted my hard drive (APFS). Most recent version of the game as of last week (unstable release).

I opened it by mistake, working on a project, the intro movies I had enabled last time I played started playing, with major buggy artefacts. This put my computer in kernel panic, with random short lines of white across the screen everywhere, which persisted reboots, NVRAM clear, and SMC reset, while the computer failed to boot. In fact I was convinced it had somehow corrupted my logic board until just now, when I booted it from a USB installer and the random lines disappeared.

**Comment by crudelios** [comment]
It is highly unlikely that the intro movies were the direct cause of your problem.

The intro movie playback only reads (it does not write) to the hard drive. It does so by software (not directly using the graphics card), so if some buggy implementation was the problem you should see at most a game crash, but not white lines or kernel panics.

My take is something failed on your computer that manifested itself when you opened the sdl window. Possibly it is a graphics driver issue, or even a problem with the graphics card itself...

**Comment by aslak01** [comment]
Yeah I guess so… I thought it had resolved itself as I was writing that, as the OS installer didn't have any graphical bugs, but they returned once it finished and it never succeeded in booting to the fresh install, so definitely some deeper HW issue. RIP Old Faithful.

**Comment by crudelios** [comment]
Just out of curiosity, what's your graphics card? The 8600M series were notoriously known to stop working after a few months/years due to a production issue.

**Comment by aslak01** [comment]
One of Nvidia GT 755M, GTX 775M, GTX 780M. I honestly can't remember which, but I did invest in some upgrades to the base model, but not too much. Maybe 2nd one.

**Comment by crudelios** [comment]
I hope you can get your problem fixed. Hardware issues are always tricky.

Anyway, since really doesn't seem to be related to Augustus, I'm closing the issue.
