### ISSUE TITLE
Including Mothballed Buildings on Risks/Problems Overlay

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#160]
Presently, there's no way of detecting mothballed buildings, except by right-clicking on each of them.

It might be a good idea to detect them on the Risks/Problems Overlay with a small improuvement: mothballed, workers and raw materials problems, in that order (according to its degree of urgency), with a visual sign.

![Pottery_Mothball](https://user-images.githubusercontent.com/64329357/100370332-02329480-2ffe-11eb-972f-08e11a9dabcc.jpg)   ![Pottery_Workers](https://user-images.githubusercontent.com/64329357/100370373-11194700-2ffe-11eb-8d86-f68858db8306.jpg)   ![Pottery_Raw](https://user-images.githubusercontent.com/64329357/100385700-526c1f80-301b-11eb-8486-30146c73a58c.jpg)

**Comment by Areldir** [comment]
Can this been moved to the Discussions tab too? If so, I'll close the issue.

**Comment by arkimedes1967** [comment]
> Can this be moved to the Discussions tab too? If so, I'll close the issue.

Moved, you may close this thread.
