### ISSUE TITLE
Too pixelated backround images when playing at wide aspect ratio

### ISSUE THREAD

**Issue by theradeonxt** [Keriew/augustus#161]
Hello,

I noticed with the latest Augustus releases, the background images in menu, advisors etc get very pixelated.
I'm playing at 2560 x 1080 resolution, which has a 21:9 aspect ratio, on Windows.

It looks that the image is **not actually stretched**, but in fact **zoomed in** to try to fit any aspect ratio.
This is visible when playing in Windowed mode and resizing it left/right only.

Here the picture was taken in fullscreen mode.
You can see that some parts of the original image are cut out.

![Capture](https://user-images.githubusercontent.com/13402104/100443196-e7215c80-30b1-11eb-8334-920f50664f7c.JPG)

**Comment by crudelios** [comment]
Yes, this is by design as we did not want black borders or strange horizontal or vertical-only stretching.

**Comment by theradeonxt** [comment]
Oh, I see, well in fact no black borders is better now.
So this just comes down to the fact that the game art, images were intented for 4:3 aspect ratio and resolutions.
And also not too big resolutions like we have today.
Thanks, I will close this.
