### ISSUE TITLE
Grand Temple to Neptune water coverage not centered

### ISSUE THREAD

**Issue by theradeonxt** [Keriew/augustus#163]
**Found with:**
![Capture3](https://user-images.githubusercontent.com/13402104/100650031-fcb1b300-334b-11eb-8ab7-fd92992e486e.JPG)

**Steps to reproduce:**
1. Build GTN
2. Bestow Epithet which gives water coverage around it
3. **Bug:** The area around is biased in some directions.

See picture (the 4 corner fountains mark the maximum water range):
![Capture2](https://user-images.githubusercontent.com/13402104/100649615-5cf42500-334b-11eb-9eb4-3b8d325eaddd.JPG)

**Comment by Keriew** [comment]
Good catch, thanks for the report!

Fixed in 3eaf416
