### ISSUE TITLE
Rename files which are identcal with julius

### ISSUE THREAD

**Issue by TheChymera** [Keriew/augustus#174]
I am trying to package agustus for Gentoo Linux, but a number of files conflict with julius.

This is the tail of my [build.log](https://github.com/Keriew/augustus/files/5708577/build.log).

I have tried to locate the files in the repo, to submit a fix as a PR, but I could not. Any idea how I could best fix the name of the files so that this issue can be persistently solved?

**Comment by crudelios** [comment]
It seems Gentoo has an outdated build of Augustus (1.4.1A).

The latest version of Augustus (2.0.1) seems to have generally fixed those collisions, maybe save for metainfo.xml.

@Keriew Can you confirm this, please?

**Comment by Keriew** [comment]
They should have all been fixed in 2.0.0 and later (they were in fact fixed because of this issue).

**Comment by TheChymera** [comment]
Yes, I can confirm. All fixed in newer releases. Thank you :)
