### ISSUE TITLE
When enable zoom, korean font is became transparent in game

### ISSUE THREAD

**Issue by yg3988** [Keriew/augustus#179]
> version 2.0.1
> os:  windows 10

* Construction Menu
![image](https://user-images.githubusercontent.com/31890257/102872742-7b999780-4483-11eb-8328-88bcb65c8c8a.png)

In addition to the construction menu, transparent Korean font bugs occur in many places. 
(e.g. File, Options, Help, Advisors, Map, and Pause)

* File
![augustus_file](https://user-images.githubusercontent.com/31890257/102874631-0d0a0900-4486-11eb-99ea-b0bdbfd3b0ce.png)

* Option
![augustus_option](https://user-images.githubusercontent.com/31890257/102874665-18f5cb00-4486-11eb-9a2d-39f73bb7bbcc.png)

* Help
![augustus_help](https://user-images.githubusercontent.com/31890257/102874693-26ab5080-4486-11eb-86d3-13dadde0b74b.png)

* Advisor
![augustus_advisor](https://user-images.githubusercontent.com/31890257/102874753-3b87e400-4486-11eb-9ac6-82dc75b40086.png)

* Overlays
![augustus_overlays](https://user-images.githubusercontent.com/31890257/102874890-68d49200-4486-11eb-9ec5-2dd44a337628.png)

* Pause
![augustus_pause](https://user-images.githubusercontent.com/31890257/102875556-4bec8e80-4487-11eb-996a-c614bea26880.png)

**Comment by crudelios** [comment]
Thanks for the report.

I'll fix it ASAP
