### ISSUE TITLE
Request: More information on newly added content in game

### ISSUE THREAD

**Issue by webfischi** [Keriew/augustus#182]
I just take roadblocks as an example here, as a new player I don't know what all those images of the people mean, also the String used for the buttons are not inside german.c 
I guess in the english version it shows "accept" and "not accept" from a different part of the game, which may have been translated correctly in that part, but can't be used for roadblocks. For roadblocks the german translation would need a translation for "allow" and not for "accept"

**Comment by Keriew** [comment]
Yes, I agree that the roadblocks control could use more explanations, I'll add tooltips to them. 

What other features do you think would need more in-game explanation?

Good point on the localization issues. Roadblocks use the same strings as granaries and warehouses which may be a problem depending on their localization. That probably won't get updated until the next big release.

**Comment by Keriew** [comment]
Tooltips added with c0cc5a7.

**Comment by webfischi** [comment]
Is it possible to add tooltips to everything in the game?

**Comment by Keriew** [comment]
No technical limit on that. What do you think need tooltips?

**Comment by crudelios** [comment]
@webfischi Is there anything else you feel could be "tooltiped"?

If not I'll be closing this in a few days.

**Comment by webfischi** [comment]
Atm there is nothing I could complain about. I guess there will be some missing on the new and upcomming stuff I haven't compiled yet (like the new Import/Export behaviour), but now that we have a discussions, I don't think we need this issue anymore.

But I somehow have the feeling that the new Import/Export behaviour needs a tooltip, explaining the changes made. Also adding all the new stuff into the in game help menu would be great.

**Comment by crudelios** [comment]
I don't think the new stick behavior can be explained in a tooltip as it's a new game mechanic.

Regarding adding new info to the help button, that would be, well, helpful.  If anyone wants to go ahead and give it a go (at least creating the texts so we can add them), please do so.

However since this is more of a contribution effort than an issue (like the translations), if there's nothing else I'll close this.

**Comment by webfischi** [comment]
Ok, I'll open a new discussion
