### ISSUE TITLE
Issues regarding Korean patch

### ISSUE THREAD

**Issue by sickchicken** [Keriew/augustus#183]
I checked Korean language pack today, and I found some issues.

1.I saw some texts from the mod were missing(not translated). I think I can help on this matter if you give me original texts from your locale, so I can check if there's any Korean text are missing.
Let me know if you need translator.

2.I find font for Korean text very hard to read. Actually, I can safely say it hurts my eye. Let me suggest some free fonts with better visibility.

I need to know if I can use your tools so I can actually try some fonts by myself and check it in high resolution, and edit those missing texts. I have zero knowledge in programming though...

**Comment by crudelios** [comment]
There was an issue with the korean font with zoom enabled. Does it work better with zoom disabled?

**Comment by webfischi** [comment]
This is an open source project, just create a pull request. Just edit korean.c stored in /src/translation to do that, GitHub will say that you can't edit and if you want to fork the project and create a pull request. The original english text is written in the english.c file.

To test the translation in Windows you have to build it with Visual Studio. With CMake and MinGW I got an error at 99% "implicit declaration of function 'rand_s' ; did you mean 'rand'? [-Werror-implicit-function-declaration]" Even building in Linux worked flawlessly, there seems to be an issue somewhere.

**Comment by bvschaik** [comment]
Some info on the font:
The Korean "font" is stored in the "korean.555" file as black/white images. It's not possible to make them "HD". It's also not possible to use TTF files or other real fonts. The images are these, if you can update them to increase legibility, that'd be great. Keep in mind they still need to be black/white.
Small:
![korean-small](https://user-images.githubusercontent.com/104874/103132775-a57ed400-46a6-11eb-8ac6-72828159bbec.png)
Medium:
![korean-medium](https://user-images.githubusercontent.com/104874/103132780-a9aaf180-46a6-11eb-919f-21d50987aa1e.png)
Large:
![korean-large](https://user-images.githubusercontent.com/104874/103132782-ad3e7880-46a6-11eb-8a91-76f8d7e05ad8.png)

**Comment by sickchicken** [comment]
Thanks. Wow, that's not good. Seriously, I can safely say Korean font is not viable at all. But I'm not sure how I should put TTF files into this, since Hangul is very complicated character in this matter. Oh, I pity those poor Korean graphic designers. I'll look into it.

**Comment by sickchicken** [comment]
Large:
[
![large](https://user-images.githubusercontent.com/74414833/103147234-c6beed80-4796-11eb-8bc6-9ec94f3ebdf8.png)
Medium:
![medium](https://user-images.githubusercontent.com/74414833/103147236-c7f01a80-4796-11eb-8315-0215249e9a95.png)
Small:
![small_bold](https://user-images.githubusercontent.com/74414833/103147237-c888b100-4796-11eb-9c1a-60ed9b6b2d31.png)
![small_light](https://user-images.githubusercontent.com/74414833/103147238-c888b100-4796-11eb-831d-00fc9f3466d0.png)

See if those fonts are working. There's two version for small fonts, for I'm not sure about its visibility in game. I need to test it. There are bold version and medium('text') version of it(I tried bold for smaller text to enhance its readability).
](url)

**Comment by crudelios** [comment]
Ping @bvschaik

**Comment by bvschaik** [comment]
I'm going to look at it next week. Note that the game also makes the letters sort of semi-bold already, so this might result in too "fat" letters.

**Comment by sickchicken** [comment]
We need exactly that fat letters for small texts, since Korean texts with light font(original) are not readable at all in Help column. It has some sort of white shadow in background, so we do need Bold fonts. English fonts are thick enough, but Korean font is way too light.
But I'm not sure if large and medium texts will be ok if the game use some Bold filter on it. I have to see actual high res screenshot or check by myself in game.

**Comment by bvschaik** [comment]
@sickchicken I converted your images, check the new version here: [korean_new_fonts.zip](https://github.com/Keriew/augustus/files/5746396/korean_new_fonts.zip)
To try it in game, just copy the korean.555 file to your Caesar 3 installation folder.

**Comment by sickchicken** [comment]
I don't know what is wrong with these texts, but all those texts went transparent. 
Perhaps because I saved PNG in 'transparent' mode? 

I think readablity itself is much better, but I must try it again with fixed version. wait up
[
![sc](https://user-images.githubusercontent.com/74414833/103211962-f0217a00-494c-11eb-86be-661dbb7e476e.jpg)
](url)

**Comment by sickchicken** [comment]
Non-transparent images for fonts

![large](https://user-images.githubusercontent.com/74414833/103212221-9a010680-494d-11eb-8285-cab1bcf7c3cf.png)
Large

![medium](https://user-images.githubusercontent.com/74414833/103212223-9b323380-494d-11eb-856c-a8b0b2926973.png)
Medium

![small_bold](https://user-images.githubusercontent.com/74414833/103212224-9b323380-494d-11eb-85c8-31439ae74d5b.png)
Small - Bold

![small_light](https://user-images.githubusercontent.com/74414833/103212225-9bcaca00-494d-11eb-87e5-7219a4d13cdd.png)
Small - Light

**Comment by sickchicken** [comment]
I'm not sure what causes this problem, but fonts are all transparent in my game, old and new. This can cause some readability issue too. I checked new version, but still, smaller fonts are problematic. I will try something else.

**Comment by bvschaik** [comment]
What do you mean with "transparent"? All letters are drawn with a shadow behind them to make them stand out from the background, if that's what you mean. This is how the new font looks in my game:
![city 2020-12-28 13 11 42](https://user-images.githubusercontent.com/104874/103213676-aca81b00-490e-11eb-82dd-1a236a82abb3.png)

**Comment by sickchicken** [comment]
![sc](https://user-images.githubusercontent.com/74414833/103213776-1269c680-4952-11eb-9b3d-23c35b4ac090.jpg)
See that blue color beyond texts above? that's what I meant by 'transparent'. (This is Screenshot from older version)

These are my new version of Korean font, because San-serif font still had few issues. I saw Eng version all had Serif fonts, and I thought Serif fonts could do some good. As I'm looking into screen, I thought Serif fonts will work better in retro games.

![large](https://user-images.githubusercontent.com/74414833/103213825-2f9e9500-4952-11eb-9bfd-595440af5dff.png)
Large

![medium](https://user-images.githubusercontent.com/74414833/103213829-30372b80-4952-11eb-8c8e-7bf3b941b823.png)
Medium

![small_bold](https://user-images.githubusercontent.com/74414833/103213830-30cfc200-4952-11eb-83eb-96ccbd7d8f41.png)
Small(didn't make light one for this)

**Comment by bvschaik** [comment]
Please disable zoom in the Options, that should fix the transparency issue for now.

New version with your latest images: [korean_new_fonts_2.zip](https://github.com/Keriew/augustus/files/5747277/korean_new_fonts_2.zip)

**Comment by sickchicken** [comment]
Wow, you do real Blitzkrieg, you know.
I think this fixed readability issue just fine. Not good as English version, but I'm sure this is as best as Korean Caesar 3 can do.
I'm working on ENG-KOR translation now, and it's about 90% done. I'm dead tired from work, so let me finish that tomorrow. And I still have no idea how github works.


![103163999-e9a9da00-4848-11eb-9d3e-25896be5bb61](https://user-images.githubusercontent.com/74414833/103214660-62498d00-4954-11eb-8a37-462f790b25d2.png)

Also, is there anything we can do for this? Korean version says "자금(Fund)", not "데나리(Denarii)". It's because the space allows only 2 characters of Hangul. If we put 데나리, string will come out of button. 
Is there any way we can move the 'cost' space left, so we can put 데나리 instead of 자금 in there? 
"Fund" instead of Denarii! It just drives me crazy. (Of course, if we do this, we must find and fix all strings from KR translation...)

**Comment by sickchicken** [comment]
Updated Korean traslation.

**Comment by yg3988** [comment]
Transparency issue fixed by @crudelios in #179

**Comment by yg3988** [comment]
> Please disable zoom in the Options, that should fix the transparency issue for now.

transparency issue fixed by @crudelios in #179

**Comment by crudelios** [comment]
Since this has now been fixed in Julius, I'm closing this one here. The pending translation is in #192.
