### ISSUE TITLE
Feature Request: Import defaults to "All"

### ISSUE THREAD

**Issue by jayhova** [Keriew/augustus#186]
The 1.4.1.0 version defaults to 0 on imports. This breaks compatibility with classic. If you load a CIII .sav gave imports stop. There is also no easy way to make imports unlimited. You have to ramp the import number up until it is higher than the combined exports of your trade partners. The 0 is essentially the same as turning trading off. Zero works as it should for exports as over 0 is the default in classic.

**Comment by crudelios** [comment]
I agree with this, 0 should mean "No Limit" (if fact we could even replace 0 with that string in the game).

If you don't want to have inports, disable them.

**Comment by jayhova** [comment]
You could always use '∞' if you wanted to keep the character count down but 'All' is only 3
