### ISSUE TITLE
Where should the mods directory be installed for augustus to find it?

### ISSUE THREAD

**Issue by TheChymera** [Keriew/augustus#188]
As it currently stands I was only able to get the additional mods to work by cloning the repository and copying the contents of the `mods` dir to `.cache/julius/app/mods/`.

Is there any way to install this at the system-wide level (perhaps in `/usr/share/augustus`, as seems reasonable per the FHS) so that augustus can automatically find them? This has two rationales:

1. These files seem to not require modification by the user, and therefore it would make sense for them to be available to all users and not require write access.
2. The Gentoo Linux distribution (for which I am currently trying to package it), prefers to not install files into the user's home, as this should be left to the application or the user.

**Comment by crudelios** [comment]
This is actually something I want to address when I port Augustus to Android.

**Comment by TheChymera** [comment]
@crudelios Android, oh my :) Is there anything else I could do in the mean time? As it stands, having to copy these files manually complicates the installation quite a bit, what with already having to tell users to get the proprietary files and put them in the appropriate directory.

**Comment by crudelios** [comment]
@TheChymera Thanks for your interest. I've been thinking about this lately. The way Augustus mod handling is designed works fine for Windows but is cumbersome for every other system.

However, Linux in particular has many directories where a game's assets can be fitted, like `/share`, `/usr/share`, etc. If possible I'd like to hardcode a single path for every single distro (with the user only having to pick the C3 directory), but I don't know if that's even feasible.

**Comment by TheChymera** [comment]
@crudelios Linux actually has very well specified directories so that you can unambiguously decide which is best (check out the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) as a general resource). This is precisely the design principle it follows:

> If possible I'd like to hardcode a single path for every single distro

`/share/` in particular is not recommended. The best choice would be `/usr/share/augustus-game`.

**Comment by crudelios** [comment]
How about `/usr/local/share`? From that artie it seems to be the most suitable directory for `augustus-game`

**Comment by TheChymera** [comment]
@crudelios not really, it's not “local” in the sense that it's distributed and not specific to this system. Just as a sanity check I looked to see whether any packages use it on any of my systems, and they don't. They keep their things in `/usr/share/some-variation-on-the-package-name`. So I think that's best :)

**Comment by chewi** [comment]
There's hardcoding it and there's hardcoding it. If you absolutely have to pick one path for everyone, use `/usr/share/augustus` or whatever but please don't do that. There's no one-size-fits-all solution here. Gentoo supports installing within an arbitrary prefix within another OS. I've never used it but I gather NixOS uses all sorts of weird and wonderful paths. Finally, for those installing manually, such software is supposed to go under `/usr/local`.

You're using CMake so do distros a favour and employ [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) to install the files to `${DATADIR}/augustus` and use the other variables where applicable too. Then use `configure_file` or `add_compile_definitions` to pass this path into your code, where it will be hardcoded from a user perspective.

**Comment by crudelios** [comment]
@chewi Thanks for your input. I don't know much about directory managing on Linux, so your idea seems to be the most flexible one so far.

I also want to figure out the best way to bundle the assets in macOS, so if anyone has any suggestion please let me know. Ideally I want to fix this issue for every platform at once.

**Comment by chewi** [comment]
I haven't used macOS in years, I'm afraid. I couldn't find much concrete information about how GNUInstallDirs behaves on other platforms but one comment indicated that it installs under `C:\Program Files` on Windows, which is probably what you want. I suggest you just try it and see.

**Comment by crudelios** [comment]
@TheChymera @chewi can you please check #221? Specifically the dirs I'm adding to the new assets' search path.

**Comment by TheChymera** [comment]
@crudelios perfect, this works just as expected and out-of-the box <3
