### ISSUE TITLE
Warehouse man with empty-all order appears and disappears over and over

### ISSUE THREAD

**Issue by LyonHe** [Keriew/augustus#19]
Currently, if there's no available warehouses for an empty all order, the warehouse man will keep appearing and disappearing. My suggestion is either we don't spawn the warehouse man or we spawn and let it wait until there's available spaces.
This is something that keeps bugging me.

**Comment by Keriew** [comment]
True, that's annoying. There's a bunch of cases with granaries/warehouses involved where they don't check if the target exists or is reachable before spawning the cart pusher, it'd be good to get through them and make sure they don't happen. I'll get to it at some point.

**Comment by Keriew** [comment]
Fixed with 6d09ed4
