### ISSUE TITLE
french translation update for tooltips and re-arranging

### ISSUE THREAD

**Issue by Trokinos** [Keriew/augustus#190]
Hello, 
I updated the french.c file to add the french translation of the new tooltips.
I also re-arranged the order of the translation to match line by line the english.c one (to make it easier to edit the french translation later).   
Here is the updated french.c file (it's in the frenchup.zip file), thanks for your work.

[frenchup.zip](https://github.com/Keriew/augustus/files/5744475/frenchup.zip)

**Comment by crudelios** [comment]
Thanks for this, I'll have a look.

**Comment by crudelios** [comment]
Could you also translate the following, please?

```
    {TR_ADVISOR_TRADE_MAX, "Max"},
    {TR_ADVISOR_TRADE_NO_LIMIT, "No limit"},
    {TR_ADVISOR_TRADE_IMPORTABLE, "Importable"},
    {TR_ADVISOR_TRADE_EXPORTABLE, "Exportable"},
```

**Comment by Trokinos** [comment]
Hello, here's the french version , it nearly use the same words as in english there :

    {TR_ADVISOR_TRADE_MAX, "Max"},
    {TR_ADVISOR_TRADE_NO_LIMIT, "Sans limite"},
    {TR_ADVISOR_TRADE_IMPORTABLE, "Importable"},
    {TR_ADVISOR_TRADE_EXPORTABLE, "Exportable"},

**Comment by crudelios** [comment]
Thank you, changes added!
