### ISSUE TITLE
High-res example screenshot

### ISSUE THREAD

**Issue by TheChymera** [Keriew/augustus#191]
Not a UI improvement. I've just had a lot of fun building a nice city with augustus — and if you'd find a high-res screenshot of a full density and high-prosperity city useful to showcase your software, I'd be happy to share this with you: https://ppb.chymera.eu/fefa2d.png

Also, here's the savefile for reference: https://ppb.chymera.eu/1f1d09.svx

**Comment by Ivan-Cristian** [comment]
oh my god, that is amazing! literally the most gorgeous caesar 3 city i've ever seen!

**Comment by crudelios** [comment]
Thank you, the city looks really good.

@Keriew maybe we could replace the readme image with a low-res version of this one? (We could keep the link to the original high-res image)

**Comment by Keriew** [comment]
Looks great! Thanks, we'll use it for the readme.

**Comment by crudelios** [comment]
@TheChymera Can we direct the image link to the direct link you provided (https://ppb.chymera.eu/fefa2d.png)? Or do you think it may waste too much bandwidth?

**Comment by Areldir** [comment]
If possible, could we clone this thread to the Discussions tab and then close the issue?
