### ISSUE TITLE
New Buildings/Resources/etc

### ISSUE THREAD

**Issue by XLightningStormL** [Keriew/augustus#196]
I didn't want to just stick this in Issues (as it's more suggestions/ideas than actual issues) but no discussions tab.

I'll get to my point, I'd like to see the integration of more building/resource types, at least optionally, maybe more houses, or probably better, more requirements for houses.

Stuff like Sand, Glass, Utensils, Sheep and Wool (though sheep would be a meat source as well, maybe for Greek-style levels), Lamps - Really would only be useful is housing requirements were expanded, as well as for exporting (though I'd imagine that'd require having to make new maps, and such) Glass would probably be great for Desert Levels, though it'd probably end up being slow and tedious (historically Romans only made enough glass that even the modern day skyscraper in a major city has more glass) but pretty decent market wise.

As for buildings, maybe like an Odium, a sort of cheaper/filler type of Entertainment with a "Musician's Guild" and Basilicas that'd function like Pharaoh's Courthouses, with Magistrates that'd help lower crime (and prevent pesky thieves more, since Prefects are well, you know) like Caesar II and Pharaoh, could have Shrines back as a cheap, low maint way to keep the gods happy and from wrecking your stuff.

Yeah, my ideas were taken from the other games in the series, which is probably where new inclusions should start.

As well anyone else could use this for the same purpose as well, suggest your ideas, and keep issues for issues.

**Comment by Areldir** [comment]
Never fear, all these ideas are included on our roadmap. Resources are going to take a bit of time, as they require a substantial engine rewrite, but the new building ideas are either currently WIP or on the roadmap for a future update.
