### ISSUE TITLE
Some Chinese texts get poorly rendered

### ISSUE THREAD

**Issue by hathlife** [Keriew/augustus#199]
On augustus some Chinese UI text get poorly rendered,  lead to bad readability.
![image](https://user-images.githubusercontent.com/19867269/104457292-cfac1d80-55e4-11eb-94bb-2eb03ada4bee.png)
![image](https://user-images.githubusercontent.com/19867269/104457305-d470d180-55e4-11eb-93b6-1d168adb5285.png)
Julius has no such issue:
![image](https://user-images.githubusercontent.com/19867269/104457871-8dcfa700-55e5-11eb-9fdb-7fa09fae85c2.png)
Is it possible to introduce something like freetype to eventually get rid of issues like this?
Update: It seems that the color of text wrongly get a 0% alpha value or sth else.
![image](https://user-images.githubusercontent.com/19867269/104458431-56adc580-55e6-11eb-8647-852558094c41.png)

**Comment by crudelios** [comment]
This has been fixed on the `release` branch 👍
