### ISSUE TITLE
Make amounts sticky

### ISSUE THREAD

**Issue by jayhova** [Keriew/augustus#203]
I've noticed with granaries (and probably with other things) the amounts always change back to the default number whenever you change the method. That is to say, if I set the amounts so the three items I have in my province are at a limit of 12 and then I change the method from accepting to getting the amount changes back to 24. It would be nice if the amount would remain where you set it and not reset.

**Comment by Keriew** [comment]
That's a good idea. I'll work on adding it soon.

**Comment by Keriew** [comment]
Added!
