### ISSUE TITLE
Hello, dear production team, I have a few questions to ask

### ISSUE THREAD

**Issue by USAsamurai** [Keriew/augustus#204]
在这里问你的问题。1  Can the original 1 × 1 building area be enlarged? Like the police station!？ 
2   Can the function of fire fighting be separated from the police station? Add a new building to deal with the fire brigade?
3  The original project institute and police station have no sound effect when they click. How to add a new sound effect?
4 Can I join your production team? I am good at art design, and participated in the art design of the end of the Red Alert 2

**Comment by Legionary2** [comment]
Hi there , we would love you to contribute to art design - if you are interested please join the GamerZach discord. When you join, please send me a private message at Legionary2. We have our own discord server where we discussion and implement code and art decisions before final releases

**Comment by USAsamurai** [comment]
当然荣幸加入

**Comment by USAsamurai** [comment]
Of course, it's my honor to join!

**Comment by Legionary2** [comment]
https://discord.com/channels/136544899339124736/671669495559094272

**Comment by Areldir** [comment]
As Legionary2 has sufficiently answered the most pressing issue here, and the suggestions can be reiterated in the Discussions tab, I'm closing this issue.
