### ISSUE TITLE
Imports & Exports Shortcut

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#206]
Please exclude this thread.

**Comment by crudelios** [comment]
I actually don't agree with this. That window is specific to the resource, not the city.

What happens when you were already importing a resource then the window only allows you to export it?

**Comment by arkimedes1967** [comment]
When you want to buy or sell a resource, you must open a trade route with the city. So, the first approach is with the city, and the first set is made here. Imports using the upper set of resources, and exports using the lower set of resources.

If you want to change the product afterwards (import instead of export), the Trader Adviser is be best place where are they are all align.

At least this is my approach to the game, but i don't know if it was the creator intent or not.

**Comment by crudelios** [comment]
The creator intent was to only manage trading from the advisors screen.

Again, there must be a way to know you're already importing a resource you want to export. Changing this screen will prevent that.

**Comment by arkimedes1967** [comment]
If you look carefully, you'll see that the panel box opens with the last option used. Maybe it could open **first** the right sequence - **imports** if user chooses to buy a resources using the upper line, and **exports** if user chooses to sell using the lower line of resources.

Either way, player would have access to both but on the right sequence to avoid mistakes, like the one i described on my first thread.

**Comment by crudelios** [comment]
Again, that window shows the current status of the item's trade. I still think it is a bad idea to change that without any warning.

**Comment by arkimedes1967** [comment]
Since i'm unable to show you the benefits of my proposal, you may close this thread.

**Comment by crudelios** [comment]
I'm having a look at Pharaoh's way of handling things (separate import and expirt buttons, allowing both at the same time) to see if it's easy enoghbto implement. That would take care of this issue.

**Comment by crudelios** [comment]
After looking at the code, it's certainly possible to allow both importing and exporting at the same time.

As such, I'll be implementing Pharaoh's way of doing things, which allows for separately setting imports and exports from the same window.

That would take care of this issue while also implementing a new mechanic that will be useful going forward.

**Comment by crudelios** [comment]
> Please exclude this thread.

I'm not excluding this, this is actually a nice change. It's only a matter of time for me to implement it.

**Comment by Legionary2** [comment]
> After looking at the code, it's certainly possible to allow both importing and exporting at the same time.
> 
> As such, I'll be implementing Pharaoh's way of doing things, which allows for separately setting imports and exports from the same window.
> 
> That would take care of this issue while also implementing a new mechanic that will be useful going forward.

I concur, I was going to propose this at some point as I know additional resource / empire changes will potentially warrant these types of situations

**Comment by crudelios** [comment]
Fixed by https://github.com/Keriew/augustus/commit/de394104393be0ea147f034f46a94e73ae069323
