### ISSUE TITLE
Granaries & Warehouses Access Mechanics

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#207]
If you Devs in the near future are thinking about revamping the Trade & Distribution issues, may you consider to change the actual mechanics as the images below show? I think they are less conspicuous compared to the current ones.

Both images should behave as an 'On/Off' buttons, when pressed.

![Granary Acess](https://user-images.githubusercontent.com/64329357/105566038-db54be00-5d21-11eb-8e17-9c9f73561e1d.jpg)

![Warehouse Acess](https://user-images.githubusercontent.com/64329357/105566048-edcef780-5d21-11eb-8920-857b417823fa.jpg)

**Comment by crudelios** [comment]
While I think the current design can be improved, I also feel your idea is not in line with the rest lf the game's general design.

Maybe making the images/checkboxes more centered and with better padding will do the trick. Or maybe even something like it's being planned on #201.

**Comment by arkimedes1967** [comment]
I would reserve the checkboxes to mothballing the building and refusing goods. Images/checkboxes uses double space and is more conspicuous then the on/off image. You might think it over as a design evolution.

The accepting/not accepting options #201 is ok for 1x1 imagens like goods or a city name. For rectangular images on this case, requires more space, which you don't have much.

**Comment by arkimedes1967** [comment]
I like best the big people figures then the current ones, sincerely.

![Distribution Access](https://user-images.githubusercontent.com/64329357/105612960-62a04100-5db7-11eb-941b-ef2a2c887d7e.jpg)

**Comment by Areldir** [comment]
Has this been moved to the Discussions tab too? If so, I'll close the issue.

**Comment by arkimedes1967** [comment]
> Cas this be moved to the Discussions tab too? If so, I'll close the issue.

Moved, you may closed this thread.
