### ISSUE TITLE
Food Distribution Chain

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#208]
Honestly, if there isn't a better idea, the schema below might work beautifully.

Conditions of **‘Pile Up’** status granaries:
1)	Accept food if available space;
2)	Don’t send food to other granaries.

Conditions of **‘Accepting Goods’** status granaries:
1)	If >= 8 food, then send it to next ‘Pile Up’ available granary;
2)	If passes a near available granary:
a.	> 6 tiles distant from point of origin;
b.	accepting goods, then drop it.

Conditions of **‘Getting Goods’** granaries:
1)	Get goods from the next ‘Pile Up’ granary

![Food Distribution Chain](https://user-images.githubusercontent.com/64329357/105568807-24157280-5d34-11eb-9ce9-c358e578b2a4.jpg)

**Comment by Areldir** [comment]
Please move this and any other ideas to the new Discussions tab, so Issues can be for bugs. Thanks.

**Comment by arkimedes1967** [comment]
Ok, moved. You may close this thread.
