### ISSUE TITLE
Wrong file name in linux version

### ISSUE THREAD

**Issue by maistoast** [Keriew/augustus#219]
Files in mods/Areldir/Mess_Hall_Walker/ are all lowercase but augustus complains about it:
> ERROR: Unable to open png file  mods/Areldir/Mess_Hall_Walker/Mess_Walker_nw_11.png
INFO: Unable to load image  Mess_Walker_nw_11
ERROR: Unable to open png file  mods/Areldir/Mess_Hall_Walker/Mess_Walker_nw_12.png
INFO: Unable to load image  Mess_Walker_nw_12
ERROR: Unable to open png file  mods/Areldir/Mess_Hall_Walker/Mess_Walker_n_01.png

Renaming these files solve the issue. I used this command in bash:
`dir="mods/Areldir/Mess_Hall_Walker"; for file in $(ls $dir); do mv -iv $dir/$file $dir/${file/mess_walker/Mess_Walker}; done`

Another thing: I got this warning for almost every png files:
> libpng warning: iCCP: known incorrect sRGB profile

Running mogrify on every png file solves the issue. I used this command inside the game dir:
`find mods/ -iname '*.png' -exec mogrify {} \;`

See: 
https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile#answer-22747902

**Comment by crudelios** [comment]
Hi, thanks for the report. Your command not only solves the issue, but it also reduces file sizes to boot.

Regarding case-sensitivity problems on Linux, I'm going to get around to fix that. I also want to add support for having the mods in a different place such as `/usr/share` or `/usr/local/share`.

**Comment by crudelios** [comment]
Case sensitivity fixed by https://github.com/Keriew/augustus/commit/c9a59a11bb39de57a71bf370670e49840ec680fb (on master only for now).
