### ISSUE TITLE
Characters limit.

### ISSUE THREAD

**Issue by ignatevp** [Keriew/augustus#22]
Is there any human character limit for a map to be simultaneously present on?

It appears like there is. I tried to do a 'gladiator defense' challenge, it's when you defend your city by building a gladiator schools and making a long way to a coliseum thus producing tons of gladiator characters which fight an approaching enemy if they meet then on their way.
I noticed that at some point I started having troubles with my pottery production, which seems to be connected to clay pit carts pushers disappearing right after finishing the product, same issue also took place for the lumber production. I removed all the gladiator schools thus significantly decreasing a number of characters present on the map and the issue seem to disappear.
It's a bit tricky to reproduce as you need to build a city to test it.
So I wonder if there is any limitations which might cause this behavior?

P.S. Thanks for all the work you've done to develop Julius, you're doing a great job! 
Glad that someone follows this awesome game.

**Comment by Legionary2** [comment]
Yes, in short c3 has what we call walker limits (sprite limits) The limits are further segmented into destination walkers (point to point) and random walkers. In addition there is also building limits. Luckily , Kerview made the shift to expanded limits and now in the next release of Augustus , you’ll be able to have lots of more of everything (buildings / walkers etc)

**Comment by Legionary2** [comment]
Shift as in the save file is different and can accommodate these expanded changes. Cities with this new save format will not be cross compatible after that point.

**Comment by ignatevp** [comment]
Got it, thanks for explanation.

**Comment by Keriew** [comment]
This, and other limits have already been addressed in 8c90b5e but it's not in the release version yet. Still needs a lot of testing, and I'd like to include many other features before releasing.
