### ISSUE TITLE
Mouse cursor not scaling

### ISSUE THREAD

**Issue by thebashsupremacy** [Keriew/augustus#23]
Using Augustus 1.3.1 on Windows 10 with 200% display scaling.
The entire game scales fine, but the mouse cursor does not and is comparatively tiny. Changing mouse cursor settings in Windows has no effect once in the game, it is like the game hat its own cursor that is fixed in pixel size. (Might have something to do with that SDL thing?)

**Comment by Keriew** [comment]
Game supports a command line parameter for cursor scaling. Try launching the game with "--cursor-scale NUMBER" parameter, with number being 1.5 or 2. I'll look into how challenging it would be to detect and implement it automatically.

**Comment by crudelios** [comment]
We are about to add scaling to the config window in Julius, so I'll close this.
