### ISSUE TITLE
Oops, crashed with signal 11 :(

### ISSUE THREAD

**Issue by ArtySh0ck** [Keriew/augustus#231]
Yep...

Recently i made update of my augustus 2.0.1 to latest 2.0.1.203
Then, i renamed folder "mods" to "assets"
And game crashes before it starts, i attached my augustus log file
[augustus-log.txt](https://github.com/Keriew/augustus/files/5948300/augustus-log.txt)

...errors on the bottom lines of log file.

btw, when i renamed that folder back to "mods" game starts ok, but it send me an error message at start, says: "u havent a right "assets" folder", u know...

**Comment by crudelios** [comment]
The crash shouldn't happen obviously, but the format of the xml has changed so it isn't possible to just change the folder name.

For now, grab the assets folder from github directly (download the `master` branch as a zip and grab the `assets` folder).

I'll need to check what's causing the crash anyway.

**Comment by ArtySh0ck** [comment]
Thanks mate! Now its good =)
