### ISSUE TITLE
Game not starting at Windows

### ISSUE THREAD

**Issue by fsiston** [Keriew/augustus#237]
Just few hours after installing the last version of Augustus, my Windows made updates. After that the game is not starting at all. It shows a black window that turn into white and I need to crash the Augustus process to keep utilising my pc.

**Comment by crudelios** [comment]
Hi, please paste the contents of `augustus-log.txt`

**Comment by fsiston** [comment]
INFO: Augustus version 2.0.1
INFO: Initializing SDL
INFO: SDL initialized
INFO: Loading game from working directory
INFO: Config key  ui_sidebar_info  1
INFO: Config key  ui_show_intro_video
INFO: Config key  ui_smooth_scrolling  1
INFO: Config key  ui_walker_waypoints  1
INFO: Config key  ui_show_water_structure_range  1
INFO: Config key  ui_show_construction_size  1
INFO: Config key  ui_zoom  1
INFO: Config key  ui_highlight_legions  1
INFO: Config key  ui_show_military_sidebar
INFO: Config key  ui_disable_map_drag
INFO: Config key  gameplay_change_jealous_gods
INFO: Config key  gameplay_change_global_labour
INFO: Config key  gameplay_change_retire_at_60
INFO: Config key  gameplay_change_fixed_workers
INFO: Config key  gameplay_wolves_block
INFO: Config key  gameplay_buyers_dont_distribute
INFO: Config key  gameplay_change_getting_granaries_go_offroad
INFO: Config key  gameplay_change_granaries_get_double
INFO: Config key  gameplay_change_tower_sentries_go_offroad
INFO: Config key  gameplay_change_farms_deliver_close
INFO: Config key  gameplay_change_only_deliver_to_accepting_granaries
INFO: Config key  gameplay_change_all_houses_merge
INFO: Config key  gameplay_change_random_mine_or_pit_collapses_take_money
INFO: Config key  gameplay_change_multiple_barracks
INFO: Config key  gameplay_change_warehouses_dont_accept
INFO: Config key  gameplay_change_houses_dont_expand_into_gardens
INFO: Config key  gameplay_change_monuments_boost_culture_rating
INFO: Config key  ui_language_dir
INFO: Config value  
INFO: Detected language:  Portuguese
INFO: Detected encoding:  1252
INFO: Translation key not found:  +  12
INFO: Translation key not found:  -  13
INFO: Translation key not found:  Page  17
INFO: Translation key not found:  Rotate Gatehouse and Triumph Arch by hotkey  28
INFO: Translation key not found:  Draw walker waypoints on overlay after right clicking on a building  32
INFO: Translation key not found:  Enable zoom (can be slow, uses more RAM)  33
INFO: Translation key not found:  Fix uncompleted rating columns on low targets  34
INFO: Translation key not found:  Grand festivals allow extra blessing from a god  35
INFO: Translation key not found:  Disable jealousness of gods  36
INFO: Translation key not found:  Enable global labour pool  37
INFO: Translation key not found:  Extend school walkers range  38
INFO: Translation key not found:  Change citizens' retirement age from 50 to 60  39
INFO: Translation key not found:  Fixed worker pool - 38% of plebeian population  40
INFO: Translation key not found:  Allow building 4 extra forts  41
INFO: Translation key not found:  Block building around wolves  42
INFO: Translation key not found:  Block unconnected granary roads  43
INFO: Translation key not found:  Houses stockpile more goods from market  44
INFO: Translation key not found:  Buying market ladies don't distribute goods  45
INFO: Translation key not found:  Immediately destroy buildings  46
INFO: Translation key not found:  Cart pushers from getting granaries can go offroad  47
INFO: Translation key not found:  Double the capacity of cart pushers from getting granaries  48
INFO: Translation key not found:  Tower sentries don't need road access from barracks  49
INFO: Translation key not found:  Farms and wharves deliver only to nearby granaries  50
INFO: Translation key not found:  Food isn't delivered to getting granaries  51
INFO: Translation key not found:  All houses merge  52
INFO: Translation key not found:  Open trade route count as providing different wine type  53
INFO: Translation key not found:  Randomly collapsing clay pits and iron mines take some money instead  54
INFO: Translation key not found:  Allow building multiple barracks  55
INFO: Translation key not found:  Warehouses don't accept anything when built  56
INFO: Translation key not found:  Houses don't expand into gardens  57
INFO: Translation key not found:  Housing advisor  103
INFO: Translation key not found:  Rotate building  110
INFO: Creating screen 1366 x 768, fullscreen, driver: windows
INFO: Creating renderer
INFO: Textures created (1366 x 768)
INFO: Model loaded
INFO: Loading mod file  mods/aesthetics.xml
INFO: Loading mod file  mods/ceres_temple.xml
INFO: Loading mod file  mods/engineer.xml
INFO: Loading mod file  mods/lighthouses.xml
INFO: Loading mod file  mods/mars_temple.xml
INFO: Loading mod file  mods/mercury_temple.xml
INFO: Loading mod file  mods/mess_hall.xml
INFO: Loading mod file  mods/mess_hall_walker.xml
INFO: Loading mod file  mods/neptune_temple.xml
INFO: Loading mod file  mods/pantheon.xml
INFO: Loading mod file  mods/roadblocks.xml
INFO: Loading mod file  mods/slave_walker.xml
INFO: Loading mod file  mods/ui_elements.xml
INFO: Loading mod file  mods/venus_temple.xml
INFO: Loading mod file  mods/workcamps.xml

**Comment by webfischi** [comment]
I only see missing translation keys in that log file. If you like, you could add the 48 missing strings in the portugese.c translation. Currently only english and german are complete in the master branch. I would suggest building the current master branch on your system.

**Comment by fsiston** [comment]
Hi. I restarted Windows few times, more Windows' updates and Augustus is working again.

I will check the strings, but where should I add them?

Thanks people!

**Comment by crudelios** [comment]
How strange! The game didn't crash internally.

If it works now, it was likely a graphics driver issue between updates.

The translation strings should not influence the game. But if you want to help translating you can check which ones need translating from the log file, add them here by opening a new issue and we'll do the rest 😉
