### ISSUE TITLE
updated french translation

### ISSUE THREAD

**Issue by Trokinos** [Keriew/augustus#238]
Hello,

I updated the french.c translation to be on par with all the ones from the english.c  
I also shortened a translation in the interface (the culture bonus to the new large temples) that was too long for the screen.

[frenchLNG4.zip](https://github.com/Keriew/augustus/files/5972489/frenchLNG4.zip)

**Comment by crudelios** [comment]
Thanks for this. I have added the updated translation.

**Comment by Trokinos** [comment]
Hello, 

Maybe i'm not looking at the correct place but it seems the french.c 
https://github.com/Keriew/augustus/blob/master/src/translation/french.c
is still using the old incomplete version.

**Comment by crudelios** [comment]
It's not on `master` but on `release`.

You can find the commit here: https://github.com/Keriew/augustus/commit/505ff78640c6dfb00cc61f66ead8031a3b9b31bd

**Comment by Trokinos** [comment]
Thank you, i'll have to update my bookmarks :)
