### ISSUE TITLE
More than two grand temples

### ISSUE THREAD

**Issue by StElysse** [Keriew/augustus#239]
Is it possible for me to modify the code in my local Augustus folder to allow the placement of more than two Monuments/Grand Temples? That Carthage screenshot at the Augustus homepage is incredibly tantalizing.

**Comment by MSTVD** [comment]
That is something that's been proposed to be added as a config for user made maps, not sure about campaign though. Would love to see what others have to say.

**Comment by crudelios** [comment]
> Is it possible for me to modify the code in my local Augustus folder to allow the placement of more than two Monuments/Grand Temples?

Sure it is! Go ahead and do it! Cities saved with more than two grand temples should also open up just fine on "vanilla" Augustus, so no worries there.

**Comment by StElysse** [comment]
> Sure it is! Go ahead and do it! Cities saved with more than two grand temples should also open up just fine on "vanilla" Augustus, so no worries there.

If I may rephrase what I asked originally:

What I would like to do is place more than two grand temples in my cities. Vanilla Augustus won't let me do this. How can I mod Vanilla Augustus to allow me to do this? Thank you!

**Comment by crudelios** [comment]
Sure, in `building/construction.c` and `building/construction_building.c` search for:

 `&& building_monument_count_grand_temples() >= 2`

And remove that!

**Comment by StElysse** [comment]
Which file do I need to modify that contains this code you mentioned? Where can it be found? How can I modify it?

**Comment by crudelios** [comment]
You need to modify the source code of Augustus itself.

Read how to [build Julius](https://github.com/bvschaik/julius/wiki/Building-for-Windows) if you're interested in doing so (it's for Julius, but the process is the same for Augustus).

Changing the source code and compiling the game yourself is rather technical, so I can't help you any further than that.

Apart from it, the idea of having more than two grand temples has been discussed but for now we'd rather have this gameplay limit.

**Comment by StElysse** [comment]
Thank you for taking the time to help! If I find the courage to fiddle around in VS, I will remember.

**Comment by maistoast** [comment]
Hello, I already defined a variable to modify it. I would like to to add an option so the user can set it. At the moment all the options for augustus are booleans; could you provide some info how could I implement an option that sets an integer value?

**Comment by crudelios** [comment]
You can either use the `numerical range` input that is used for scaling settings, or the numerical input window to input a number. Other than that, internally the boolean as already an int that can be either `0` or `1`, so the config file already supports its.

**Comment by maistoast** [comment]
Ok thanks I'll look into it

**Comment by maistoast** [comment]
Where can I discuss about coding? Here?

**Comment by crudelios** [comment]
It's better on [Discord](http://www.discord.gg/GamerZakh), go to the `#augustus` channel.
