### ISSUE TITLE
Trade ships don't always appear on unstable builds

### ISSUE THREAD

**Issue by maistoast** [Keriew/augustus#240]
I'm in Tingis in the military campaign. I opened the trade route with Carthago Nova but no ships are coming. Is it a bug or am I missing something very basic here? 

[aug.zip](https://github.com/Keriew/augustus/files/5977583/aug.zip)

**Comment by Areldir** [comment]
Kinda dumb question, but have you made sure to build a dock and set your imports/exports in the advisor?

**Comment by maistoast** [comment]
I did. I attached a save file if you have time to check.

**Comment by crudelios** [comment]
Which version of augustus are you using?

**Comment by maistoast** [comment]
Augustus version 2.0.1.206-cc7b089a

**Comment by crudelios** [comment]
Ah, it's a known issue then.  The specialized docks PR (#201) has some pending issues with dock pathfinding.

@xyn22 is already aware of that but I'll keep this issue open for everyone else to know.

**Comment by maistoast** [comment]
Is it possible to rebuild augustus without that feature?

**Comment by crudelios** [comment]
No but you can get the build immediately before that one from either appveyor (if you use Windows) or bintray (for everything else)

**Comment by maistoast** [comment]
Is it possible to make Tingis a land trade route modifying the source code?

**Comment by crudelios** [comment]
Not really. Your best bet is to eithrr get an older version or wait for a fix.

**Comment by xyn22** [comment]
I'll be working on it very soon today, I'll collect all save files from here and discord and more save files are highly appreciated

**Comment by crudelios** [comment]
The trade ships should now appear. However, the underlying issue (the fact that ships can't queue in land tiles) is an original bug from C3 and eventually needs fixing.
