### ISSUE TITLE
New buildings don't render

### ISSUE THREAD

**Issue by rubensoleao** [Keriew/augustus#241]
The newly added buildings in Augustus (roadblocks, engineer's guild, supply post etc...) Don't render properly and glitch. 

![glitch image preview](https://i.imgur.com/ifddBq3.png)

I'm running on linux. When i run the executable in the terminal i don't see any errors on terminal and when compuling I get only a couple warnings. ( [Compile output pastebin)](https://pastebin.com/q6K5KU5R).

Is there anything I can do? Thanks.

**Comment by rubensoleao** [comment]
Ohh I tried putting the assets folder in the Ceasar3 Directory and it worked. It wasn't clear in the installation instructions. Thanks!

**Comment by chpill** [comment]
@rubensoleao I have exactly the same problem as shown in your screenshot. I tried copying the `assets` file of this repo into what I think is the Caesar3 Directory (where you can find the `Caesar3.ini` and the `augustus.ini` files), but it does not seem to work...

Could you please explain what you did to fix this?

**Comment by crudelios** [comment]
@chpill It depends on how you're doing things.

What version are you using?
Did you compile Augustus yourself?
If so, are you installing it?

**Comment by chpill** [comment]
@crudelios yes sorry :sweat_smile: 

I use the augustus-2.0.1-linux.AppImage, and the first time I launched it, it asked about the path of the caesar3 game files (which I installed by using innoextract on `setup_caesar3_2.0.0.9.exe` I got from GOG).

I'll try building the game from source later today to see if that works better.

**Comment by crudelios** [comment]
Is it the release version 2.0.1 or the newest unstable?

If it is the release version, you don't need the newer `assets` folder, rather the older `mods` folder that comes with that version. 

If you're using the latest unstable build, the appimage doesn't need any folder as it already includes the extra assets. In that case, deleting the `assets` folder from the C3 directory should do the trick!

**Comment by chpill** [comment]
I downloaded the latest unstable build of the AppImage, and, indeed, it works out of the box. I also tried building it from sources, and I could get the new assets by copying the assets folder into caesar3 folder. As this is not needed with the AppImage, I'll stick to that.

Thank you @crudelios !

**Comment by crudelios** [comment]
You're welcome!

Indeed right now things are somewhat confusing because the assets folder was created after the latest release. Hopefully when there is a new release things will get smother.
