### ISSUE TITLE
Augustus wont save a game (russian version bug)

### ISSUE THREAD

**Issue by ArtySh0ck** [Keriew/augustus#244]
Augustus version: 2.0.1.234

Playing Campaing on Syracuzes map now, when try to save - game immediately CTD

[Архитектор.zip](https://github.com/Keriew/augustus/files/6017884/default.zip)

just try to Save...

here is log: 
[augustus-log.txt](https://github.com/Keriew/augustus/files/6017887/augustus-log.txt)

Thanks!

**Comment by crudelios** [comment]
It's saving fine for me on master though...

**Comment by ArtySh0ck** [comment]
win10 x64

**Comment by ArtySh0ck** [comment]
just test this moment on 2.0.1.203 - its fine. when i click "Save" then appears window with saving menu...

CTD came when just click on "Save" in game menu

**Comment by crudelios** [comment]
The window doesn't appear at all?

Can you do me a favour and try it on Julius as well (in Russian too)

**Comment by ArtySh0ck** [comment]
Julius 1.6.0.42 - works fine (rus.ver)

**Comment by crudelios** [comment]
No matter how much I try, I can't reproduce this issue. I have an idea what might be causing it, but I need your help.

- Does it happen with every file or only with files saved in the Russian language?
- What if you change the game language to English (The file name will become a bunch of `???`). Does it still crash?
- What if you (temporarily) move all your saves away from the C3 folder and start from scratch? Does it still crash?

Thanks!

**Comment by ArtySh0ck** [comment]
ok, i'll try it lil later, got to go for now

**Comment by ArtySh0ck** [comment]
You're right. Solution was to change game language back to english (default)

**Comment by crudelios** [comment]
That is no proper solution though.

I need a favour from you. Can you grab all your savefiles (both `.sav` and `.svx`), zip them and place them here.

I want to reproduce your issue to properly fix it,  and that would help.

**Comment by ArtySh0ck** [comment]
here
[SAVs.zip](https://github.com/Keriew/augustus/files/6023403/SAVs.zip)
[SVXs.zip](https://github.com/Keriew/augustus/files/6023404/SVXs.zip)

**Comment by crudelios** [comment]
Thanks for the files.

Wouldn't you know, the crash happens where there are less than 12 savefiles available (which is your case), regardless of language.

Also, this is actually a Julius crash, so I'll fix it there.

**Comment by ArtySh0ck** [comment]
Thanks!
