### ISSUE TITLE
Suggestion: Templates

### ISSUE THREAD

**Issue by jackgraves** [Keriew/augustus#245]
This is an improvement request to allow the user to create templates for sets of buildings they want to build in one step.

For example:

1. Create a template by clicking a button and dragging across an area of the map
2. The area will be saved as a template and can be used to create that set of buildings again
3. Templates could be accessed through a menu (create, delete, update etc.)

This would be a really cool addition, as a lot of the game is understanding the patterns (order of buildings) to use.

A cool extension of this would be to allow sharing templates using the clipboard (e.g. Copy/Paste JSON online).

**Comment by crudelios** [comment]
This is not an issue but a feature suggestion/discussion, therefore it should go to the "Discussions" tab.

Regarding the idea itself: while I understand your reasoning (housing blocks could be easily shared), this is so beyond the capabilities of the game engine that for now (and the foreseeable future) this is simply not possible to add.
