### ISSUE TITLE
Language packs are very hard to find

### ISSUE THREAD

**Issue by sickchicken** [Keriew/augustus#246]
https://github.com/bvschaik/julius/wiki/Patches
How do you think about this page going in
Main pages of [Julius mod](https://github.com/bvschaik/julius) and [Augustus mod](https://github.com/Keriew/augustus
) for easier download? 'Running Julius' - 'Patches' could be bit vague for a bunch of language packs. How about directly having "To download language packs, click here" kind of link also? 

And about Julius-Augustus, it may cause misunderstanding. We can write that you may need certain some assets from Julius to run Augustus right(like that language patch)

For now, I think it's very hard to find and download. I'm trying reinstalling Caesar III and Augustus mod to double-check it, but it took almost 5-10 min to find it.

**Comment by crudelios** [comment]
Regarding the patches/ language, we could indeed add a link to the main page.

For the download link, it's available right on the front page. You click the version you want then just need to click the file name in the page that opens. We can't really make it easier right now as we can't provide a direct link.

**Comment by sickchicken** [comment]
I thought it may cause misunderstanding because the word 'patch' sounds nothing like option regarding language/translation. Some people find it really hard to play without translation in non-English speaking countries. 

Also, I thought Augustus being different mod but sharing some assets like those language packs, maybe I can put that info in readme_KR file as well. I know I'm being obsessed about same file or little details, but I saw a Korean guy from Youtube making a guide dedicated to downloading & updating these mod and Korean patch because so many players are missing this gem, so I feel like I must give detailed/easier guide as best as I could. 

If that's OK, can I put bit more info for full mod install in Korean readme, not like the original one?

Thank you for instant feedback.
[patch_readme_KR.txt](https://github.com/Keriew/augustus/files/6029915/patch_readme_KR.txt)

**Comment by crudelios** [comment]
Well, technically we aren't providing language packs but a patch to the v1.1 version of the game.

Each patch is for a specific original game's language, hence the language distinction and the possible confusion about language packs.

Regarding adding that info to the readme, I'm pinging @bvschaik

**Comment by sickchicken** [comment]
Thanks a lot. It's about language pack itself being compatible with everything, texts hardcoded into the mod file, the difference between Julius and Augustus, and the quick guide of installation.

**Comment by crudelios** [comment]
Haha yeah, this being an open source project it's hard to avoid some technical stuff. That is especially difficult when english is not your mother language. Maybe going forward we will create an easier way to download files, but for now this is very well suited for our own needs and it's also free, so we can't really complain :wink:
