### ISSUE TITLE
Unstable build bug / Korean translation

### ISSUE THREAD

**Issue by sickchicken** [Keriew/augustus#247]
1.Unstable build won't recognize Augustus /mods asset folder in Caesar 3 folder.
But 'transparent' texts issue was fixed in unstable version, and texts were much cleaner. Thank you for your hard, wonderful work!
2.In 'Running Julius' - 'Patches' - Korean language pack, Korean translated texts are still missing. Just reinstalled and double-checked.

**Comment by bvschaik** [comment]
> 2.In 'Running Julius' - 'Patches' - Korean language pack, Korean translated texts are still missing. Just reinstalled and double-checked.

The Korean patch does not contain any of the new texts, those are hardcoded into julius/augustus.

**Comment by sickchicken** [comment]
Didn't know that, thanks for the info. So it's kind of font/locale data, not the text itself?
Anyway, transtated texts weren't applied in unstable version correctly.

**Comment by crudelios** [comment]
1. The latest unstable build uses a new `assets` folder, not the old `mods` folder, so you need to update your folder.

2. What texts are exactly missing? New strings are constantly added so it may just be that the translation you provided is already outdated.

**Comment by sickchicken** [comment]
1.Actually tried 3 ways.
(1)Classic '/mods' folder.
(2)Duplicated the folder and changed the name into '/assets' so the game have both /mods and /assets.
(3)Put the /assets into /mods
It still says /assets folder is missing.

2.As I mentioned, I completed Korean translation including some unfinished Korean texts but it remains unchanged. For example, mod options are still English.

**Comment by crudelios** [comment]
You can't just change the name into `assets`, you actually need to grab a new `assets` folder from github.

All thenew  translations you provided have been added about one month ago. They are in the latest unstable.

**Comment by sickchicken** [comment]
Yup, I'm talking about that unstable. Latest unstable is augustus-2.0.1.236-0ce6d7a9-windows, correct?
It's still aren't there.

**Comment by crudelios** [comment]
Can you send me a screenshot please and `augustus-log.txt` please? So I can identify what's going on, because it should be working.

**Comment by crudelios** [comment]
I got what happened. You didn't add all the translations to the PR, but they are in the issue.

I'll update the translations.
