### ISSUE TITLE
SDL2 weight difference

### ISSUE THREAD

**Issue by ArtySh0ck** [Keriew/augustus#248]
Have a question...

Julius have SDL2 newer version rather than Augustus have. I have one playable directory with caesar 3 (+julius +augustus)... wanna know, which sdl2 should i use for more proper for BOTH modules? sdl2 from augustus builds (its lighter) or sdl2 from julius builds (its heavier)?

thanks!

**Comment by crudelios** [comment]
I think both of them are interchangeable, but the one that is provided with Julius is more recent so it may have some bugs fixed. Eventually Augustus will be updated too so they will both share the same SDL.

**Comment by ArtySh0ck** [comment]
Clear. Thanks!
