### ISSUE TITLE
Legion Status menu extend over the menu area when allowing 3 extra forts

### ISSUE THREAD

**Issue by theodoretsai** [Keriew/augustus#26]
The 3 extra legions extend past the menu area in Legion Status menu and it's glitchy when trying to click any action on them.

I don't know if this counts as a large UI change, if so feel free to just close the issue.

**Comment by Legionary2** [comment]
Hello! Yes , the UI issue - we are aware. It will eventually be displayed properly along with a final fort.

**Comment by Keriew** [comment]
Implemented in 2a892c4
