### ISSUE TITLE
Damascus start date

### ISSUE THREAD

**Issue by Riww** [Keriew/augustus#265]
Campaign Damascus starts 50 AD, but it should start 10 BC.

**Comment by crudelios** [comment]
I just tested in original C3 to make sure. Damascus starts at 50AD, so Augustus is working fine.

**Comment by Riww** [comment]
Well then it is original bug, still a bug. On mission selection screen, it says 10 BC. Damascus shall start 10 BC, not 50 AD.

**Comment by crudelios** [comment]
You're right, this is an original bug, most likely an oversight from the developers when creating the city files.

Since it isn't possible to fix this without changing the original C3 files, we can't really fix this, so it'll be kept as-is.

**Comment by Riww** [comment]
Ok, created bug for Julius, more appropriate there as it is original bug. 
https://github.com/bvschaik/julius/issues/592
