### ISSUE TITLE
Suggestion: Special Orders from Granaries/Warehouses

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#27]
On my point of view you might consider include on the warehouses a 4th option : "3/4" or "3Q". It's quite useful because if you assign a warehouse to potery prodution, for exemple, you'll accept 3Q of potery and Q of clay. Besides, it's inevitable because you're already have "Q" option leaving only the other 2, "F" or "H", resulting on a uneficient warehouse space.

Awesome work, so far. Congrats!

**Comment by Legionary2** [comment]
Hi there , we will be implementing the 3/4 option. Hopefully , a conversion to numbers will be utilized instead of letters , example 8,16,24,32 and granary 6,12,18,24 respectively

**Comment by Legionary2** [comment]
UI work can be time consuming from my understanding so it’s just a matter of time but we have been meaning to convert and implement 👍🏻

**Comment by Keriew** [comment]
Implemented in 01edea2
