### ISSUE TITLE
Labour camp doesn't seem to be working

### ISSUE THREAD

**Issue by imyungdae** [Keriew/augustus#270]
I started building lighthouse, and gathered marble into the warehouse. There is road connection between the two, and also there are sufficient workers for both the labor camp and engineers guild. Yet they don't fetch the marble from the warehouse, even after I set WH to "not accepting" marble.

**Comment by Keriew** [comment]
Could you upload the save with that situation so I could take a look?

**Comment by imyungdae** [comment]
Sure, here it is.

[AugustusSave.zip](https://github.com/Keriew/augustus/files/6100563/AugustusSave.zip)

**Comment by Keriew** [comment]
All right. Monuments require center piece to be connected to the road, not just any tile. You can see when it works, because the road will turn into the monument. I'll update warning message to make it more clear.

**Comment by imyungdae** [comment]
Ahh I see, thank you, works now. Closing topic.

**Comment by Keriew** [comment]
Improved the road access message in 0c846ce.
