### ISSUE TITLE
Epithets

### ISSUE THREAD

**Issue by HoratioVex** [Keriew/augustus#274]
Some of the epithets used for the grand temples strike me as both historically and grammatically incorrect.

Promitor and Reparator were some kind of helper gods of Ceres', not epithets. More importantly, they're male, so the gender of the word doesn't agree with the name of the goddess.

Abundantia has the same problem: different deity, and the word is female.

**Comment by Areldir** [comment]
Yes, I agree these should be changed. The original "epithets" were added in a bit of a rush, and I didn't have time to review them to make sure they were appropriate before we released. Which epithets do you think need changing the most?

**Comment by Keriew** [comment]
Updated them in 432a89b

**Comment by Keriew** [comment]
With lack of further comments, I assume the rest are fine. Please reopen if you think any other need changing.
