### ISSUE TITLE
Suggestion: Rasing Culture Ratings

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#30]
There's something that always buged me, since the release the game: the culture ratings. The culture rating is calculated by comparing the number of buildings the city has in these categories (temples, oracles, schools, libraries, academies or theaters)  with the size of the population.

It's anoying to see, on some corner of our city, a pile of theaters, libraries, etc., only to satisfy the culture rating.

My humble suggestion: instead of changing the culture calculating formula, you might consider adding some upgradable culture buildings, the same way that markets, baths and senate upgrade doe to excelent desirability. These upgraded buildings might boost the city culture rating allawing/attending more people (doble or tripling the base building capacity), favoring the unchanged cultural rating formula of the game.

Keep up the good work!

![Bath](https://user-images.githubusercontent.com/64329357/80298573-b11ba300-8785-11ea-8fc5-63f4c5808332.png)   ![Bath 2](https://user-images.githubusercontent.com/64329357/80298574-b678ed80-8785-11ea-91fd-2d76f56543a4.png)

**Comment by Legionary2** [comment]
That’s not a bad idea , although we are still unsure just exactly how we will be going about culture. The current consensus is to implement a walker coverage system similar to how tax coverage % is shown in the finance tab. If all houses are covered by theatres then culture points are added for perfect coverage etc. we plan on expanding the list of culture important buildings as well to all types of entertainment, education , religion, and now even health services.

**Comment by arkimedes1967** [comment]
I'll leave an exemple for the libraries. Just took a couple hours using current existing images of C3.

![Commerce_00084](https://user-images.githubusercontent.com/64329357/80298440-503f9b00-8784-11ea-8684-732d8bf79eea.png)    ![Library3](https://user-images.githubusercontent.com/64329357/80298446-5e8db700-8784-11ea-91cb-75565d530f75.png)

I'm looking foward to try your next release. I love your work!

**Comment by Legionary2** [comment]
Do you have graphic experience?

**Comment by Legionary2** [comment]
> I'll leave an exemple for the libraries. Just took a couple hours using current existing images of C3.
> 
> ![Commerce_00084](https://user-images.githubusercontent.com/64329357/80298440-503f9b00-8784-11ea-8684-732d8bf79eea.png) ![Library3](https://user-images.githubusercontent.com/64329357/80298446-5e8db700-8784-11ea-91cb-75565d530f75.png)
> 
> I'm looking foward to try your next release. I love your work!

- you can also join discord / gamerzach channel to join on discussions etc - we are all very active over there especially the creator Keriew

**Comment by arkimedes1967** [comment]
> Do you have graphic experience?

Because of the Covid-19 i find myself with extra time to play C3 using Julius mod. As an hobby, i play with GIMP for fun. Since i have extra time, in a 3 months time i'll be a pro, on both! ;)

**Comment by Legionary2** [comment]
> > Do you have graphic experience?
> 
> Because of the Covid-19 i find myself with extra time to play C3 using Julius mod. As an hobby, i play with GIMP for fun. Since i have extra time, in a 3 months time i'll be a pro, on both! ;)

- Cool, come back and let us know !!!

**Comment by crudelios** [comment]
This is being implemented and there is now a more recent issue, so I'm closing this.
