### ISSUE TITLE
Default North for Delivery

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#31]
Is there any possiblity to costumize the waypoint/ face in of the buildings for delivery and walkers in general?

City walkers and delivery men use the longest path to do their job, because they use, by default, the North side  of buildings, the "wrong way" on the player's perspective, in some cases.

I've made some gifs that shows what i mean below.

First option: North

![Warehouse - North](https://user-images.githubusercontent.com/64329357/80322626-6437db00-881e-11ea-8513-20a359919df8.gif)

Second option: North through West

![Warehouse - East to North](https://user-images.githubusercontent.com/64329357/80322637-7580e780-881e-11ea-9444-800b7b4e3dad.gif)

Third option: East

![Warehouse - West](https://user-images.githubusercontent.com/64329357/80322646-7fa2e600-881e-11ea-8f39-1aadb2778fbb.gif)

Fourth option: South (the most efficient entery to the building)

![Warehouse - South](https://user-images.githubusercontent.com/64329357/80322765-11125800-881f-11ea-9d5d-359f67f4a0a3.gif)

To a city up then 5k, it can be an issue because it's not an eficient one. The present solution is start building your city the farest North as possible, wich is not allways possible.

Finaly, what's the porpuse for the "Draw walker waypoint on overlay after right clicking on a building" on Augustus 1.31 version?

**Comment by Legionary2** [comment]
Yes this issue manifests itself further with multiple warehouses behind a coast of docks for example. I’m sure Keriew will take a look at this !

**Comment by arkimedes1967** [comment]
Ok, thank you. And what about my final question about the "Draw walker waypoint on overlay after right clicking on a building" on the options of Augustus 1.31 version?

**Comment by Legionary2** [comment]
Oh shoot - missed that. Its basically a rough idea of where the walkers should end up on their daily paths. People in the past suggested routes be actually drawn to show where they would walk each time but that would require heavy resource calculation

**Comment by arkimedes1967** [comment]
> People in the past suggested routes be actually drawn to show where they would walk each time but that would require heavy resource calculation

I think it's really unecessary at all, on my point of view. As i use rodbloks heavily, it's now possible to close a 'perfect' square block, no further calculations needed.

 However, it would help a lot the further development of the overlay information:

- The Commerce/Food overlay should also include visible walkers between granaries (walkers getting goods);
- There's no goods overlay, maybe it whould be a good idea implement that, showing more or less the same as above but concerning goods (pottery, furniture, etc); 
- It would be perfect if created a new overlay under the STOCKS name (food + goods), and other under ADMINISTRATION (desirability + taxes);

What's your opinion?

**Comment by crudelios** [comment]
So apart from markets, with building rotatiom from #90 this should be fixed, right?

**Comment by arkimedes1967** [comment]
Yes, you can close this thread, thank you.
