### ISSUE TITLE
Materials go into Grand Temple and disappear

### ISSUE THREAD

**Issue by 7Soul** [Keriew/augustus#318]
My setup:
![image](https://user-images.githubusercontent.com/5599828/115447597-11092600-a1ef-11eb-8a64-2ba7d0fc90c6.png)

Marble is being delivered to that currently empty warehouse. The engineer comes in, takes it, walks up towards the granary and from it, into the temple, but no marble is added to the temple

The map, save file and augustus.ini files:
https://drive.google.com/file/d/1ZpbQlpgIqfXQt8AATLdYC8h7jtzSx7-l/view?usp=sharing

As soon as you load it, you can see the marble being delivered and then vanishing

**Comment by Keriew** [comment]
Hey, thanks for the report! We've fixed this already in 7fe9ab2. To not have that problem you can download the unstable version, which has it fixed, or make sure that the monument has a non-diagonal connection to a middle tile.
