### ISSUE TITLE
Roadbloks Still Need Work

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#32]
The roadsblok is ignored on doble roads. See the gif below.

Thank you on advance, you're the best, really. Roadblocks is a revolution on C3. Now we can build cities with out gatehouses everywhere. ;)

![Roadbloks](https://user-images.githubusercontent.com/64329357/80391631-e7504400-88a5-11ea-838d-5863d6f63d6c.gif)

**Comment by theradeonxt** [comment]
Hello,

I have noticed a similar thing when placing engineers and prefectures - Only happens when they are at a corner of a road, so a road is not directly in front of them but in diagonal.
I think roadblocks are ok, please try with normal roads and diagonal building - should be same problem.

I can confirm for engineers, prefectures, small temples, forums. I always have to make sure to not place them near a diagonal road or near a gatehouse - or they will spawn on the wrong side!

**Comment by arkimedes1967** [comment]
> I think roadblocks are ok, please try with normal roads and diagonal building - should be same problem.
> 
> I can confirm for engineers, prefectures, small temples, forums.

I agree with you: roadbloks are ok. It's the best and the most needed mod for C3.

I realise that the "North" thing is the problem. Whenever a building touches a road faced North the walkers spawn in that direction.

Look at the temple on the left: it goes in the intended road, guess what, it faces North!

![Roadbloks_North](https://user-images.githubusercontent.com/64329357/80426495-be4ba580-88dd-11ea-8d8c-594c336ac163.gif)

**Comment by theradeonxt** [comment]
On second thought you are right, I did not know this North spawn causes it. I always feared the wrong spawing of people when placing anything that can touch diagonally...
Learned something new today!

**Comment by arkimedes1967** [comment]
And you're right also, ... diagonally North :))

**Comment by arkimedes1967** [comment]
Other 2 example an the current solution to it: double roadblocks:

![Roadblock 1](https://user-images.githubusercontent.com/64329357/80916036-122b1400-8d4e-11ea-88ef-aa40a6496b07.gif)  ![Roadblock 2](https://user-images.githubusercontent.com/64329357/80916039-17885e80-8d4e-11ea-981b-9c312baf9fbd.gif)

![Double Roadblock](https://user-images.githubusercontent.com/64329357/80916045-2242f380-8d4e-11ea-863c-5fe2ec308680.gif)

**Comment by arkimedes1967** [comment]
One more weird behavier of a prefect near a roadblock: he makes a shortcut on the North corner of the building like a deliver man of the warehouse (drop corner). To correct it, we must doble roadblock the acess road, before the building corner.

![Roadblock Wharehouse Bug](https://user-images.githubusercontent.com/64329357/81094700-cf0ea380-8efb-11ea-98ee-0f43e66456e2.gif)

**Comment by Keriew** [comment]
Yeah, that one tile of warehouse is walkable. Not sure if that's something that should be changed.

**Comment by arkimedes1967** [comment]
By rotating the building (not the map) as a future option on C3 (??), it could solve the problem. As you well know, when you rotate the map the image changes.

![Granary](https://user-images.githubusercontent.com/64329357/81138146-f5166100-8f58-11ea-8cdc-dddbc1532bcb.gif)

**Comment by crudelios** [comment]
I believe things that can be fixed here are now fixed, right?

**Comment by arkimedes1967** [comment]
Yes, you may close this thread.
