### ISSUE TITLE
Mods folder missing

### ISSUE THREAD

**Issue by Urides** [Keriew/augustus#339]
Hello,

After having a good time with Julius, I wanted to check Augustus.

I followed the installation instruction, launched the game and... had a problem :

![Mods](https://user-images.githubusercontent.com/24555008/116427909-f6a8fb00-a833-11eb-9ea8-f9561dbe9e36.png)

It says that the mods folder is missing and that new buildings won't be displayed correctly. I need to check that a mods folder exist in my Caesar 3 installation folder.

I tried creating a simple mods folder, empty of course, but that doesn't change.

Did i forget something ?

I'm on linux mint 20.1, using the last Augustus linux AppImage 2.0.1

**Comment by crudelios** [comment]
Hi, download the `mods` folder from the Windows build and place them on your C3 installation folder.

The upcoming 3.0 version will have this issue fixed (mods will be bundled on the Linux Appimag3), but for now you have to follow the above steps.

**Comment by Urides** [comment]
It works fine now.

Thank you for the answer and this great project!
