### ISSUE TITLE
Throwing Automatic Gods Festivals

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#35]
As you may see on the image below, it wont require extensive changes on UI.

With similar customisation as granaries, clicking on the botton, would appear "A" (automatic) throwing repetive gods festivals, one god at the time. We could throw only one type of festival, desabling the other options.

First, we must shoose what kind of festival we want (small, grand or large [*], i'm not sure about this last one because it requires wine) and then click on the automatic botton. It will throw a small festival every 2 month (to each god sequencially), a grand festival every 4 month and a large festival every 6 month.

[*] Maybe throwing a grand festival instead (downgrade) until the city has wine to celebrate a large one, as intended.

![Gods_Automatic](https://user-images.githubusercontent.com/64329357/80663493-fee92180-8a8b-11ea-8a0d-8897972565d5.jpg)

By the way, i found a bug on the Oracle: this building requires road but if we put it just one tile away of the road, it also works fine.

![Oracle](https://user-images.githubusercontent.com/64329357/80663738-c138c880-8a8c-11ea-92b1-8a52f79100c8.gif)

**Comment by Keriew** [comment]
Auto festivals are worth considering, but are low priority for now.

The oracle should not display the warning if they are one tile away from the road in the next version.

**Comment by arkimedes1967** [comment]
Ok, cool. Please consider also adding a shortcut on the festival warning, It's very usefull.

![Festival Shortcut1](https://user-images.githubusercontent.com/64329357/80914917-b1e4a400-8d46-11ea-86e2-85922d372a13.png)

**Comment by arkimedes1967** [comment]
I leave here some thoughts for you to consider about a revamped gods mechanism.

- Gods will either bless you, or curse you depending on their disposition. Each god has a major and a minor "wrath" event for when they're upset, but each only has one "blessing";

- They only bless you when they are exalted... the same blessing over and over;

I propose the follow revamped god bessing mechanism (i'll leave the wrath events as they presently are):

- 3 diffent types of blessing events: minor blessing, a blessing and major blessing;

- The minor blessing is triggerd when gods are 'charmed', a blessing when 'delighted' and a major blessing when 'exalted';

- Depending on the type of festival, the effect on gods is limited: small festivals only satisfy gods till 'charmed' state, large festivals till 'delighted' state and grand festivals till 'exalted' state;

- I leave some exemples of blessings:
![Blessings](https://user-images.githubusercontent.com/64329357/83566023-41809c80-a517-11ea-8a90-704d02cb8586.jpg)

- Besides denarii, wine is needed for throwing a grand festival. I propose to change the comodity and the requirements. The comodity other then wine (grain, fish, etc.) should be its equivalent net price (ex: 1 wine = 160 dn ~ 6 wheat = 168 dn)

![Major blessing cryteria](https://user-images.githubusercontent.com/64329357/83572772-12235d00-a522-11ea-89ec-8c0268b94031.jpg)

Tell me your opinion about it, please.

**Comment by crudelios** [comment]
This is now redundant with the religion update, so I'm closing it.
