### ISSUE TITLE
Inconsistancies & Other Cool Stuff

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#37]
First of all, i'm having a blast with the Augustus Mod 1.31. Congrats!

On the Valentia Mission, we can produce wine (only one type, i guess). 

So, to build a Luxury Palace from a Grand Villa, we must import a second type of wine from Carthago Nova. As the game does not allow to import & export at the same time, we must import wine and stop export our own. This is  inconsistent, on my opinion.

So, instead of a second type of wine, i suggest a WONDER like a Triumphal Arch, for exemple. Since this monument is only buildable as gift from Caesar (free of charge after our army victory abroad),  in the other circunstances we could also build one as long as we acchive 100% favor rating & at a huge cost - denarius and marble, for exemple.

![Triumphal Arch](https://user-images.githubusercontent.com/64329357/80849280-6af39300-8c0e-11ea-884a-7a665f59b5fa.jpg)

OTHER COOL STUFF

Gardens: i remender back from Caesar 3 demo, that the gardens were much cooler then the actual full game. Maybe you could add it as a new feature. I think there's no copyright issue.

![Gardens](https://user-images.githubusercontent.com/64329357/80850849-12c08f00-8c16-11ea-950a-158a817bd64f.jpg)

Colored Overlay: the colums from the caesar 3 demo are much cooler then the actual game, don't you think?
 
![Overlay](https://user-images.githubusercontent.com/64329357/80850961-a5612e00-8c16-11ea-92ec-65a4638a26d3.jpg)

**Comment by Legionary2** [comment]
There will be a new option - so long as the route is open for the second type of wine , it counts as two and you can still export wine

**Comment by Legionary2** [comment]
I do like color columns but unsure what keriew would like to do with it. Also triumphal arches will be a monument style building and no longer tied to distant battles. Victory Trajan columns will probably replace the old triumphal all arch system.

**Comment by arkimedes1967** [comment]
Cool, can't wait to play it!

**Comment by constant-current** [comment]
> The gardens above are from C3 demo, is there any copyright issue?

Sure there is. Since they are not opensource or public domain graphics, those can't be embedded in Augustus and they will require a manual file copy from a previous C3demo installation.
IMHO, this old demo design is more repetitive and does not look nice in a large scale. The 4x4 tile really shows its limitation. Finally, this demo garden design can visually be confused with normal trees in a northern province climate.

**Comment by arkimedes1967** [comment]
I found another inconsistence: the native trader.

I seems that he only starts to trade with us as long we open a trade route in the empire map with... another city. 

I think it's more logic that the "trigger" to trade should only be: romanized by a mission post and orders to export by the trader adviser.

**Comment by crudelios** [comment]
I think most of these issues have been addressed, right?

**Comment by arkimedes1967** [comment]
Yes, may can close this thread, thank you.
