### ISSUE TITLE
Rotate Building Option

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#38]
Will you consider including a rotate (R) building option on C3?

![Circus](https://user-images.githubusercontent.com/64329357/81198778-c54b7580-8fb9-11ea-9890-bebf91b044d3.gif)

The objects may flip horizontally and, particularlly the Circus, could be very usefull to fit (this large object) on the map.

It's possible to rotate de building but not the map?

**Comment by arkimedes1967** [comment]
The bath on C3 is composed by 10 different images that, in sequence, become an animated gif.

Is it possible to apply on Augustus a rotate option (horizontal flip) using one single animated imagem like the bath below?

![Bath](https://user-images.githubusercontent.com/64329357/83959359-23e36800-a874-11ea-9163-efb1de3ee305.gif)     ![Bath Rotate](https://user-images.githubusercontent.com/64329357/83959364-2b0a7600-a874-11ea-9f48-7ff55985f1c0.gif)

The rotate image option (horizontal flip) makes more sense if the image isn't a perfect square like the circus or the troops fort - to fit on a nerrow space.

If you think about it, gatehouses and Triumphal Arch already rotate by default every 2 seconds.

I'm still struggling with the 2 racers images on the circus...

**Comment by Keriew** [comment]
Added.
