### ISSUE TITLE
Entertainment Lacking - Brundisium

### ISSUE THREAD

**Issue by AlexDenthanor** [Keriew/augustus#384]
There never seems to be enough entertainment for the city, this prevents immigration and it makes the people unhappy. I have only a little over 500 people. I have more than enough theatres. Is this due to the fact there are more entertainment venues and this has changed the entertainment value, just like in an old Pharaoh mission that cannot be beaten because the addition of the Zoo in Cleopatra changed the entertainment values?

[save and ini.zip](https://github.com/Keriew/augustus/files/6497142/save.and.ini.zip)

**Comment by crudelios** [comment]
You need to provide pottery to your city for the immigrants to return, it's a scenario specific thing.
