### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by lionirdeadman** [Keriew/augustus#389]
Would you like to ship Augustus as a flatpak package and ship it on [flathub.org](https://flathub.org/home)?

**Comment by crudelios** [comment]
Humm. We are already providing an appimage and outside communities have been creating proper packages for their environment (aur, deb, etc).

I may be mistaken but I even think someone created a flatpak image for v2.0.1.

Since no one here is really familiar with flatpak, we'd be glad to have someone step in and help us with that.

**Comment by crudelios** [comment]
@lionirdeadman Thanks for the package! It's there anything on our end we need to do now, or is this fixed?

**Comment by lionirdeadman** [comment]
Ah, sorry I forgot to say something here, haha.

There could be information about it in the README and I could automate it so a bot would create a Merge request in the Flathub repository to remind you and make maintaining it a bit easier.

**Comment by crudelios** [comment]
If you could automate it, that would be great, thanks!

**Comment by lionirdeadman** [comment]
Did the auto-pr thing with https://github.com/flathub/com.github.keriew.augustus/commit/6874956cf4772922caca20c507a55654d5541835

**Comment by crudelios** [comment]
Nice! That means when we launch a new release the package will be automatically created with no input on our end, right?

**Comment by lionirdeadman** [comment]
Sorry, I've been taking things relax lately. Not quite, it means that @FlathubBot will make a PR to the https://github.com/flathub/com.github.keriew.augustus repository that someone can merge (after testing that it works). This behaviour can be made fully automatic but I don't think it'd be appropriate as releases are not time sensitive and you likely want to test it works.

**Comment by crudelios** [comment]
I agree,  if should be checked beforehand.

Thanks a lot for your effort! I'm going to close this now 👍
