### ISSUE TITLE
Invisible Mouse Pointer on aarch64 soc device

### ISSUE THREAD

**Issue by Cebion** [Keriew/augustus#390]
Greetings,

first of all thanks for this wonderful port.

I've built Augustus for use on a linux portable handheld on armv8 aarch64 basis.
It works very well but the mouse pointer is completely invisible. 

Even with a real mouse connected the issue persists.

I've looked into the code but couldn't find any culprit.

Have you experienced this behavior before?

Thanks in advance.

**Comment by crudelios** [comment]
This probably is due to a lack of mouse cursor support from SDL.

You can hard-fix it by adding a `#define PLATFORM_USE_SOFTWARE_CURSOR` in `src/input/cursor.h`.

**Comment by crudelios** [comment]
@Cebion Did my answer help you fix it? Thanks.

**Comment by Cebion** [comment]
Thank you very much! This helped yes.
