### ISSUE TITLE
Mouse pointer jumps on click

### ISSUE THREAD

**Issue by jakelooker** [Keriew/augustus#398]
The game seems to lose track of my cursor causing me to miss click on menu items. As soon as I click the mouse button the cursor jumps to it's true location, often on the button next to the one I intended to click on.

I'm using the touchpad on my thinkpad with the external left click button (so it's not the touchpad incorrectly registering movement). The same issue occurs with the trackpoint too.

I am using Arch running SwayWM with Wayland. I have tried disabling the mouse acceleration I applied but this did not change it.

It only seems to happen with the top two rows of the building buttons.

Hopefully I've made the issue clear, happy to do any testing to help you track this down.

**Comment by crudelios** [comment]
First possible solution: try disabling right click to drag the map
Second solution: it's possible your trackpad is registering both as a mouse and a touch device. I know this happens on apple devices. Maybe there's a touchpad setting you could change to fix that?

**Comment by crudelios** [comment]
@jakelooker Did any of my suggestions help you fix this issue?

**Comment by crudelios** [comment]
Since there were no developments, I'm closing this. Let me know if this isn't fixed yet.
