### ISSUE TITLE
Small mausoleum construction

### ISSUE THREAD

**Issue by Azoku** [Keriew/augustus#405]
Construction of some of small mausoleums never completes even though the they look built. I have experienced the issue on multiple maps. Please see the image attached.
![city 2021-05-24 20 34 59](https://user-images.githubusercontent.com/84738454/119392209-271b7200-bcd8-11eb-92d0-1f2bccc8386a.png)

**Comment by Keriew** [comment]
Thank you for the report. Fixed in a3ccfe6, you can download the latest unstable to not experience the problem.
