### ISSUE TITLE
Show lararium, nymphaeum and mausoleums in religion tab

### ISSUE THREAD

**Issue by brainwad** [Keriew/augustus#407]
The new religious buildings added in v3 are not displayed in the religion tab.

I would suggest counting the nymphaeum as a "large" oracle, and the small and large mausoleum as small/large oracle (since they have the same effect on the gods). A separate line item is probably necessary for the larariums.

**Comment by brainwad** [comment]
Counting the Nymphaeum/Large Mausoleum as large oracle will clash slightly with the Pantheon, but only in exactly the way that the Grand Temples already do.

**Comment by Keriew** [comment]
Thanks for the suggestion! Implemented in fc61b7b and bb20198.
