### ISSUE TITLE
Oracle bonus before completion of its construction

### ISSUE THREAD

**Issue by Azoku** [Keriew/augustus#413]
When I placed an oracle, I get its benefits (e.g better relations with gods, desirability etc.) before its construction is complete. It can also seen in the advisor window that there is an oracle in the city even though the construction is not finished. This issue may apply to other oracles (i.e. nymphaeum and mausoleums) and large temples.

**Comment by Keriew** [comment]
Thanks for the report!
Fixed in 5fa149d. Download the latest unstable version if you want to play with it fixed before the next release.
