### ISSUE TITLE
Gladiator schools don't send entertainers to the colosseum

### ISSUE THREAD

**Issue by blubb975** [Keriew/augustus#417]
When having a block containing an amphitheater, arena and colosseum, the gladiator schools send most of their entertainers to the arena, the amphitheater gets a sporadic supply (often runs out), and the colosseum never gets any. I've tried with anything from one to six gladiator schools on that block.

On this particular map I already had medium palaces before I built the colosseum and hippodrome, finishing the colosseum and having it supplied with animals only didn't even evolve them (entertainment boost too low?)

To my knowledge the way it is determined how the entertainer schools supply to the venues had already been kind of wonky in vanilla C3 (upon spawning a walker it seems to look up which of the venues in reach will run out of shows next *at that exact time*, no matter if the school had already sent the previous walker to that very venue but that previous walker is still underway so he doesn't count - leading to multiple walkers being sent to the same venue in succession, with another venue only being picked after the first walker has reached the first venue, which can be problematic in longer forced walker blocks)

Possible suggestions:
- Make it so that the entertainer school always strictly alternates, so if it has for example 3 possible destinations on the same road network, the first walker spawned goes to venue 1, the second to 2, the third to 3, the fourth to 1 and so on
- Make it a possibility to restrict the type of venue a school can send its walkers to. So if things go wrong you could build three gladiator schools and have them dedicated to amphitheater, arena and colosseum each

The block in question is on the southeastern side of the map

[gladiators.zip](https://github.com/Keriew/augustus/files/6596936/gladiators.zip)

**Comment by crudelios** [comment]
This should be fixed on the latest unstable, please check.

**Comment by crudelios** [comment]
@blubb975 Can you confirm it's fixed so I can close this? Thanks.

**Comment by blubb975** [comment]
It's definitely better now, the colosseum and arena get supplied. Amphitheater still sometimes runs out though

**Comment by crudelios** [comment]
It seems that the running out is likely normal behaviour. Schools have always been fiddly anyway.

I'm closing this, let me know if you find any abnormal behaviour.
