### ISSUE TITLE
Missing assets (despite folder being present)

### ISSUE THREAD

**Issue by nickgeorge** [Keriew/augustus#430]
Just downloaded zip and moved into my Steam Caesar3/C3 directory, and get the following message: 
`The extra Augustus assets could not be loaded.  This can be do to a missing or old assets directory.`
etc.

This is using 3.0.1 Augustus on a steam install.

**Comment by nickgeorge** [comment]
Seems I had to copy the assets directory out of the augustus directory and into the C3 directory.  Might be worth mentioning this in the readme.

**Comment by crudelios** [comment]
This will be changed for 3.0.2, allowing you to keep the assets in the augustus directory instead of the C3 directory.

**Comment by zuckerruebe** [comment]
I think the point about mentioning assets (at all) in the README or anywhere is still valid. I couldn't find any place mentioning these asserts nor where to find them except in this and a couple of other issues...

**Comment by zuckerruebe** [comment]
Never mind, I think my issues was that there's currently something wrong with the assets on master (I was building from source) and I got confused the the error message box.
