### ISSUE TITLE
If houses forage, only a devolve warning displays

### ISSUE THREAD

**Issue by cdsmith-umn** [Keriew/augustus#44]
When a house that normally requires food from a market is set to forage, then when you right-click on it to check what it requires to evolve, you will see only the message that the house will soon devolve because it requires food from a market. This will persist until the house has reached an evolution that is one step below an evolution that does require food from a market.

Steps to reproduce:

1. Edit c3_model.txt by setting the flag for "Requires food from a market" for "House 3" and "House 4" to zero. This changes the residents into foragers.
2. Start the game and create housing plots.
3. Place a well.
4. Do not place a market, any temples, or any form of entertainment.
5. Once the house has evolved twice, right click on it. (It should not be capable of evolving into "House 4".)
6. Observe that it displays a message stating the house will soon devolve as it has not received any food from a market.
7. Observe that it also does not display the requirements necessary to cause the house to evolve further.

Expected behaviour:
When right-clicking on the house, it should display information telling the player what is required to cause the house to evolve.

I started playing C3 again after 10 years away from it, and I only discovered this project (and the one by bvschaik) this past Monday. Due to the difficulty I had in creating cities with effective walker paths, I had reduced the food requirements for my houses. I started using the Augustus executable yesterday and noticed this bug. I have since reverted to a vanilla/default c3_model.txt because the improvements you've made in this project has allowed me to solve the problems I was having with walker routing and resource availability.

Unrelated to the bug, I would just like to say how much more fun I had playing Augustus than playing the original C3. I really appreciate the work you all have done on this!

**Comment by cdsmith-umn** [comment]
@Keriew If you want to close this issue, that would be fine with me. This will only be an issue for people who continue to play with a heavily modified c3_model.txt. Once those people get used to using roadblocks, I can't really see them continuing to use a heavily modified model file. I, personally, do not expect this to ever be fixed because it is very much an edge case. I mainly wanted to create the issue so that it was logged in case anyone else experiences this.

**Comment by Keriew** [comment]
I intend to fix this at some point, but it's a very low priority issue and I'm trying to fix the bugs, tie things up and get the new release out soon. I'll get back to working on things unreleated to logistics once that's done.

**Comment by cdsmith-umn** [comment]
OK. That sounds good. I think it's something that should probably be fixed when there's nothing left to fix. :smile:

**Comment by crudelios** [comment]
@cdsmith-umn This should be fixed on the latest `release` branch.

Can you test, please? [Here's a link to a build with the fix](https://ci.appveyor.com/project/Keriew/augustus/builds/37949836/job/ochu45pmjou7ok2q/artifacts)

You can ignore the assets missing if you don't want to update them.

**Comment by crudelios** [comment]
Since there has been no answer and I did fix this, I'm closing this issue.

**Comment by cdsmith-umn** [comment]
@crudelios Sorry. I just haven't had time to play in a while. Life's gotten busy and pulled me in other directions. Thank you for fixing it, even though it's very much an edge case.

**Comment by crudelios** [comment]
@cdsmith-umn No problem, I just don't like having issues hanging and since it was fixed anyway I decided to close it.
