### ISSUE TITLE
Crash occurred

### ISSUE THREAD

**Issue by ChunGilLee** [Keriew/augustus#444]
I don't know what my behavior causes a crash. But, the crash occurred. Following are messages when the crash occurred.

ERROR: Oops, crashed with signal 11 :(
INFO:   ./augustus-3.0.1-linux.AppImage(backtrace_print+0x29) [0x43a249]
INFO:   ./augustus-3.0.1-linux.AppImage() [0x436d09]
INFO:   /lib/x86_64-linux-gnu/libc.so.6(+0x3efd0) [0x7f7b0bbacfd0]
INFO:   ./augustus-3.0.1-linux.AppImage() [0x449bea]
INFO:   ./augustus-3.0.1-linux.AppImage(building_update_state+0xb0) [0x44ac60]
INFO:   ./augustus-3.0.1-linux.AppImage() [0x452a2c]
INFO:   ./augustus-3.0.1-linux.AppImage(building_construction_clear_land+0x1b1) [0x452da1]
INFO:   ./augustus-3.0.1-linux.AppImage(building_construction_place+0x36e) [0x44f00e]
INFO:   ./augustus-3.0.1-linux.AppImage(widget_city_handle_input+0x55f) [0x4ea93f]
INFO:   ./augustus-3.0.1-linux.AppImage(window_draw+0x73) [0x4e9143]
INFO:   ./augustus-3.0.1-linux.AppImage(game_draw+0xb) [0x4b348b]
INFO:   ./augustus-3.0.1-linux.AppImage(main+0x236) [0x4361b6]
INFO:   /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f7b0bb8fb97]
INFO:   ./augustus-3.0.1-linux.AppImage(_start+0x29) [0x436879]

Rex.

**Comment by crudelios** [comment]
Hi,

From your crash report it seems your were deleting something when the crash occurred.

Can you please provide the city file and tell us what you were deleting?

Thanks!

**Comment by crudelios** [comment]
Due to the lack of activity I'll be closing this issue.
