### ISSUE TITLE
Granary pushers bug

### ISSUE THREAD

**Issue by alex-triphonov** [Keriew/augustus#453]
Hi there, I found an interesting bug with granaries:
It produces multiple pushers that dissaperar after few times passed.  All pushers on screenshot are from granary above them and will disappear right before road block(not related).
I can drop you save game if you tell me where should I upload it.
https://i.postimg.cc/L6t4D5k0/bug.jpg

**Comment by Keriew** [comment]
Can you upload it here?

**Comment by alex-triphonov** [comment]
[pusher bug.zip](https://github.com/Keriew/augustus/files/6834695/pusher.bug.zip)
never realized you can upload files here..

**Comment by Keriew** [comment]
Thanks, fixed in 515a557.
