### ISSUE TITLE
Vacant log with Pantheon access + house evolution bonus cause crash

### ISSUE THREAD

**Issue by nishantjr** [Keriew/augustus#456]
Built from latest master: bb20198c

Save [attached](https://github.com/Keriew/augustus/files/6842154/save.zip)

**Comment by Keriew** [comment]
Hey, thanks for the report! I can't reproduce the crash (possibly due to different layout of memory due to the compiler), but I found a couple of regions that could be causing a problem and fixed them in 45dc821. Could you check if the crashing is fixed?

**Comment by nishantjr** [comment]
Perfect! This fixes the crash. Thanks
