### ISSUE TITLE
android select directory button doesn't work

### ISSUE THREAD

**Issue by danzoo** [Keriew/augustus#457]
![save](https://user-images.githubusercontent.com/25403330/126429062-eaf4901a-b078-421f-8c35-e5ae9afeac9e.gif)
select directory button doesn't work. android version : 11

**Comment by crudelios** [comment]
The "select directory" is known to not work on some specific android versions, like miui, because those don't use the standard android api.

If you're using miui, I'm afraid this will not be fixed. If not, what's your phone model?

**Comment by crudelios** [comment]
Due to the lack of activity I'll be closing this issue.
