### ISSUE TITLE
Suggestion: Especialized Docks & Warehouses

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#46]
Issue:

- I believe the option "Become the trade center" on warehouses is pratically useless because traders tend to ignore this priority, buying firstly from other warehouses;

Suggestion: 

- When using "become the trade center" option it should be possible to choose what product to export, as a dedicated warehouse, making sure traders buy firstly (& exclusivly??) from it. This way, we could have multiple dedicated trade centers, each to its product/export.

Issue:

- With multiple docks, traders offten choose the farest dock to buy an export instead of a free and dedicated dock near its local prodution;

Suggestion:

- As suggested above about warehouses, it should be possible to choose what product/export is that dock dedicated, been the first place traders look for to buy it.

Please tell me what's your opinion & if it's worth to implement.

**Comment by Keriew** [comment]
Not sure if you've been tracking the additions to the code, but I've added finer control over traders and trading ships. This, along with partial warehouse controls should allow you to control where trade is happening.

![warehousecontrol](https://user-images.githubusercontent.com/59965174/83507253-9812ba00-a4c8-11ea-831c-bbd793c84029.png)

Do you think this is enough?

**Comment by constant-current** [comment]
> As suggested above about warehouses, it should be possible to choose what product/export is that dock dedicated, been the first place traders look for to buy it.

Not bad but the first problem is that the ship traders don't behave like caravan merchants and don't go to the dock where there is the type of goods they still have quotas to buy. Making them as smart as their ground counterparts will already avoid a lot of workaround like "getting goods" orders or like dockers pushing carts all around the city next to the unused dock when the two are road connected.

**Comment by Keriew** [comment]
Right, that works fine for traders but docks need some more control. I'll try experimenting with some ideas and see what works.

**Comment by arkimedes1967** [comment]
> Not sure if you've been tracking the additions to the code (...)

Anxiously..., but didn't track this one.

> Do you think this is enough?

Your solution fixes an annoing knowned problem concerning traders that buy from warehouses 'assigned' to markets/housing block that offten lead to a devolve housing problem. Thank you!

But, the dock issue still remains. May you consider a possibility of assigning a dock to a especific trader/city? Combined with your improved warehouse it would be perfect.

**Comment by Keriew** [comment]
![docks](https://user-images.githubusercontent.com/59965174/83536338-5e0add80-a4f3-11ea-8b15-21d00f468ed0.png)

Added dock special orders - a ship won't go to a dock unless that dock accepts all the goods that the ship trades. That should solve the issue.

**Comment by arkimedes1967** [comment]
May i propose an alternative?

The problem with dock ins't the product (like you solution points out) but the local to trade it. So, i propose a both generic or assign dock  to a trade city.

1. Click on the world map (top right);
2. Choose the sea trader city symbol;
3. Close worl map;
4. The dock is now assign to Miletus.

![Militus Trading Dock](https://user-images.githubusercontent.com/64329357/83600268-1f623b00-a566-11ea-81eb-dd05a811f884.gif)

To return to a generic dock:

1. Click on the world map
2. Choose our city symbol
3. Close world map
4. The dock is now a generic one
