### ISSUE TITLE
Warehouse/Granary "get" orders

### ISSUE THREAD

**Issue by cdsmith-umn** [Keriew/augustus#48]
I'm not sure whether this is a bug. To me, it is, but there may be some technical reason that the game cannot behave in the way that I would like.

When warehouses and granaries are set to "get" a product or food, they will not retrieve them from other warehouses and granaries that are set to "get" that same product or food. This makes it difficult to "chain" warehouses and granaries in order to smoothly move products and foods across the city. 

![Londinium_resized](https://user-images.githubusercontent.com/9805709/83545291-a19a2300-a4c4-11ea-8b5e-54c084399949.png)

Let's look at Londinium that I just finished today for examples.

On the Western side of the map, there are 10 warehouses grouped together. All the warehouses, except the ones with timber in them and the one with only wine in it, were set to get olive oil. The warehouse with only wine in it was initially set to also get oil, but I changed it to "accept" in order to make its oil available to other warehouses in the city. Of course, doing that there is no way to replenish its supply of oil since the dockers will drop it (properly) into the nearest accepting warehouse. In the NE corner of the map, there are two housing blocks of Grand Insulae. I had difficulty keeping their markets stocked with oil because the warehouses near them would not get oil from the other warehouses because those other warehouses were set to "get" oil, too. This meant that those warehouses' cart pushers had to go all the way to the dockside warehouse to get oil.

The granaries on this map are another excellent example. On the far Eastern edge of the city, there are eight granaries. They are all set to get wheat. On the other side of that housing block, there are more granaries. Some are set to get wheat, while others are set to get vegetables. The Eastern-most set of granaries will always go to the granaries nearest the farms to get their wheat, even though they should be able to get wheat from the granaries that are nearest to them. In order to get those houses to evolve, I had to build the far Eastern granaries before putting houses into place there. Once they were full, I put down markets, prefectures, and engineer's posts. After the market ladies had picked up some food, then I put down the houses and let people move in. This was the only way I could ensure those houses had a stable supply of food. This is also the reason for the large number of granaries on the Western side of the city (on the East side of my palace blocks).

I would like to be able to move goods and foods across the city by having each granary or warehouse get goods and foods from the next nearest granary or warehouse that has that good or food, without regard for whether the building is set to "get" or "accept". Is this possible?

**Comment by cdsmith-umn** [comment]
I have also noticed that ships and traders (the guys on donkeys) won't sell you any goods if you have 12 or more of that good in a warehouse. This makes it difficult to develop a supply of a good, such as oil, across the different housing blocks that demand that good.

**Comment by Keriew** [comment]
It's not a bug, it's a design choice. The problem, with storage buildings getting from other storage buildings would be situations like this:
`A--------B--C` 

Where A is accepting warehouse and B and C are getting granaries. Right now, both B and C will go get goods from A, while if they would be getting from other getting warehouses, they would just keep moving it back and forth between themselves. This seems to be intended way of transporting goods in Caesar 3 - accept goods where they are produced, get them where they are needed. In practice, long range transport of goods doesn't work all that well, and even medium range transport of food is pretty challenging, considering the volume of food needed.

New version of Augustus add a few options that will help the long distance transport of food, but it's still going to remain somewhat tricky.

Regarding trade, traders have their own logic limiting how many goods you can buy, depending on the type of good, city population and the number of workshops. This has already been changed in f0d835e but still unreleased. Which allows you to specify how much you want to import.

**Comment by cdsmith-umn** [comment]
@Keriew Thank you for the explanation. I can see that changing how granaries and warehouses get foods and goods would require substantial re-work to prevent the situation you describe. To my mind, it would essentially require adding the ability to tell each granary and warehouse from where they should be getting their goods and foods. That way, you could tell C to get from B, and B to get from A. I cannot imagine the amount of work required to code that, to say nothing of the UI changes this would require.

I consider this matter closed and am closing this issue.
