### ISSUE TITLE
Unclearable tiles are highlited in red when hovering with Clear Land tool

### ISSUE THREAD

**Issue by Ouaz** [Keriew/augustus#482]
Hi,

In Julius, when selecting the _Clear Land_ tool, and drag-click on both clearable and unclearable tiles, unclearable tiles are not highlited:

![land_unclearable_julius](https://user-images.githubusercontent.com/11946570/132072926-cd3e330b-444e-4a30-95ff-ea2b17e9d980.png)

But in Augustus, when selecting the _Clear Land_ tool, and doing the same thing, all tiles are highlighted in red:

![unclearable_land_augustus](https://user-images.githubusercontent.com/11946570/132072796-32dec5aa-0df5-4786-a8c8-85becfccf476.png)

Julius behaviour is useful in some circumstances, e.g. when trying to wedge multiple buildings in a narrow space and... 
"Oh geez, 1 in 4 tile is not clearable! All my plans are screwed." ^^

(bug report fetched from [Joey Maximus on Caesar III Heaven forums](https://caesar3.heavengames.com/cgi-bin/caeforumscgi/display.cgi?action=st&fn=2&tn=7838&st=47#post48), thanks to him)

**Comment by crudelios** [comment]
The Julius behaviour is the buggy one actually, all tile should be highlighted in red. In fact if you grab the latest unstable of Julius you'll see that everything gets red again, because that's been fixed since Julius 1.6.0.

**Comment by Ouaz** [comment]
Oops, my bad, if "all tiles highlited in red" is considered as the normal behaviour.

But I admit I don't understand why, though. It makes sense to not have a red visual feedback, if a land is not clearable.

**Comment by crudelios** [comment]
The idea is to highlight the whole area that will be affected, regardless if there are things to clear or not. The water tiles get red too and most of them aren't clearable either.

**Comment by crudelios** [comment]
Since this isn't a bug per se, I'm closing the issue.
