### ISSUE TITLE
Side Bar with details dont show up - Augustus v3.0.1

### ISSUE THREAD

**Issue by Annut1234** [Keriew/augustus#485]
Ask your question here.
Hi,
I have 2 question:-

1. On the side bar with all the details of ratings etc, I only get 4 sets of information 
a. Game Speed
b. Unemployment
c. Invasion
d. Gods

None of the other information is displayed. Is it a setting ? I have deleted , downloaded everything from scratch twice. This just doesn't change. 

2. My exports don't max out in the middle of the game. I have tons of stuff in warehouses but just doesn't get max out. This is true for most maps, esp in the middle of the games, I am on Londinium and after 5000 Population, i have ran into money issues. Not the first time, over and over again..
Is it that I have to import stuff from other places and they will only then buy my stuff or any other bug? 
I heard GamerZakh once say in one of his videos that there is a limitation in this game as to how much money we can make, but he never explained or gave specifics... is that accurate? If so, can you please provide some trade guidelines. 

Thanks
Anurag

**Comment by crudelios** [comment]
Hi,

1. It has to do with your screen size. The game only displays the information that will fit on your game window. If you can't make the window any bigger you can alternatively reduce the game scale.
2. This is a known 3.0.1 issue that had been fixed on the unstable builds and will be fixed for the stable v3.1.

**Comment by Annut1234** [comment]
Thnaks... any time line for v3.1?

**Comment by crudelios** [comment]
It's almost ready, though it's been like this for almost a month.

If you don't want to wait you can download the latest unstable but you'll need to delete your assets folder and download the assets for the unstable version as well.
