### ISSUE TITLE
Minor: Games from Colosseum wrong Advisor selected

### ISSUE THREAD

**Issue by Riww** [Keriew/augustus#491]
When starting games from Colosseum, the last used advisor is highlighted (wrong, see picture, Ratings advisor makes no sense). Either the proper advisor shall be highlighted (Entertainment), or the whole advisor row should not be displayed, as it cannot be used anyway.
![003986](https://user-images.githubusercontent.com/74105140/134529384-66ac71b2-4081-4b95-963c-0f035a58ba6a.png)

**Comment by Keriew** [comment]
Thanks for the report, fixed in 97cac7c!
