### ISSUE TITLE
Warehouse Delivery Man isn't Efficient: Minimum Stock Is Too Low

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#50]
On the video below you can see the behavior of the delivery man from 2 warehouses:

- The first warehouse has 6 furnite, it's on **getting goods** ("H" - half)  mode and has enought space for 10 more;

- You can read the message "Our cart is here, waiting for new instructions";

- On the production site, the second warehouse has 15 furniture, it's on **Accepting** ("F - Full") mode. 

- They are both connected by a road.

- I could observe that the minimum stock for the delivery man effectivelly getting goods is 4 furniture;

- If a cart gets a maximum of 4 furniture on each travel, on my opinion, the minimum stock (trigger for effectivelly getting goods) should be:  Max alowed space - 4 = Minimum Stock (16 - 4 = 12). So, it should be 12 not 4;

- I'm aware of the next version of Augustus concerning this issue - getting double goods on each travel, but the problem remains: Max Alowed Space - 8 = Getting Goods (16 - 8 = 8). The minimum stock should be 8 (not 4) to effectivelly getting goods.

- The same logic goes to graneries. 

- The getting-double-goods option will be really needed by those warehouses/graneries which are too far from the prodution site, and aim to compensate the consuption of goods during the long cart travel.

![Warehouse](https://user-images.githubusercontent.com/64329357/83745265-303daa00-a655-11ea-9a23-9564cca7722c.gif)

**Comment by Keriew** [comment]
Fixed already in fda1695
