### ISSUE TITLE
Bug encountered says c3.eng or c3_mm.eng files not found or too large

### ISSUE THREAD

**Issue by cesarmarcanove** [Keriew/augustus#511]
The bug discovered in log:

INFO: Augustus version 3.0.1
INFO: Initializing SDL
INFO: SDL initialized
INFO: Loading game from working directory
INFO: No key found on layout for  [
INFO: No key found on layout for  ]
INFO: No key found on layout for  =
**ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.** << A bug???
INFO: Loading game from base path D:\GOG Games\augustus-3.0.1-windows\
INFO: No key found on layout for  [
INFO: No key found on layout for  ]
INFO: No key found on layout for  =
**ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.** << A bug???
INFO: Location:  C:\Users\**YOURUSERID**\AppData\Roaming\augustus\augustus\
INFO: Loading game from user pref D:\GOG Games\Caesar 3

The screenshot capture
In responding of loading the app augustus v3.01 and says these missing files:  **c3.eng** or **c3_mm.eng**
![bug-augustus-v301](https://user-images.githubusercontent.com/279859/140631197-69fa7b57-9395-4855-8b02-d1b507472bfd.jpg)

**Comment by crudelios** [comment]
That isn't a bug, the game searches for the C3  file data in many directories. In your case, it searched until it found them on `C:\Users\*YOURUSERID*\AppData\Roaming\augustus\augustus`.

What you're missing are the augustus new assets which don't come with the original C3 install.

When you downloaded augustus an extra `assets` folder was in the zip file.

You need to place that assets folder on `C:\Users\*YOURUSERID*\AppData\Roaming\augustus\augustus` for the extra assets to be found.

Version 3.1.0, which isn't yet released, will allow you to keep the assets folder where you installed `augustus.exe` removing the need for this step, but until then you must do the above step.

**Comment by cesarmarcanove** [comment]
Al right reason. 

I have downloaded version 3.0.1-284 (the nightly version) and it can be configured to release as version 3.0.2 as a hotfix if you want; because the additional data notice no longer appears (as seen in the test image that we uploaded) and they have a lot of improvement than version 3.0.1 (the stable version), and from there some few bugs were found in the part of the assets folder, because it looked very strange in the stable version, I played the game once I put a missing infrastructure such as the roadblock, tavern, theater, etc. 

Because with version 3.0.1-284 (the nightly version) the notice of additional data files no longer appears as in the image, and bugs are no longer found. And now it can be released as stable version 3.0.2, as if it were a hotfix patch.

Congratulations on your project and follow many successes, and hopefully the new version 3.1 is released (based on the recent Julius v1.7.0)

**Comment by crudelios** [comment]
Thanks!

To get the assets working with the latest unstable, you need to download the latest unstable assets, delete the old assets folder and copy the new one. Simply overwriting the old assets folder won't be enough.

We've been meaning to release v3.1.0 for a few months now, but there's always something missing. Hopefully it'll be soon.
