### ISSUE TITLE
Workshop with 7 raw materials

### ISSUE THREAD

**Issue by crudelios** [Keriew/augustus#516]
### Discussed in https://github.com/Keriew/augustus/discussions/514

<div type='discussions-op-text'>

<sup>Originally posted by **catalin-duta** November  9, 2021</sup>
Is there any limitation, or any way to limit, the maximum number of raw materials that a workshop is storing?
I am building a Grand Temple which requires clay, at the same time the pottery industry needs some of the clay, so I would rather not stockpile.
Unfortunately, the cartmen are very adamant to only deliver clay to pottery workshops, and not at all fairly.
Some of my workshops have 1-2 stored clay, while I have workshops with 6 or even 7 clay stored.

Update: with stockpiling turned on, the warehouses closer to the GT and work camps are no longer Getting the clay.

And in the mean time, a Pottery Workshop across the street from 3 Clay Pits has 0 units stored, while another which is not that close to pits has 9 units stored.
Other workshops (Weapons, Oil) won't take more than 3 units each before the raw materials end up in warehouses.

It's a race against time for the Foreman to get to the clay faster than the warehouse can dispatch to the workshops.
</div>

**Comment by catalin-duta** [comment]
[6Lugdunum8Ah8.zip](https://github.com/Keriew/augustus/files/7504152/6Lugdunum8Ah8.zip)
Not finding exactly the save file with 9 units of clay in 1 workshop, but this is the general state.

The workshops in this area are generally overstocked with clay:
![Screenshot_20211109-130329747](https://user-images.githubusercontent.com/93785920/140913216-10932c72-5a1c-4954-9092-ee4e3ba1c175.jpg)
The lonely one here across from 3 pits is understocked:
![Screenshot_20211109-130341860](https://user-images.githubusercontent.com/93785920/140913280-d4d45121-4381-4616-9af3-ee8d2a5103cf.jpg)
On a sidenote, there is also one clay pit by the water here that never gets labor access, ever, while its neighbours are fine:
![Screenshot_20211109-130411543](https://user-images.githubusercontent.com/93785920/140913431-d5a05a61-27d9-4388-ada5-3fac1fb64754.jpg)

**Comment by catalin-duta** [comment]
Here a save file with 7 and 8 clay in workshops. It's the area from the first screenshot above, surrounded by mountains.
[6Lugdunum8Ah10.zip](https://github.com/Keriew/augustus/files/7504216/6Lugdunum8Ah10.zip)

**Comment by npliashechnikov** [comment]
I think I have created similar issue and it has been fixed: https://github.com/Keriew/augustus/issues/416

**Comment by catalin-duta** [comment]
crudelios also mentioned that in #514 but I was on a later build, so something is still off.
It might be that a warehouse is supplying clay to a workshop (on its own road network) when there is a workshop (somewhere, on a different road network) that does not have a full stock of clay?
Then again, the cart pusher in the screenshot is still there after many years, and when the city doesn't have separate road networks anymore.

**Comment by npliashechnikov** [comment]
In my experience with the 3.0, the cart pushers from the warehouses will supply the workshops indefinitely as long as there is road between the warehouse and workshop.
As long as the pit, workshop and warehouse aren't on the same road network, workshop wouldn't accept more than 2 or 3 units of clay from the pit. At least, I didn't encounter that in my playthroughs.

**Comment by catalin-duta** [comment]
I think this is the same as
https://github.com/bvschaik/julius/issues/527
A warehouse will send a worker out to deliver clay [on its own road network] whenever there is an understocked workshop [on any road network].

**Comment by crudelios** [comment]
@catalin-data exactly. 

I just had a look at the code and warehousemen will always select a workshop, even if it has more than enough goods. They only do that if every other workshop has enough goods though. In that case, it picks the closest one, so that one ends up having a disproportionately high number of raw materials.

**Comment by catalin-duta** [comment]
@crudelios so is there a way to improve the warehouse logic, in that it only checks understocked workshops on its own road network instead of the whole city?

**Comment by crudelios** [comment]
Yes it is. I'll do it ASAP.

**Comment by crudelios** [comment]
Right now the code is working properly.

The problem with the savefile is that the cartpusher for the pottery workshop south of the theatre was permanently stuck on a garden tile and the workshop got 13 resources before my code changes.

The new code I added yesterday will make the stuck cartpusher immediately move upon reloading the game, therefore making its workshop work again and consume the raw materials.

Hopefully with that, everything gets fixed. Please let me know.

**Comment by catalin-duta** [comment]
The cartpusher did indeed move and the workshop has started working again.
But workshops are still being overstocked, with even 8 units of clay each, in the same area from the very first screenshot.
Warehouses are not an issue (they actually barely have any clay now), and anyway there is just 1 road network in the city now.
But I see cartpushers from clay pits coming in groups of 3-4-5 delivering to the same workshop.
Any thoughts?

**Comment by crudelios** [comment]
Yes, they all appear at the same time and at the moment they spawn they find what the workshop with the least amount of raw materials is, which will be the same if they are close by. So they all go to it and likely the cartpushers are so close to each other that they don't have time to update they destination before they reach the original workshop.

**Comment by catalin-duta** [comment]
So cartpushers from raw materials to workshops can also recalculate their destination while on the trip? The 6 workshops in the problem area are about 20 road tiles away from the closest 2 clay pits; rest of the clay pits in the city are at least 30+ tiles away, mostly in groups of 2 pits. How often approximately would they update their destination?

**Comment by crudelios** [comment]
Yes, they do recalculate. They do so every 120 in-game ticks, which is every 2 seconds at 100% game speed.

**Comment by catalin-duta** [comment]
So assuming 1 tile in 15 ticks, they should recalculate roughly every 8 tiles travelled.
Given the distances from the 6 workshops to clay pits (2 at around 20 tiles, rest at 30+), they should get a chance to recalculate at least 2 times, right?

**Comment by crudelios** [comment]
Exactly.

**Comment by crudelios** [comment]
@catalin-duta Is everything working fine regarding this issue now?

**Comment by catalin-duta** [comment]
@crudelios It seemed fine (or at least better) last time I got the chance to test. My old saves might have been affected by something else as well, with new games resource allocation has seemed more balanced.

**Comment by crudelios** [comment]
Glad to hear! I'll close this then.
