### ISSUE TITLE
Minor Glitch on Warehouse & Conflict of Orders

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#52]
There's a minor glitch on the warehouse delivery man when "Try to send goods elsewere" is active, and there's no espace to deliver the goods. He flashes continueslly as you can see on the gif below.

![Warehouse Flashes](https://user-images.githubusercontent.com/64329357/83898985-99094d00-a74f-11ea-8e25-c99d158663e0.gif)

Also, it seams to be a conflict of orders when we try to send the goods elsewere and the instruction to getting goods is also active. The deliverly man seams trying to do both: he gets goods and send them elsewere.

It would help if the instructions of the warehouse change automatically to "Not accepting" when the "try to send goods elsewere" is selected.

![Warehouse](https://user-images.githubusercontent.com/64329357/83899046-b211fe00-a74f-11ea-926f-ad26a7f7436c.jpg)

**Comment by Keriew** [comment]
Could you describe the problem?

**Comment by arkimedes1967** [comment]
Sorry, i edited before complete.

**Comment by Keriew** [comment]
Yes, there are a bunch of cases where cartpushers are assigned a task without checking if that task if possible/reachable. 

I'll get around at some point to fixing this

**Comment by crudelios** [comment]
@Keriew is this fixed now?

**Comment by Keriew** [comment]
Fixed with 6d09ed4
