### ISSUE TITLE
Land trade policy - multiple?

### ISSUE THREAD

**Issue by crudelios** [Keriew/augustus#525]
### Discussed in https://github.com/Keriew/augustus/discussions/522

<div type='discussions-op-text'>

<sup>Originally posted by **catalin-duta** November 11, 2021</sup>
![Screenshot_20211111-173012321](https://user-images.githubusercontent.com/93785920/141324791-d89ae4c5-98a2-4ccc-bee4-1d3726a58622.jpg)

In the above screenshot there are two things that seem contradictory to me:
- policy Consilium venditor terrae, so exports earn +20%
- capacity 12 units used, implying policy Consilium quantitas terrae

I should note that the Caravanserai was built, policy Venditor was set, then it was demolished and rebuilt. But the policy was never on Quantitas.
And as I understand, only 1 should be active at any given time.</div>

Savefile: [6Lugdunum8Ah21ltp.zip](https://github.com/Keriew/augustus/files/7521692/6Lugdunum8Ah21ltp.zip)

**Comment by dvincent56** [comment]
I will check asap

**Comment by dvincent56** [comment]
@catalin-duta
You have a Mercury Grand Temple active, so you have the temple bonus too.
Base is 8 goods.
Mercury temple is +50% => 8 + 4 = 12 goods

All is ok, there is no bug
If you select land trade policy Quantitas in caravanserai, you will add 4 more goods to 16 units(max)

**Comment by catalin-duta** [comment]
You're right. Going back through saves, the change in quantity starts applying after the Mercury GT is finished.
Truth is, for lack of information (I haven't seen that in the manual) I'm not familiar with the base bonuses of GTs, and I've only found a list of Epithets online.

**Comment by crudelios** [comment]
Ok, marking as not a bug, but we definitely need to merge the manual.
