### ISSUE TITLE
Name conflicts with Julius

### ISSUE THREAD

**Issue by mase76** [Keriew/augustus#53]
Hi!
I packaged version 1.4.0 for my Debian system today. However the desktop filename is still for julius and also tries to launch the julius executable, instead of augustus. Also the icons are named for julius. This would make conflicts when trying to install julius next to augustus. Maybe you want to completely use the augustus namescheme, even for the assets folder.

**Comment by Keriew** [comment]
That's a good idea, I'll get around to fixing it.

**Comment by Keriew** [comment]
Should be fixed with 6f2370d
