### ISSUE TITLE
Building on Visual Studio 2019

### ISSUE THREAD

**Issue by invasionofsmallcubes** [Keriew/augustus#535]
Hi,
I wonder if you could help me. I'm trying to build the game on Visual Studio following the guide on [julius](https://github.com/bvschaik/julius/wiki/Building-for-Windows).

Problem is at the steps that says: `Build → Build All`. Unfortunately I don't see any errors but the exe is not generated.

What I see is:

```
>------ Build started: Project: CMakeLists, Configuration: Debug ------
  [0/2] Re-checking globbed directories...
  ninja: no work to do.

Build succeeded.
```

What do you think am I doing wrong? I can also attach the screens if you need.

Thank you.

**Comment by crudelios** [comment]
That means the code was already built before, so there's nothing to build again.

If you go to `<augustus_repository_folder>\out\build\x64-Debug`, the exe should be there.

**Comment by invasionofsmallcubes** [comment]
For some reason the out dir was not showing on Visual Studio so I thought it wasn't there but from the file explorer is there. Thanks

**Comment by crudelios** [comment]
Yes, the out dir is ignored on visual studio to prevent cluttering. You can also press `F5` or `Debug` to start the exe directly from visual studio, but don't forget to add the dlls first.
