### ISSUE TITLE
Sea Traders Stoped Visiting the City

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#54]
Please exclude this thread.

**Comment by crudelios** [comment]
I think you need to accept both clay and marble at the same dock, that's how it works right now.

**Comment by Keriew** [comment]
The way it works is that ship checks all the docks if they accept all the goods it trade, in this case Wheat, clay, fish and marble. If the dock doesn't accept all of these, a ship won't dock there.

There's a room for improvement here.

**Comment by arkimedes1967** [comment]
Is it possible to include also an exception to dock cartpushers for retrievig more then 2 units each per travel (a total of 6 because dock releases 3) when the distance to the warehouse is more then 60 road tiles?

See imagem below. 

This is Cesarea mission: the distance by road is 76 road tiles (red line) and, even in strait line, the distance is 66 tiles (green line).

![City View 2](https://user-images.githubusercontent.com/64329357/83970339-27efa400-a8cd-11ea-91cf-3d54c7878ebc.jpg)

PS: the dock works fine when we accept all tradable goods of that particular sea trader.

**Comment by Himeko7** [comment]
I had the same issue in a mission, all dock settings were correct. Deleting and remaking the docks fixed it.
