### ISSUE TITLE
Trojan alert when I click to download Augustus 3.1

### ISSUE THREAD

**Issue by GloriusBasterd** [Keriew/augustus#542]
Is this a problem on my end (false positive or something else) or is the link really corrupted?

**Comment by crudelios** [comment]
Where are you downloading from?

**Comment by GloriusBasterd** [comment]
From here - the download section. I get the alert for every system, not just Windows.

**Comment by crudelios** [comment]
It's a false positive then - the downloads come from my own personal server.

Most likely your AV is being overly protective, because it doesn't know the download address. (After all, it's a personal server)

**Comment by GloriusBasterd** [comment]
> It's a false positive then - the downloads come from my own personal server.
> 
> Most likely your AV is being overly protective, because it doesn't know the download address. (After all, it's a personal server)

Thank you
