### ISSUE TITLE
Food lost in the void when delivered from a warehouse if the granary gets full in the meantime

### ISSUE THREAD

**Issue by Ouaz** [Keriew/augustus#543]
![food_in_the_void](https://user-images.githubusercontent.com/11946570/144760490-d22ec12d-85df-4efd-a91d-23881df71023.png)

To reproduce:

[save_augustus_food_in_the void.zip](https://github.com/Keriew/augustus/files/7656666/save_augustus_food_in_the.void.zip)

- Load the save.
- Pause the game right away and display the Warehouses overlay to locate the warehouseman with meat in his cart.
- Right-click on the granary on the left, it should get full (due to farm cartpusher's deliveries) just before the warehouseman arrives.
- The warehouseman continues his delivery and drops the meat to the full granary: the meat is lost in the void (not added to the granary stock)
- The warehouseman comes back with his empty cart, and the same process happens everytime if the granary gets full before the warehouseman arrives (even if the warehouseman is still far from the granary, and the granary gets full - it happens on the 2nd meat delivery for example).

**Comment by crudelios** [comment]
This is an original bug, and it's even documented in Julius:

https://github.com/bvschaik/julius/blob/14ccc48a48331bcc2461463d825b50648e572b02/src/figuretype/cartpusher.c#L473

This should definitely be fixed though.

**Comment by Ouaz** [comment]
> This is an original bug, and it's even documented in Julius

Oh, I never noticed that in vanilla C3 (due to warehousemen delivering food to granaries only if they're less than half full). So I launched and witnessed the bug right away on a dense farming city. Haha.

But, as Augustus 3.0 added by default "_Warehouses will now send food to granaries if there's any empty space in there, instead of needing to be half-empty_", the bug is more glaring (and can happen a lot more).

Thanks for your answer.

**Comment by crudelios** [comment]
No problem, I'm trying to fix this actually.

I never added the "check for a better destination every X tiles" to these sort of cartpushers, I think it's a good idea to do so.
