### ISSUE TITLE
Supply Post = Mess hall?

### ISSUE THREAD

**Issue by TheRealAyCe** [Keriew/augustus#549]
The PDF mentions both mess hall and supply post, is it the same building? https://raw.githubusercontent.com/Keriew/augustus/master/res/manual/augustus_manual_3_1.pdf
Should be renamed to the same name everywhere.

**Comment by crudelios** [comment]
True, the supply post was originally called mess hall and we missed some changes.

**Comment by Ouaz** [comment]
Thanks, fixed in the WIP manual 4.0.
