### ISSUE TITLE
Suggestion:  Layout of the Building's Information Panel

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#55]
Please exclude this thread.

**Comment by arkimedes1967** [comment]
Since the help shortcut is redondant on granary information panel and on its Special orders, there's a better functional & attractive visual alternative to limite te market lady access, as the iamge below shows.

This way, you can give special orders on the same place.

![Granary Instructions 1](https://user-images.githubusercontent.com/64329357/83947546-8fdfb500-a80f-11ea-87aa-c0a818fa6d26.jpg)

**Comment by Keriew** [comment]
I'd rather not remove the help button, but it looks better moved to the position you indicated.

For the market lady control button, I'd like to keep it and the warehouse's in the same spot and warehouse's special orders page is pretty cluttered as it is.

**Comment by arkimedes1967** [comment]
On warehouse you've no other choise because there's 3 options, this is not the case of granaries. Try to play the game, openning & closing repetetly the granary panel & special options, you'll see it's more funcional this last option, on my point of view.

**Comment by Areldir** [comment]
I'm closing this issue, as it seems Keriew has already answered all questions.
