### ISSUE TITLE
Bug with stocks in warehouses

### ISSUE THREAD

**Issue by Muryska** [Keriew/augustus#553]
Hello! I saw the strange behavior of the game in the following situation: For example, in a warehouse, 8 units of clay. A worker carries one unit of clay to the pottery workshop. In this case, after a few seconds, the amount of clay in the warehouse decreases by 1. As a result, 6 units of clay remain in the warehouse. If the pottery workshop is very close to the warehouse, then there is no additional reduction in clay reserves. Is this a bug? The same is with other stocks in warehouses.

**Comment by Muryska** [comment]
I'm on my last mission - Massalia. Game version 3.1.0.55

**Comment by Keriew** [comment]
That sounds pretty weird. Do you have a save which allows to reproduce the issue?

**Comment by Muryska** [comment]
On the first save (03-01.svx) there are 15 units of clay in the warehouse. On the second save (03-02.svx) I built a pottery workshop. There is no clay in it yet, but a worker with a cart is walking towards it. The cart contains one unit of clay. At the same time, there are 13 pieces of clay left in the warehouse ... I also attach screenshots.
[bug.zip](https://github.com/Keriew/augustus/files/7795375/bug.zip)

**Comment by Keriew** [comment]
Thanks, that helps a lot! I managed to find out the problem. That was a really nasty bug. Fixed in f1d503f. Newest unstable will have it fixed.
