### ISSUE TITLE
Map change in Carthago 159BC

### ISSUE THREAD

**Issue by npliashechnikov** [Keriew/augustus#554]
Hi!
I'm playing through Carthago map now and just received the empire border change notification. However, the map remains unchanged. On the heavengames forum, I found a similar question but it was never answered.

Maybe someone with knowledge of the game internals might shed some light on what had been supposed to happen with this map change?

**Comment by Keriew** [comment]
Empire expanded event does three things:
1. Most notably, changes the cities of type EMPIRE_CITY_FUTURE_TRADE to EMPIRE_CITY_TRADE, allowing a new potential trade route.
2. Changes the city type from EMPIRE_CITY_FUTURE_ROMAN to EMPIRE_CITY_DISTANT_ROMAN - no gameplay effect, just one "distant city" changes into "distant roman city". Purely for flavour.
3. Some objects have different positions on the map with the empire expanded. That's mostly used for the poles that indicate empire borders.

Player can't tell in advance which cities will change. They all appear as "A distant city" with yellow flag.

In this specific scenario, Vollubilis (southwestern corner of the map) is marked as a future Roman city, and it changes to a Roman city after the border expansion event. The border poles around it also move. In addition, Brundisium and Toletum teleport from Italy and Spain to Slovenia/Croatia (Which I guess is an unintended bug, probably was meant for the border poles to move there). In this case, the expansion has no gameplay effect and is just used to add some flavour to the game.

**Comment by npliashechnikov** [comment]
Thank you, that's a great insight!
I wonder how many gamers were losing their minds trying to figure out what happened. I sure did. Glad to have it finally answered.
