### ISSUE TITLE
Division by Zero crash when accessing Health Advisor if there are no occupiable/occupied buildings

### ISSUE THREAD

**Issue by BazzaCuda** [Keriew/augustus#565]
Steps to reproduce:
1. Select any map from the City Construction Kit.
2. Immediately click the Advisors button in the sidebar, or use the Health Advisor hotkey.
Augustus will crash with the standard message reporting an unrecoverable error.

If you firstly create some housing and allow people to move in and then access the Health Advisor, the crash does not occur.
But if you then delete all the tents, trying to access the Health Advisor directly or via the Advisors button will cause the Division by Zero crash.

I believe the fault is in city_health_get_global_sickness_level() in src\city\health.c, line 335:
    int global_rating = building_sickness_level / building_number;
when building_number is still zero.

**Comment by crudelios** [comment]
Strangely enough, on Android I don't get this crash though there indeed is a division by zero.


However, upon debugging I can confirm the crash is indeed caused by that line. Thanks!
