### ISSUE TITLE
theaters and amphietars don't show players in Entarteiment view

### ISSUE THREAD

**Issue by mmaslano** [Keriew/augustus#567]
I believe there is difference between original Caesar 3. When you go to Overlays/Entertainment/Amphiteaters, you should see only amphiteaters. Those which have actors and gladiators have persons on stage even in this view. It was the same for Theaters. It is helpful when you are trying to figure out which entertainment is missing performers.
(I was trying to attach a picture, but I failed. Drag&drop doesn't work for me. Feel free to close it if it's not useful without it).

**Comment by Ouaz** [comment]
> I believe there is difference between original Caesar 3. When you go to Overlays/Entertainment/Amphiteaters, you should see only amphiteaters. Those which have actors and gladiators have persons on stage even in this view.

Are you sure about that ?

I tested on vanilla C3:
- Amphitheater overlay shows amphitheaters, actor schools, gladiator schools, and walkers from both of them
- Theather overlay shows theaters, actor schools, walker from actor schools

Both overlays do not show persons on stage.

> It is helpful when you are trying to figure out which entertainment is missing performers.

Well, it's actually a good idea!

That's something that could be added to the Trouble overlay (currently it shows Entertainement buildings only if they have no labour).

When hovering Entertainement buildings on the Trouble overlay, which have workers but no performers:
```
"No current plays" (Theather, Amphitheater, if no actors)
"No current gladiator combat" (Amphitheater, Arena, Colosseum, if no gladiators)
"No current races" (Hippodrome if no charioteers) 
```

**Comment by crudelios** [comment]
This is a good idea, I'll add this for v3.2.0
