### ISSUE TITLE
Small/large pond graphics

### ISSUE THREAD

**Issue by bibelwort** [Keriew/augustus#570]
Dear Augustus mod team,

I would like to note, that small/large ponds look weird..
It seems that the water surface has wrong isometric angles in contrast to the border with gardens.
Could you fix that?

Anyway, new assets are fantastic! 👍 Thank you all! ☺️

![IMG_20220217_194508](https://user-images.githubusercontent.com/57213149/154529970-eb7df9a8-ffe2-47fa-8f1e-d1d8960bad01.jpg)

**Comment by crudelios** [comment]
Hi,

Even thought I'm not the author of the asset  I think I can say the pond is supposed to look irregular, in order to give it a more "natural" look.

If you pay close attention, you'll notice that a paved circle surrounds the pond, and that one is aligned isometrically. The pond, in turn, is not aligned with the circle either.

**Comment by bibelwort** [comment]
Sure, I understand that they were intended to be irregular. However some disproportion of the pond catches the eye.
I have tried to normalize the isometric image. As you can see, the ponds are clearly stretched along y-axis (on the game screen).
Probably, it was not intended by the author..

I mean, if we stretch them along x-axis instead, they could become more 'natural' within the game environment.
It is a question of visual perception. For example, the Greeks took into account how humans see 3D-world designing the Parthenon and other monuments. I think, the Romans did this too ☺️

![large_pond](https://user-images.githubusercontent.com/57213149/154564369-3e4b0ac7-a29a-423a-8dc4-3cd477d1cb11.png)
![small_pond](https://user-images.githubusercontent.com/57213149/154564375-0b7ed3c7-a1c7-4f1c-8305-d0ccbd53cb7a.png)

**Comment by crudelios** [comment]
@Areldir I think this one is your area of expertise 🙂

**Comment by crudelios** [comment]
Given the provided explanation, I'm closing this issue.
