### ISSUE TITLE
Warehouse and pub and market issues

### ISSUE THREAD

**Issue by maoxp09** [Keriew/augustus#575]
1     What are the functions of large tombs and small Tombs? They seem to reduce satisfaction
2     How can the warehouse be opened only to pubs and not to the market? The distribution of wine in the market will lead to a large number of nobles. Labor decline

**Comment by maoxp09** [comment]
If the warehouse prohibits market purchase, the tavern will not get wine from the warehouse. If it is opened, it will produce a large number of nobles

**Comment by crudelios** [comment]
1. They provide religion access to some people to all gods, a bit like the oracles, at the cost of don't desirability

2. You can disable wine distribution in the market itself by going to "special orders", so you can keep the access enabled on the warehouses.

**Comment by maoxp09** [comment]
> 1. 他们让一些人接触到所有的神，有点像先知，而代价却是不可取。
> 2. 您可以通过进入“特殊订单”来禁用市场上的葡萄酒分销，这样您就可以在仓库中保留启用的访问权限。

Thank you for your answer, but if the warehouse is set to prohibit market purchase, the tavern can't get wine from the warehouse

**Comment by maoxp09** [comment]
> 1. 他们让一些人接触到所有的神，有点像先知，而代价却是不可取。
> 2. 您可以通过进入“特殊订单”来禁用市场上的葡萄酒分销，这样您就可以在仓库中保留启用的访问权限。



> 

Thank you for your answer, but if the warehouse is set to prohibit market purchase, the tavern can't get wine from the warehouse

**Comment by crudelios** [comment]
Don't use the warehouse, use the market:
![city 2022-02-23 18 10 09](https://user-images.githubusercontent.com/6518876/155380906-3658c6fd-ed59-4f03-a0b4-dd4d4900abea.png)
![city 2022-02-23 18 10 15](https://user-images.githubusercontent.com/6518876/155380909-1271969f-1f55-4ad2-80d8-ddd347bd63b1.png)

**Comment by maoxp09** [comment]
> Don't use the warehouse, use the market: ![city 2022-02-23 18 10 09](https://user-images.githubusercontent.com/6518876/155380906-3658c6fd-ed59-4f03-a0b4-dd4d4900abea.png) ![city 2022-02-23 18 10 15](https://user-images.githubusercontent.com/6518876/155380909-1271969f-1f55-4ad2-80d8-ddd347bd63b1.png)

I can't believe that the original market can also restrict trading. Thank you very much for your answer!

**Comment by maoxp09** [comment]
> If you set markets to not sell wine, market ladies won't fetch wine from warehouses, but Tavern suppliers could still access wine in warehouses.

I can't believe that the original market can also restrict trading. Thank you very much for your answer!
