### ISSUE TITLE
Fountains not working in a large city

### ISSUE THREAD

**Issue by Dgeremi** [Keriew/augustus#58]
Hi, $subj

Description:
I'm creating a large city on the map that created myself via an editor.  At a certain point, I see that newly build fountains are not working. Here are some interesting points:
In my city, there is little unemployment, so this is not that case when I have no workers for water supply.
previous fountains working without issues, it is not the situation when you have too little working people on water supply and fountains working one by one. Only new fountains are not working.
New fountains decreasing unemployment, so there are people working on water supply, but still, fountains don't work.
I'm attaching my savefile and some screenshots. Feel free to test.

Release: v1.4.0 - Windows
If it will be usefull initial map was created on v.1.3.1
[All-Housing.zip](https://github.com/Keriew/augustus/files/4741062/All-Housing.zip)

![photo_2020-06-07_01-07-56](https://user-images.githubusercontent.com/12035588/83955421-782e1e00-a85b-11ea-97ee-d631bace0878.jpg)

**Comment by Keriew** [comment]
Fixed. Check the latest unstable build if you want to test it.
