### ISSUE TITLE
People's shadows get painted onto the roofs of the buildings they're passing

### ISSUE THREAD

**Issue by BazzaCuda** [Keriew/augustus#583]
![Clipboard Image (3)](https://user-images.githubusercontent.com/22550919/157270868-4e929f87-9625-4e45-af36-73c58b7d94d4.jpg)

Shadows of cartpushers, caravan donkeys, charioteers, etc. often get painted on the roofs of the buildings they pass.
The black splodge on the roof in the screenshot is actually the ground shadow of a charioteer passing the building on the street below.

It is also noticeable when a cartpusher takes a diagonal route passed the corner of a warehouse: the cart's shadow gets drawn on the warehouse's decking as the cart passes. The same for caravans: the donkey's/mule's shadow is drawn on the building.

If you need further example screenshots, let me know.

**Comment by crudelios** [comment]
I don't think there's a way to fix this short of removing shadows. Even with the new hardware renderer, the way the game engine expects buildings to be drawn, there's really no way to fix this unfortunately.

**Comment by BazzaCuda** [comment]
OK, at least now it's a known issue, if it wasn't already ;)
