### ISSUE TITLE
Tents confer +des 3 tiles away with Venus bonus

### ISSUE THREAD

**Issue by dmyersturnbull** [Keriew/augustus#589]
With the C3 resources from GOG,
Tent desirability is initial  -3, step size 1, step value +1, range 3 -- so -3, -2, -1. With the 2nd Venus perk, it becomes -1, +0, +1. This is very odd.

Insulae have a related issue: small and medium have a different range than large and grand.

(Hopefully I read the code correctly!) By the way, should these values just be defined in the code or an Augustus-specific config file? Right now some are defined in the C source and others are in the C3 config file.

**Comment by crudelios** [comment]
Well, the Venus temple epitaph does improve overall desirability, so it makes sense that it also reduces negative desirability of some buildings.

**Comment by dmyersturnbull** [comment]
Sure. But this means that tents actually become desirable, so players will see nearby villas evolve when they plop down tents.

I think sign flips are seriously unexpected and should be prevented. Changing the range of tents to 2, or catching this case in the code would fix.

**Comment by crudelios** [comment]
That makes sense, yeah. Max for tents should be zero.
