### ISSUE TITLE
Hippodrome only works if road touches the north third of the building

### ISSUE THREAD

**Issue by vorsprung1** [Keriew/augustus#6]
https://github.com/bvschaik/julius/issues/311
~https://github.com/bvschaik/julius/issues/312~
~https://github.com/bvschaik/julius/issues/313~
~https://github.com/bvschaik/julius/issues/315~

(Fixed issues are struck)

**Comment by Keriew** [comment]
https://github.com/bvschaik/julius/issues/313 is intentional, per manual:

> Caesar 3 manual, pg.89
> Without  performers,  the venue's staff becomes a little desperate, and tries to entertain people there themselves, though  the  results  are  barely  better  than nothing at all.

Others seem like good fixes (with wolves change maybe being optional).

**Comment by vorsprung1** [comment]
Also this one as well as I was surprised to see that the Julius boss won't fix, hope you are more open: https://github.com/bvschaik/julius/issues/314

**Comment by vorsprung1** [comment]
> 
> 
> [bvschaik#313](https://github.com/bvschaik/julius/issues/313) is intentional, per manual:
> 
> > Caesar 3 manual, pg.89
> > Without  performers,  the venue's staff becomes a little desperate, and tries to entertain people there themselves, though  the  results  are  barely  better  than nothing at all.
> 
> Others seem like good fixes (with wolves change maybe being optional).

Didn't know about that, the behaviour seemed strange to me, but thanks for clearing it up.

**Comment by vorsprung1** [comment]
@Keriew cool! I would love to try out the changes, but there is no unstable build for Windows, only a release from last week. Is this on purpose?

**Comment by Keriew** [comment]
It's up now. I upload builds when I'm fairly confident that they're working properly.

**Comment by CommonLoon102** [comment]
You can trap wolves by building aqueducts around them. It is cheaper than walls.

**Comment by CommonLoon102** [comment]
Theaters work fine without an actor colony, it just won't provide that much entertainment. Only the amphitheater needs an actor colony.
