### ISSUE TITLE
Request: Fix Career Trade

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#60]
There's some career missions/scenarios that have been reported with some bugs, since the Impressions 1.0.10 patch. I found at least 2:

Can't import marble from Tarsus on Damascus mission;
Can't export vegetables to Carthago Nova on Caesarea Mission.

I'll try to find eventually more bugs no the career maps and i'll report them on this thread.

![Damascus Marble Bug](https://user-images.githubusercontent.com/64329357/83973874-31830700-a8e1-11ea-801c-1b439623bc15.jpg)

![Caesarea Vegetables Bug](https://user-images.githubusercontent.com/64329357/83973880-39db4200-a8e1-11ea-8b42-3a0c757fa68e.jpg)

**Comment by arkimedes1967** [comment]
> Adding the career maps to CCK also wouldn't be trivial, because they are stored as saves and not as .map files. I'll think of a level selection screen for the career in the future.

I found the C3 game explorer on Caesar 3 Heaven site, [Caesar 3 Heaven site](https://caesar3.heavengames.com/downloads/showfile.php?fileid=914) that alows you to edit certain items on city save files. At least on Damascus, if we can't import marble maible we can produce it.

Talk with the very talented Bianca (aka bvschaik, aka pecunia) about it.

**Comment by Keriew** [comment]
What's the problem with Caesarea? You can't produce vegetables there, so it make sense that it doesn't show up on the trade screen.

**Comment by arkimedes1967** [comment]
I was pretty sure we could produce vegetables, sorry my mistaque. Saw you fixed the Damascus Marble, thanks.
