### ISSUE TITLE
invert map dragging

### ISSUE THREAD

**Issue by hankyuller** [Keriew/augustus#604]
Is there a way to invert right mouse map dragging ?

Thanks for the great work.

**Comment by Keriew** [comment]
We've added the option for that. If you want to try it, check the unstable version.

**Comment by hankyuller** [comment]
Thanks for your answer. I've tried it, and it works. 

There is a new issue with the cursor being moved at another location after the dragging. It seems to be related with the display scale being set to something else than 100% (I use 140%).
