### ISSUE TITLE
Links to packages are dead

### ISSUE THREAD

**Issue by jaroslavknotek** [Keriew/augustus#610]
The links to [josecadete.net](josecadete.net) in the documentation are all dead. 

Steps to replicate:
```
> curl josecadete.net
curl: (7) Failed to connect to josecadete.net port 80: No route to host
```

This bug prevents me from downloading the installation package

**Comment by Areldir** [comment]
Unfortunately, the download server experienced a critical failure and is currently down. The only accessible version of Augustus right now is the stable build, accessible via the links on the Code tab.

**Comment by jaroslavknotek** [comment]
Thank you. This workaround works.
