### ISSUE TITLE
Tarentum Mars wrath

### ISSUE THREAD

**Issue by greggman1221** [Keriew/augustus#614]
I'm not sure if this is only in Tarentum, but incurring Mars wrath does not generate any punishment. I get the pop-up saying that I have "no military assets" even though I have three forts with soliders

**Comment by Keriew** [comment]
The behaviour is working as intended, but the message could use some improving. Gods always perform a small curse, before performing a big one. Small Mars' curse causes a local uprising. However, he's not allowed to do that in the first five missions and it results in that message. That's the same behaviour as in vanilla.

I'll write a new message for this case later.

**Comment by greggman1221** [comment]
Makes sense, thanks a lot. Was not sure if there was some other behavior intended. What an awesome mod, really appreciate it!

**Comment by Keriew** [comment]
Added in 8e0cad8.
