### ISSUE TITLE
"Getting" changes to "Accepting" at certain values.

### ISSUE THREAD

**Issue by cdsmith-umn** [Keriew/augustus#62]
If you set a granary to get food, the button will change to "Accepting" when you set the value to get to 18. When the value is 6, 12, or 24, it will read "Getting". **This does not change the granary's behaviour**. It is a visual bug only.

![granary_getting_bug_24](https://user-images.githubusercontent.com/9805709/84023944-9de81f80-a94e-11ea-93ed-6480daa62bd3.png)
![granary_getting_bug_18](https://user-images.githubusercontent.com/9805709/84023949-9fb1e300-a94e-11ea-9ee1-3243ab24c03c.png)
![granary_getting_bug_12](https://user-images.githubusercontent.com/9805709/84023953-a17ba680-a94e-11ea-8a04-fd0d1594510b.png)
![granary_getting_bug_6](https://user-images.githubusercontent.com/9805709/84023959-a3456a00-a94e-11ea-84f3-77acc9987fd7.png)

**Comment by Keriew** [comment]
Thanks for the report, fixed!
