### ISSUE TITLE
running the game on linux

### ISSUE THREAD

**Issue by JohnMuryska** [Keriew/augustus#623]
Hello. I'm trying to run the game on Linux. At first, a lot of errors were given, there were not enough installed packages. Fixed almost all problems. Only one left:
**./augustus-3.1.0.387-14584cc2-linux.AppImage: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found**

Can't find a solution...

I have:
NAME="Linux Mint"
VERSION="20.3 (Una)"
ID_LIKE=ubuntu
UBUNTU_CODENAME=focal

Help me please.

**Comment by volfpeter** [comment]
Hi,

I installed the game from Flathub (as a flatpak).
Here's how I set it up, works well so far: https://github.com/volfpeter/install-guides/blob/main/augustus.md

Peter

**Comment by JohnMuryska** [comment]
That's good, thanks. But in this case, a clean version 3.0.1 is launched. How to run "Unstable build" of the latest version?

**Comment by volfpeter** [comment]
Well, I'm not a contributor in this project, but if you just want to play, I suggest using a stable release.

**Comment by crudelios** [comment]
@JohnMuryska When I get the time, I'll have a go on my linux machine to try and reproduce and fix the problem.

However from what I've read, maybe you need to update gcc to a more recent version? Note that I am unsure of what I'm saying.

**Comment by crudelios** [comment]
@JohnMuryska I just tested on Linux Mint and figured out what's wrong. I'll fix this.

**Comment by crudelios** [comment]
Fixed by [c5b5d8a](https://github.com/Keriew/augustus/commit/c5b5d8afb99be429760426688ab559ddce2d7c61).
