### ISSUE TITLE
Warehouses set to "get 24" pull from "getting" warehouses

### ISSUE THREAD

**Issue by cdsmith-umn** [Keriew/augustus#63]
If you set a warehouse to get 24 of a good, then it will get from other warehouses that are also set to get that good. If you place two of them next to each other and set them both to get 24, then they will spend the entire time getting from each other. I have attached a zip file with an svx and the augustus.ini file. This game was loaded into the 1.4.0.216 unstable build, having been created with the original C3. (I can tell because the area that is walled in is smaller than "normal" now.) The second wine warehouse was placed after loading into the unstable build, however. I set them both to get 24 after the second warehouse was placed.
[carthago_warehouse_bug.zip](https://github.com/Keriew/augustus/files/4745587/carthago_warehouse_bug.zip)

This is not something specific to Carthago, of course. It was simply where I first noticed it this weekend and I knew I had a save file I could use to reproduce it. I did observe this behaviour in Tingis, too, when I tested for it. This behaviour does not happen when the warehouses are set to get either 8, 16, or 32, as I have been using those values without problem.

**Comment by Keriew** [comment]
Thanks for the report, fixed!
