### ISSUE TITLE
Walker sprites render over buildings when walking down a low bridge.

### ISSUE THREAD

**Issue by Julioevm** [Keriew/augustus#634]
Hey all,

Today I noticed, that the walkers going over a low bridge have their sprites appear over buildings that should be covering them, see pic:

![Screenshot from 2022-07-19 10-47-49](https://user-images.githubusercontent.com/38758281/179708867-a8f05ebb-1714-4be8-9af7-c7524de32823.png)

I'm using linux, the development appimage 'augustus-3.1.0.465-902d6e5e-linux'

**Comment by crudelios** [comment]
We know about this but unfortunately this is a quirk of the way the graphics engine works and is unfixable.

**Comment by crudelios** [comment]
For reference, the issue has been posted on bvschaik#544
