### ISSUE TITLE
Ballitas Rotating Map Bug

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#64]
Please exclude this thread.

**Comment by crudelios** [comment]
Afaik this happens with every citizen, not just ballistas. The citizens' position is updated only every X city ticks, so when paused they will face the wrong way.

Hopefully this is a simple fix, I'll have a look at it.

**Comment by crudelios** [comment]
I had a look at this. Contrary to what I was expecting, fixing this issue would require a major require of the way the game handles figures.

Since this is a visual issue that only happens while the game is paused, it's not worth fixing.
