### ISSUE TITLE
From commit 4963ba4 rendering is not correct on aarch64 Amlogic Mali-G52

### ISSUE THREAD

**Issue by shantigilbert** [Keriew/augustus#645]
When compiling for aarch64 and Mali-G52 the rendering of the screen looks like it has bounding boxes. 
I have tried several scale settings and resolutions, they all look about the same.

If I compile the git version that does not use the HW changes (one before 4963ba42f63cd4f4c7b01849033acef958e30c60) display looks fine (Also Julius displays fine). 

Alternative would be to make the HW rendered optional? 

Platform: EmuELEC AARCH64
Device: Odroid N2+ / GPU: Mali-G52 using FBDEV

Any suggestions would be welcomed

Screenshots:
![20220811210708818](https://user-images.githubusercontent.com/18634770/184273831-2a7695e7-acf7-466e-8f7c-1cfe5b834acb.png)
![20220811210743685](https://user-images.githubusercontent.com/18634770/184273833-b4aae4b9-d290-406a-bdbe-22799755c5ad.png)
![20220811210853961](https://user-images.githubusercontent.com/18634770/184273835-0b4857e1-8b62-4fdd-8159-9399e3aebf1d.png)

**Comment by crudelios** [comment]
This is actually an SDL issue.

This same issue happens on android and it has to do with opengles2 not using high precision floats on shaders by default.

Simply disabling HW rendering is not an option as the code is completely different now.

A workaround is to set the max atlas texture size to `1024` on `src/platform/rendering.c`. That's what is done for Android.

A fix has been added to the current unstable version of SDL that should work on all Mali GPU's, except older ones that should have no business running Augustus anyway.

**Comment by shantigilbert** [comment]
> A workaround is to set the max atlas texture size to `1024` on `src/platform/rendering.c`. That's what is done for Android.

Thanks I will test this and let you know! 

> A fix has been added to the current unstable version of SDL that should work on all Mali GPU's, except older ones that should have no business running Augustus anyway.

Do you mean Augustus unstable SDL version? or libsdl? Could you point me to where this fix is?

**Comment by crudelios** [comment]
I mean libsdl. It will be fixed when SDL 2.24.0 is released.

I also checked and it seems FBDEV _can_ use opengles2, so perhaps the fix will also work there.

**Comment by shantigilbert** [comment]
> I also checked and it seems FBDEV _can_ use opengles2, so perhaps the fix will also work there.

Yes we use OpenGles2 on EmuELEC with FBDEV :) do you have a git has for the commit with the fix? I might want to compile SDL and see if it fixes the issue.

**Comment by crudelios** [comment]
Yes, the fix was added on this PR:

https://github.com/libsdl-org/SDL/pull/5947

**Comment by shantigilbert** [comment]
> Yes, the fix was added on this PR:
> 
> [libsdl-org/SDL#5947](https://github.com/libsdl-org/SDL/pull/5947)

This fix also worked for me, I didn't need the workaround :) Thank you!
