### ISSUE TITLE
Werehouse, Market and Get Goods

### ISSUE THREAD

**Issue by RevanStarforge** [Keriew/augustus#647]
There seems to be this weird behaviour,

i made a werehouse nearby the market of my city, because production buildings were far away... werehouse holded 16 furniture and 16 pottery...

but somehow, as long as that werehouse is picked as "get goods", market lady only gets like 4 piece of each, and of course it runs out and everyone leaves the city.

however if i turn that to accept, they take 12 or more, and city stabilizes, but then of course werehouse stocks are slowly dies down. 

And yes, i checked my production the 'far away' werehouses were full to the brim.

Sadly i deleted the save file (i saw there was another closed complaints and there you asked a save game), it was the 3th campaign mission and i can confidently say there was no production issue. and over and over again, i saw the issue, market lady gets much less then normal whenever the werehouse nearby i set to "get goods"

**Comment by crudelios** [comment]
Market ladies should only get 2 of each good regardless of whether the warehouse is getting or accepting. They do get 8 food though, so maybe you saw 2 at the same time at it seemed to be more than they actually were.

Unfortunately without having the save file it's impossible to explain what was going, but I have a feeling it was actually a logistical issue.

What I can recommend is that you have separate markets for food and goods, especially if the block is big/dense enough. Market ladies always prioritize food, so you may very well run out of goods in the market.
