### ISSUE TITLE
Issue with docks?

### ISSUE THREAD

**Issue by crudelios** [Keriew/augustus#653]
### Discussed in https://github.com/Keriew/augustus/discussions/652

<div type='discussions-op-text'>

<sup>Originally posted by **catalin-duta** August 20, 2022</sup>
I'm playing on the Tarsus map and I noticed that for some 2 years trading boats have become rare and few in between.
Sometimes I see a boat spawning (NW side) and it disappears right away.
It seems to improve (not sure if 100% spawns) if I demolish the first dock (awkwardly placed, yes).
Has anyone else noticed something similar?
Screenshot and save attached.
![Screenshot_20220820-211417328](https://user-images.githubusercontent.com/93785920/185761001-660de089-643e-419b-8705-6ac8de4a04c4.jpg)
[7TarsusA2j.zip](https://github.com/Keriew/augustus/files/9387811/7TarsusA2j.zip)
</div>

**Comment by catalin-duta** [comment]
Just some info after going back through older saves: the dock has been there for about 5 years, but for at least the first 3, the boats were heading to the other docks. Not sure exactly what triggered the issue.

**Comment by crudelios** [comment]
Did you change the dock's permissions perhaps?

**Comment by catalin-duta** [comment]
No, I didn't touch the cities docking or the resources. Not exactly related but I did mothball all the wharves a few times. Do the fishing ships share any code with the trading ships?

**Comment by crudelios** [comment]
They shouldn't interfere with one another.

I know why ships won't go to that dock but I don't understand why they only started going there a few years later.à

**Comment by crudelios** [comment]
Even though #749 is a duplicate of this one, there's a better discussion there so I'm closing this one.
