### ISSUE TITLE
Tower Partially Disappears When Shovel Tool is Selected

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#67]
Some towers partially desapper when the shovel tool is selected.

Right-clicking to desable the tool, towers return to normal.

It seems the image of the soldiers (forts) on background jumps to foreground.

![Towers](https://user-images.githubusercontent.com/64329357/84063904-ac1f5580-a9b9-11ea-8fbe-a5e68653f015.gif)

**Comment by crudelios** [comment]
This is a Julius bug, and it's currently being fixed 👍
