### ISSUE TITLE
Request for new hotkey - Mothball/Unmothball building

### ISSUE THREAD

**Issue by Suprcheese** [Keriew/augustus#675]
Currently, the process to toggle mothballing an individual building requires three interactions: RClick to select building, move mouse+LClick to toggle mothball via the button, then close the building window. If trying to do this on a series of several buildings, it can be quite tedious.

The process could be greatly improved with the addition of a new hotkey (or hotkeys) to mothball/unmothball the building under the cursor. The operation could be similar to the copy/paste building settings hotkeys, presumably, including the message displayed at the top.

**Comment by crudelios** [comment]
Good idea!

**Comment by barra81** [comment]
its done ;)
