### ISSUE TITLE
Crash opening city Tingis

### ISSUE THREAD

**Issue by githubfan1** [Keriew/augustus#692]
![crash-opening-Tingis](https://user-images.githubusercontent.com/6599012/190939134-b4f4c0bd-0df1-4e71-ae33-65f0138a834a.png)
[augustus-log.txt](https://github.com/Keriew/augustus/files/9595776/augustus-log.txt)

**Comment by crudelios** [comment]
Did you build the have yourself? It seems like you did.

I can see from the log the crash was causing while loading a sound.

What is the version of sdl_mixer you're using? If you're using 2.0.4 with sdl 2.24.0, that is known to cause issues. Try updating sdl_mixer to 2.6.2 please!

**Comment by githubfan1** [comment]
I am using these versions: SDL2_mixer-devel-2.6.2-VC.zip and SDL2-devel-2.24.0-VC.zip. I am trying to get 2.6.2. Be back.

**Comment by githubfan1** [comment]
I am using the latest SDL versions so the cause of the crash is somewhere else.

**Comment by githubfan1** [comment]
I downloaded and build today with the above SDL versions and I was able to open the city of Tingis. So this is no longer an issue.
Thanks for pointing out to check the SDL versions.
