### ISSUE TITLE
Dialogue if business is mothballed vs if insufficient available labour

### ISSUE THREAD

**Issue by MHCreations** [Keriew/augustus#706]
Version 3.2 
When a structure is mothballed, the text on the structure implies to check the employment / labour advisor in the senate/forum, rather than indicating it has been mothballed.

Can the text be changed (based on an IF/else statement) or -- I read you're probably not likely to change the core text -- can the "mothball" tickbox be more prominent/obvious to a quick glance? 
![mothed](https://user-images.githubusercontent.com/17123773/194582288-9317285a-0874-47b4-85b5-231565dbbaa2.jpg)

**Comment by crudelios** [comment]
This makes sense. A "Building is mothballed text" should be enough.

**Comment by Ouaz** [comment]
This has been fixed: https://github.com/Keriew/augustus/commit/7286dfd02ce2b11af81b01fc48d751a5a69bd29c

![image](https://github.com/Keriew/augustus/assets/11946570/cf98f2d0-47be-4098-be46-7568405e85f7)

**Comment by crudelios** [comment]
Nice! Closing this then.
