### ISSUE TITLE
Augustus crashes on startup

### ISSUE THREAD

**Issue by tominglis** [Keriew/augustus#72]
I just downloaded 1.4.1 for Linux, and copied it over the previous version.

I'm running Ubuntu 20.04 with a ThinkPad T480.

I get this crash on startup:

myusername@mycomputer:~/Games/augustus$ ./augustus 
INFO: Augustus version 1.4.1
INFO: Initializing SDL
INFO: SDL initialized
INFO: Loading game from working directory
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Loading game from base path /home/myusername/Games/augustus/
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Loading game from user pref /home/myusername/.steam/debian-installation/steamapps/common/Caesar 3/C3
INFO: Config key  gameplay_fix_immigration
INFO: Config key  gameplay_fix_100y_ghosts
INFO: Config key  gameplay_fix_editor_events
INFO: Config key  ui_sidebar_info
INFO: Config key  ui_show_intro_video
INFO: Config key  ui_smooth_scrolling
INFO: Config key  ui_walker_waypoints
INFO: Config key  ui_visual_feedback_on_delete
INFO: Config key  ui_show_water_structure_range
INFO: Config key  ui_show_construction_size
INFO: Config key  ui_zoom
INFO: Config key  gameplay_change_grandfestival
INFO: Config key  gameplay_change_jealous_gods
INFO: Config key  gameplay_change_global_labour
INFO: Config key  gameplay_change_school_walkers
INFO: Config key  gameplay_change_retire_at_60
INFO: Config key  gameplay_change_fixed_workers
INFO: Config key  gameplay_enable_extra_forts
INFO: Config key  gameplay_wolves_block
INFO: Config key  gameplay_dynamic_granaries
INFO: Config key  gameplay_houses_stockpile_more
INFO: Config key  gameplay_buyers_dont_distribute
INFO: Config key  gameplay_change_immediate_delete
INFO: Config key  gameplay_change_getting_granaries_go_offroad
INFO: Config key  gameplay_change_granaries_get_double
INFO: Config key  gameplay_change_tower_sentries_go_offroad
INFO: Config key  gameplay_change_farms_deliver_close
INFO: Config key  gameplay_change_only_deliver_to_accepting_granaries
INFO: Config key  gameplay_change_all_houses_merge
INFO: Config key  gameplay_change_wine_open_trade_route_counts
INFO: Config key  gameplay_change_random_mine_or_pit_collapses_take_money
INFO: Config key  gameplay_change_multiple_barracks
ERROR: Oops, crashed with signal 11 :(
INFO:   ./augustus(backtrace_print+0x29) [0x42b6a9]
INFO:   ./augustus() [0x429239]
INFO:   /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f345bf4b210]
INFO:   /lib/x86_64-linux-gnu/libc.so.6(+0x1869ee) [0x7f345c08b9ee]
INFO:   ./augustus(config_load+0x102) [0x42c252]
INFO:   ./augustus(game_pre_init+0x10) [0x488640]
INFO:   ./augustus(main+0x692) [0x428a92]
INFO:   /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f345bf2c0b3]
INFO:   ./augustus(_start+0x29) [0x428b79]

The previous version 1.4.0 worked fine yesterday.

**Comment by Keriew** [comment]
Thank you for reporting it and sorry for the problem. 

I think it should be fixed now. Could you confirm by trying the latest unstable build?

**Comment by tominglis** [comment]
I tried 1.4.1A and that worked fine for me. Thanks!
