### ISSUE TITLE
Update flatpak

### ISSUE THREAD

**Issue by calhix** [Keriew/augustus#721]
Just wondering if you could update the flatpak when you have time, I'm on Asahi Linux so the appimage doesn't work. Thanks!

**Comment by crudelios** [comment]
Hi,

We need someone to test the flatpak build

Can you try testing it by doing:

`flatpak install --user https://dl.flathub.org/build-repo/109245/com.github.keriew.augustus.flatpakref`

And letting us know if it works?

Thanks!

**Comment by calhix** [comment]
No problem! I'm getting:

Can't load uri https://dl.flathub.org/build-repo/109245/com.github.keriew.augustus.flatpakref: Server returned status 404

**Comment by crudelios** [comment]
Right, here's an updated url:

```
flatpak install --user https://dl.flathub.org/build-repo/114801/com.github.keriew.augustus.flatpakref
```
Thanks!

**Comment by calhix** [comment]
No problem, all seems good here!

**Comment by crudelios** [comment]
Flatpak updated, thanks!

**Comment by calhix** [comment]
May have spoken too soon, while on Asahi it seems to work fine, on my Linux desktop it crashes immediately (AppImage works fine). When opening via terminal, I get:

INFO: Augustus version 3.2.0
INFO: Initializing SDL
INFO: SDL initialized, version 2.24.0
INFO: Loading game from working directory
ERROR: 'c3.eng' or 'c3_mm.eng' files not found or too large.
INFO: Loading game from base path /app/bin/
INFO: Location:  /home/XXXX/.var/app/com.github.keriew.augustus/data/augustus/augustus/
INFO: Loading game from user pref /home/XXXX/.steam/steam/steamapps/common/Caesar 3/C3
INFO: Config key  enable_audio  1
INFO: Config key  master_volume  100
INFO: Config key  enable_audio_in_videos  1
INFO: 'c3.eng' or 'c3_mm.eng' files not found or too large. (message repeats 1 time)
INFO: Config key  video_volume  100
INFO: Config key  ui_walker_waypoints
INFO: Config key  gameplay_fix_immigration
INFO: Config key  gameplay_fix_100y_ghosts
INFO: Config key  screen_display_scale  100
INFO: Config key  screen_cursor_scale  100
INFO: Config key  screen_color_cursors
INFO: Config key  ui_sidebar_info  1
INFO: Config key  ui_show_intro_video
INFO: Config key  ui_smooth_scrolling  1
INFO: Config key  ui_disable_mouse_edge_scrolling
INFO: Config key  ui_visual_feedback_on_delete
INFO: Config key  ui_allow_cycling_temples
INFO: Config key  ui_show_water_structure_range  1
INFO: Config key  ui_show_water_structure_range_houses
INFO: Config key  ui_show_construction_size  1
INFO: Config key  ui_highlight_legions  1
INFO: Config key  ui_show_military_sidebar
INFO: Config key  ui_disable_map_drag
INFO: Config key  ui_show_max_prosperity
INFO: Config key  ui_digit_separator
INFO: Config key  ui_inverse_map_drag
INFO: Config key  ui_message_alerts
INFO: Config key  ui_show_grid
INFO: Config key  ui_show_partial_grid_around_construction
INFO: Config key  ui_always_show_rotation_buttons
INFO: Config key  gameplay_change_max_grand_temples  2
INFO: Config key  gameplay_change_jealous_gods  1
INFO: Config key  gameplay_change_global_labour
INFO: Config key  gameplay_change_retire_at_60
INFO: Config key  gameplay_change_fixed_workers
INFO: Config key  gameplay_wolves_block
INFO: Config key  gameplay_buyers_dont_distribute
INFO: Config key  gameplay_change_getting_granaries_go_offroad
INFO: Config key  gameplay_change_granaries_get_double
INFO: Config key  gameplay_change_allow_exporting_from_granaries
INFO: Config key  gameplay_change_tower_sentries_go_offroad
INFO: Config key  gameplay_change_farms_deliver_close
INFO: Config key  gameplay_change_only_deliver_to_accepting_granaries
INFO: Config key  gameplay_change_all_houses_merge
INFO: Config key  gameplay_change_random_mine_or_pit_collapses_take_money
INFO: Config key  gameplay_change_multiple_barracks
INFO: Config key  gameplay_change_warehouses_dont_accept
INFO: Config key  gameplay_change_houses_dont_expand_into_gardens
INFO: Config key  gameplay_change_monuments_boost_culture_rating
INFO: Config key  gameplay_change_disable_infinite_wolves_spawning
INFO: Config key  gameplay_change_romers_dont_skip_corners
INFO: Config key  gameplay_change_yearly_autosave
INFO: Config key  gameplay_change_auto_kill_animals
INFO: Config key  ui_language_dir
INFO: Config value  
INFO: Detected language:  English
INFO: Detected encoding:  1252
INFO: Creating screen 2560 x 1440, fullscreen, driver: x11
INFO: Creating renderer
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  207
  Current serial number in output stream:  208

**Comment by crudelios** [comment]
This may be an issue with your flatpak install. 

Please Try:

- updating your video card drivers;
- running `flatpak update`;

Hopefully this will fix your issue!
