### ISSUE TITLE
A small increase in the population or no influx at all(Android Version)

### ISSUE THREAD

**Issue by kimhaengbok1998** [Keriew/augustus#736]
When the population reaches 9000, the population does not increase, but increases slightly, but an error message keeps appearing and the game cannot proceed.

**Comment by Keriew** [comment]
What's the error message?

**Comment by kimhaengbok1998** [comment]
> What's the error message?

The population does not grow steadily, and after a few minutes the corresponding error message appears.

![image](https://user-images.githubusercontent.com/117495583/200104394-c94c59fc-fa3a-413b-8929-6524a559521d.jpeg)

**Comment by crudelios** [comment]
Can you post the savegame please?

**Comment by kimhaengbok1998** [comment]
> Can you post the savegame please?

[[http://naver.me/5xnitgsD]()

**Comment by kimhaengbok1998** [comment]
> Can you post the savegame please?

How do I Upload a File?

**Comment by crudelios** [comment]
Zip it then drag and drop it to the comment textbox. You'll need to copy the file over to a pc for that.

If you can do it, please do, it will help us a lot figuring out why your city is crashing and hopefully fix it. It will also help us understand what's going on at 9,000 pop in your city.

**Comment by crudelios** [comment]
@kimhaengbok1998 Are you still having this issue? I'm going to close this otherwise.
