### ISSUE TITLE
Connected Warehouses Bug

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#74]
The connected warehouses bug is back, again.

I atach my saved city and the .ini file & log.

Please, see the warehouse near the barraks and the other near the chariot builders. I tried to deleted both, again and again and they still 'connected': the orders on one of them is assumed by the other and vice-versa.

[My City of Cesarea.zip](https://github.com/Keriew/augustus/files/4754427/My.City.of.Cesarea.zip)

![Connected Warehouses](https://user-images.githubusercontent.com/64329357/84191626-acd6eb00-aa90-11ea-996a-ffbd83cf982d.jpg)

**Comment by Keriew** [comment]
I'm not sure it's ever been removed. 

For now, reloading the save unconnects the warehouses. I'll look into the cause of it.

**Comment by Keriew** [comment]
That should fix it. Again, for existing saves, loading the game should unlink the warehouses.
