### ISSUE TITLE
Trading ships disappear right after entering the map.

### ISSUE THREAD

**Issue by Real-Gecko** [Keriew/augustus#749]
After I've build third dock trading ships entering the map disappear almost immediately. You can see them appear on the left part of the river for a brief period. Earlier save with only two docks present worked well for me.
[Caesar3.zip](https://github.com/Keriew/augustus/files/9992513/Caesar3.zip)

**Comment by PrettyFlower** [comment]
Is this your third dock?
![image](https://user-images.githubusercontent.com/2081059/201404051-dad8a404-d08b-4a25-b7b3-a214c3116ec2.png)

I think the issue is the ships can't figure out how to get there, so they immediately off themselves. I tried deleting that dock and building another one further down the shore and that seemed to work ok. Not sure if that's a bug in the original game or something that got introduced in Augustus.

**Comment by Real-Gecko** [comment]
> Is this your third dock?

Yes, that's it.

> Not sure if that's a bug in the original game or something that got introduced in Augustus.

No way to debug?

**Comment by PrettyFlower** [comment]
Looks like it is an Augustus specific issue. We'll have to compare the two to see what's going on. Here's a simpler test case to reproduce the issue.
[Disappearing trade ships OG.zip](https://github.com/Keriew/augustus/files/9992718/Disappearing.trade.ships.OG.zip)

**Comment by crudelios** [comment]
We've had this issue with that same map and a dock in that very same position.

It has to do with the fact that the game isn't very good a picking a spot where ships should queue and sometimes it picks a land tile.

When ships appear, they notice they can't sail there so they immediately disappear.

**Comment by PrettyFlower** [comment]
After looking into this a bit, the thing that changed from the original game is ships used to look for a reachable dock location when entering the map, but now they look for a queue location instead. The "docked" locations for that dock are reachable by ships, but the queue locations are not, so the ships fail now. We could change it so ships look for a "docked" location first again, but the ship navigation code is pretty involved.

**Comment by crudelios** [comment]
Yes, we did make that change. The only way to fix this is to be more dynamic when searching for a valid "first queue"/"second queue tile".

I already improved this somewhat, but it's not perfect.

**Comment by crudelios** [comment]
I'm going to add a change which prevents people from building docks on such spots. It will not fix current problematic buildings but at least it will improve the issue.
