### ISSUE TITLE
Suggestion: Escape Key Shows Game's Menu

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#75]
Like the majority of games today, by pressing the the 'escape' key, it displays the main menu, not the game exit.

![Menu With Esc](https://user-images.githubusercontent.com/64329357/84211281-e6205280-aab2-11ea-9ea4-8b56593d595a.jpg)

The exit menu should be displayed only as a confirmation of the previous one above.

![Quit with Esc](https://user-images.githubusercontent.com/64329357/84211607-a3ab4580-aab3-11ea-9d49-bbd98d92b659.jpg)

Don't you agree?

**Comment by arkimedes1967** [comment]
I'll leave a suggestion:

![menu](https://user-images.githubusercontent.com/64329357/84214836-6b5c3500-aabc-11ea-9c38-81bb16449e38.jpg)

**Comment by daish0** [comment]
What would be really nice is to go back to the main menu.

Not that important as nowadays you can start the game within a fraction of a second, but it always bothered me why we can only go to the main menu by restarting the game.

**Comment by crudelios** [comment]
@daish0 If you go to `File > New game` you'll go back to the main menu 👍

**Comment by crudelios** [comment]
This has now been added.

**Comment by arkimedes1967** [comment]
Yes, you may close this thread, thank you.
