### ISSUE TITLE
what happening?

### ISSUE THREAD

**Issue by Avgus5** [Keriew/augustus#758]
![wtf](https://user-images.githubusercontent.com/118476639/202535176-466c18a9-e99c-4d47-b31b-cb8bb48ae59a.jpg)

**Comment by Avgus5** [comment]
Before this problem was not, but after I went into the settings. or started playing the fifth mission this problem started to come out, please tell me what should be done to avoid this problem? the game just won't start...

**Comment by Keriew** [comment]
Could you copy paste the augustus-log.txt file here? What's your operating system?

**Comment by crudelios** [comment]
I see a problem there, the background image is not showing.

It's possible your C3 installation got corrupted, can you re install it please?

**Comment by Avgus5** [comment]
Win. 10 
I couldn't find the file

**Comment by Avgus5** [comment]
reinstall didn't help

**Comment by Avgus5** [comment]
[augustus-log.txt](https://github.com/Keriew/augustus/files/10034889/augustus-log.txt)
i found the file

**Comment by crudelios** [comment]
You're missing original Caesar 3 files,  how did you install?

**Comment by Avgus5** [comment]
downloaded the installer from the Internet and installed it through the UltraISO application

**Comment by Avgus5** [comment]
Everything works on the other mod. ( Julius mod.)

**Comment by Avgus5** [comment]
the problem was solved by the original download of the GOG version.

**Comment by crudelios** [comment]
Even though you fixed it, I think the problem may have been because you set up a minimal install.

I could be wrong though.

**Comment by bvschaik** [comment]
@crudelios The Russian (1C) version of Caesar3 is missing the entire 555 folder containing the mission backgrounds, they're simply not on the CD.

**Comment by crudelios** [comment]
Ah, so that's it! But that shouldn't cause the crash... hummmm...
