### ISSUE TITLE
Please solve an unrecoverable error in Augustus

### ISSUE THREAD

**Issue by classic380** [Keriew/augustus#765]
When I play this city in Augustus mode of Caesar3,(ver. 3.2.0)
The error message repeat in the same data of the game time.
Could you help this error in my city in the game??
How to solve this error... Please help me
[Godam.zip](https://github.com/Keriew/augustus/files/10086079/Godam.zip)

**Comment by crudelios** [comment]
We also need to know what operating system you're using and when exactly you get the crash.

I tried running the city and didn't get any problem so far!

**Comment by crudelios** [comment]
Due to lack of feedback I'm closing this.
