### ISSUE TITLE
Dock can glitch sea trade entirely if it replaced a Shipyard while game is paused

### ISSUE THREAD

**Issue by gonX** [Keriew/augustus#766]
It seems like it is possible to make a Dock that does not actually function as a Dock.

While paused, selling a Shipyard that has a completed Fishing Boat and replacing it with a Dock, will cause the Dock to instead host the Fishing Boat of the shipyard and effectively the game never treats it as a Dock, never allowing trading ships to spawn. It seems like disabling the Dock (which despawns the Fishing Boat) does not work around the issue.

Step by step:

1) Make a Shipyard (and wait for it to create a Fishing Boat?)
2) Pause the game
3) Delete the Shipyard
4) Put a Dock on the "same" tiles as where the Shipyard was
5) Unpause game
6) Fishing Boat remains stuck to Dock, and no trading ships can spawn at all (even if another Dock is built)

This does not seem like #653 or #749 given their issue is on Tarsus, while I experienced this issue on Miletus (Peaceful 5).

[(gzip compressed) save](https://github.com/Keriew/augustus/files/10088155/20221125.map5.e002.closing.also.dock.svx.gz) that has the Fishing Boat stuck on the Dock

[augustus.ini](https://github.com/Keriew/augustus/files/10088159/augustus.txt) (uploaded as .txt)

and an image of the position of the Shipyard prior to its deletion:
![2022-11-25-032858_grimshot](https://user-images.githubusercontent.com/421345/203888448-6b86d100-8c54-4121-8dbb-bd8e50b1e733.png)

**Comment by crudelios** [comment]
This is a nice one! Good catch.

There was a reason why on the original game building while paused was disabled 😉

**Comment by bvschaik** [comment]
@crudelios Julius is not affected since there's a delay of at least one tick before the building is actually gone, so you _have_ to unpause the game to be able to build the dock - and in that one tick the fishing boat is properly unlinked and deleted.

**Comment by crudelios** [comment]
Right, I forgot about that detail. Thanks!

**Comment by crudelios** [comment]
This should be fixed now... Hopefully!
