### ISSUE TITLE
"Offroad" warehouse emptying does not work

### ISSUE THREAD

**Issue by gonX** [Keriew/augustus#767]
A warehouse that is on a separate road network will not cart resources off the road network, despite being able to use "Getting Goods" for resources from a remote road network.

Steps to reproduce:

1) Create a Warehouse and fill it with at least 4 of the same resource
2) Create another Warehouse on a new road network
3) On the new Warehouse, enable "Gather Goods" on the resource you have at least 4 of in the first warehouse
4) When the new Warehouse has successfully gathered at least 1 load of the resource, go back to the Special Orders of that Warehouse and click "START emptying warehouse" (so that it says "Trying to send goods elsewhere") - you may need to also tell it to stop gathering goods before it actually seems to respect this but I did not test that in depth.
5) Notice the new Warehouse walker does not path back to the first Warehouse, despite the first Warehouse still accepting that type of goods.

A small workaround is connecting the warehouse to the road network and using roadblocks to still keep it disconnected, but this can be costly in some scenarios (in either time or DN)

(savefile and ini can be found in #766, but the Warehouse issue is only partially set up at the time of the save)

**Comment by crudelios** [comment]
This is technically not a bug, but the way the game was designed.

From an outsider's point of view, it seems what can and can't go offroad is random.

Other than that, I agree this is a strange discrepancy that should be made consistent.
