### ISSUE TITLE
Clay quarry UNflooded

### ISSUE THREAD

**Issue by ArtySh0ck** [Keriew/augustus#77]
Plz, look at Valencia (campaign mission)

there is a scripted flooding of clay pits. i have 2 messages about flooded pit far, but after message i cant go (button with viber) there to see. ok, then i tried to look at all of my clay pits manualy but no one didnt flooded. so, only messages works, but clay querrys stays alive and workable.

thanks!

**Comment by cdsmith-umn** [comment]
@ArtySh0ck You almost certainly have the option checked to deduct denarii instead of actually destroying the clay pit (or iron mine, when those collapse). Take a look in the options screen. This is very unlikely to be a bug.

**Comment by ArtySh0ck** [comment]
oops, you are right! in my language localization this option have a wrong information. it says "destroyable mines take a part of money", nothing about instead destroying. 

so, plz, in russian localization of Augustus, replace this option with next: 
"Вместо разрушения, разрушающаяся шахта заберет часть денег"

thanks!

**Comment by cdsmith-umn** [comment]
I'm glad that it's sorted. I'm sure the improved Russian you've provided will get merged in by @Keriew in the near future.

**Comment by Keriew** [comment]
Thanks, I'll fix the localization soon.
