### ISSUE TITLE
Ceres Frugifera ("market") sometimes prefers import food over local food (e.g. Tarsus)

### ISSUE THREAD

**Issue by gonX** [Keriew/augustus#771]
The documentation states:
> **Ceres Frugifera**: Temples of Ceres act as markets, collecting and distributing a **single locally-produced food type** as well as **olive oil.**

On Tarsus (peaceful 7), you cannot build farms, and therefore cannot locally source wheat. However, you can locally harvest fish, as well as import wheat. Despite that, Ceres temples with the Frugifera grand temple upgrade seems to want to distribute wheat. Looking at the code, this does not seem to be the intention, as it seems to prefer locally sourced over any imported food.

https://github.com/Keriew/augustus/blob/dfab1140c669bf8c817e689bdb3ecac16336f0f1/src/city/resource.c#L300-L323

savefile: [20221129 map7 e020.svx.gz](https://github.com/Keriew/augustus/files/10144777/20221129.map7.e020.svx.gz)

**Comment by crudelios** [comment]
Looking at this, I just realized this has unintentionally been fixed since the meat/fish resource separation, so this can be closed now!
