### ISSUE TITLE
Workshops no longer take in raw materials after recent resources code change

### ISSUE THREAD

**Issue by gonX** [Keriew/augustus#778]
After #768 my workshops seem to no longer be taking in resources. I've attached 2 save files that showcases this, the first one is on a recent master version (a5166514), the 2nd save is exactly after #768 (41d575f)
[resource issue.svx.gz](https://github.com/Keriew/augustus/files/10247474/resource.issue.svx.gz)

[resource issue 2.svx.gz](https://github.com/Keriew/augustus/files/10247466/resource.issue.2.svx.gz)

I cannot reproduce this on 7175ef6c8ccda666a89d4576b574cea2acd8e40f, which is the commit before that PR

**Comment by crudelios** [comment]
Fixed by [d896931](https://github.com/Keriew/augustus/commit/d89693179182c367d20cbdbb022b249482659dd3)
