### ISSUE TITLE
Difficulty placing items/roads

### ISSUE THREAD

**Issue by Ranmyaku2** [Keriew/augustus#784]
Playing Lugdunum mission and ran into an issue where after placing a roadblock, I was no longer able to draw roads, place buildings or desirabilty features. I could do everything else. I had save shortly after the road stop place and re loaded the save and still couldn't get anything to place. I also attempted to restart game and tablet. I was playing the latest update on an android tablet (Samsung S8) on very hard difficulty. (tried on normal as well with same issue) I restarted the map from the beginning and it seemed to fix the issue at first but again after placing a road block it would do the same thing. Sometime I did it on pause and would need to unpause before I could then place anything but this only worked some of the time.

I do not have a saved version of this map with the problem at this time since I restarted the map again and it has not yet reoccured.

**Comment by crudelios** [comment]
What do you mean by not being able? Did the options disappear from the menu itself?

**Comment by crudelios** [comment]
I'm managing to reproduce this at random. It seems to require a combination of changing building variants, rotating the map and using undo.

I haven't managed to get this consistently yet though. @Ranmyaku2 did you use map rotation or undo?
