### ISSUE TITLE
Segfault when attempting to place a Dock

### ISSUE THREAD

**Issue by gonX** [Keriew/augustus#785]
Try to place a Dock - this instantly segfaults the game for me. Seems to happen on any level (tested with 8a30981b)

Backtrace:
```
ERROR: Oops, crashed with signal 11 :(
INFO:   augustus-game(+0x7a21f) [0x55e0219e521f]
INFO:   augustus-game(+0x7a2a0) [0x55e0219e52a0]
INFO:   /usr/lib/libc.so.6(+0x38a00) [0x7f1614273a00]
INFO:   augustus-game(map_water_get_waterside_tile_loop+0x1c) [0x55e021a6e54c]
INFO:   augustus-game(city_building_ghost_draw+0x668) [0x55e021a8fee8]
INFO:   augustus-game(city_without_overlay_draw+0x253) [0x55e021a991f3]
INFO:   augustus-game(widget_city_draw+0xe1) [0x55e021a8b861]
INFO:   augustus-game(+0x159e56) [0x55e021ac4e56]
INFO:   augustus-game(window_draw+0x54) [0x55e021a8a3e4]
INFO:   augustus-game(game_draw+0x10) [0x55e021a53bd0]
INFO:   augustus-game(main+0x30c) [0x55e0219e439c]
INFO:   /usr/lib/libc.so.6(+0x23290) [0x7f161425e290]
INFO:   /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f161425e34a]
INFO:   augustus-game(_start+0x25) [0x55e0219e4ab5]
```
```
$ addr2line city_building_ghost_draw+0x668 -e /usr/bin/augustus-game
/usr/src/debug/augustus-game-git/augustus/src/widget/city_building_ghost.c:998
```
https://github.com/Keriew/augustus/blob/8a30981bfbdad66f008a41937e2405f71c954bcd/src/widget/city_building_ghost.c#L983-L998
```
$ addr2line map_water_get_waterside_tile_loop+0x1c -e /usr/bin/augustus-game
/usr/src/debug/augustus-game-git/augustus/src/map/water.c:195
```
https://github.com/Keriew/augustus/blob/8a30981bfbdad66f008a41937e2405f71c954bcd/src/map/water.c#L187-L200

I'm guessing this is caused by dc63333290a but I have not bisected it.
ini: [augustus.txt](https://github.com/Keriew/augustus/files/10296998/augustus.txt)

**Comment by crudelios** [comment]
Hey, hopefully 92618805ff03705d63f43ef87a7a293f7bd3dae2 will fix the issue.

It's difficult for me as it's not crashing on windows or on android, but I think I found the issue.

Lei it build then please let me know if it works!

Thanks.

**Comment by gonX** [comment]
Thanks, that indeed fixes it. Interesting compiler quirk.
