### ISSUE TITLE
Regression: new saves reports "Invalid file" (but loads fine)

### ISSUE THREAD

**Issue by gonX** [Keriew/augustus#786]
How to reproduce:
- Start or load any map (I tested with multiple CCK maps)
- Save it to a new file
- Select the same save file
- Menu reports invalid file, but loading it still works fine

![image](https://user-images.githubusercontent.com/421345/209405055-1711494f-9a31-4d2e-bf3f-a847e500ff61.png)

My last sessions saves from 5 days ago looks fine, so this looks to be a recent regression.

**Comment by crudelios** [comment]
How strange, I thought I fixed this issue!
