### ISSUE TITLE
City needs more employees at high speeds (200%+)

### ISSUE THREAD

**Issue by hermanschaaf** [Keriew/augustus#787]
Thanks for maintaining this great project! I noticed that whenever I set game speeds to something very high (200% or more) it's as if the city's workers all slowly drain away. Pretty soon the city requires 400+ employees, even if I didn't build any new buildings and the housing situation didn't change substantially (approx. the same number and quality of housing before and after the speedup). This could be due to an aspect of the game mechanics that I don't understand, like an aging population (?), but somehow it seems to only happen at these high speeds, and it can make it very difficult, if not impossible, to get enough workers in the city.

Could this be a bug in Augustus?

**Comment by crudelios** [comment]
This is indeed causing by the aging of the population, and it's a recurrent problem. Most likely you only notice the issue on higher speeds because years go by much faster, but it's definitely there on slower speeds as well - it just obviously takes longer.

**Comment by hermanschaaf** [comment]
Yeah, I think you're right! I did a few experiments and read a bit more about the mechanics of ageing populations, it seems like I just noticed it more quickly when the game was running at high speeds. Thanks!
