### ISSUE TITLE
Game not starting on Ubuntu

### ISSUE THREAD

**Issue by sketchbuch** [Keriew/augustus#79]
Hi,

I've been playing Julius for a while without any problem and thought I would try Augustus but the app image doesn't run. Nothing happens when I try and run it. Is there something else that needs doing in order for the Linux app image to run. I really don't use app images so I have no idea what could be wrong.

**Comment by crudelios** [comment]
What happens if you load the game from a terminal window?

**Comment by sketchbuch** [comment]
./augustus.AppImage: error while loading shared libraries: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by sketchbuch** [comment]
I'm using Ubuntu 20.04

**Comment by SWRCrawf** [comment]
Found this problem elsewhere on GitHub.
sudo apt-get install libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0
Worked for me on Kubuntu 20.04
