### ISSUE TITLE
Number of warnings is increasing rapidly

### ISSUE THREAD

**Issue by githubfan1** [Keriew/augustus#793]
Although not a bug, I have seen an steady increase in the number of warnings after compiling the code.
warning C4267: 'initializing': conversion from 'size_t' to 'int'
warning C4244: '=': conversion from 'double' to 'int'

**Comment by crudelios** [comment]
I hate those msvc warnings. Every now and then I fix all of them but eventually some new ones pop up.

I'll fix those eventually!

**Comment by crudelios** [comment]
Fixed by 6ff8edc814c29f344d1a254fd28309c7bbe50888
