### ISSUE TITLE
Game crash - augustus-3.2.0.202-b9e68558

### ISSUE THREAD

**Issue by Omilron** [Keriew/augustus#804]
Hi Team,

My game always crash at this point. Attaching a save file just before the crash.

Best Wishes,
Todor  

[Siege of Murus Terroris 1.zip](https://github.com/Keriew/augustus/files/10465477/Siege.of.Murus.Terroris.1.zip)
![crash](https://user-images.githubusercontent.com/14872298/213675492-a0eb7849-3666-4b13-9524-8de0c5a0bb48.jpg)

**Comment by crudelios** [comment]
Hi,

Some crashes have been fixed since that build, please test on the latest unstable.

**Comment by crudelios** [comment]
I definitely think this was fixed meanwhile, the crash seems to be related with looters, which I  fixed a few weeks ago.

If there's no feedback I'll be closing this soon.

**Comment by crudelios** [comment]
Closed due to inactivity and also because I think this is already fixed.
