### ISSUE TITLE
Audio Issues 3.2.0

### ISSUE THREAD

**Issue by HerrManson** [Keriew/augustus#805]
Im having audio issues with the 3.2.0 version.
Every 3-5 min the sound (all sound) starts to stutter and cracks and the sound slow down to approx 70% speed 
for about 1 min and then goes back to normal. Rinse and repeat.
It is only the sound that lags behind.
I am using logitech G533 wireless headphones with a usb hub and it is only when im using the headphones the problems occur.
When im using the speakers from the audio jack on the motherboard the sound is fine.

Reverted to 3.1.0 version and the sound is flawless on the headphones.
Any ideas?

**Comment by crudelios** [comment]
Probably an sdl issue. Please try the latest unstable which has a more recent version of sdl.

Also, are you running on windows?

**Comment by HerrManson** [comment]
Yes im running on windows.

Will try the unstable build and see how it runs.

**Comment by HerrManson** [comment]
Tried the unstable build.
The problem is still there for me.

**Comment by crudelios** [comment]
Ok I still think this is an sdl issue as we have made no meaningful changes to the audio code.

Please try this, though I'm not really sure this will even allow the game to run: use the `SDL2.dll` that came with v3.2.0 of augustus and replace `SDL_mixer.dll` and add `libmpg123.dll` from v3.1.0, which you can still download [here](https://github.com/Keriew/augustus/releases/download/v3.1.0/augustus-3.1.0-windows.zip).

**Comment by HerrManson** [comment]
Tried what you suggested and it wont run.
"The procedure entry point Mix_LoadWAV could not be located in the dynamic link library F:\ etc etc etc".

The one thing I noticed when the sound bug occurs by quick switching from headphones to speakers and back to headphones
makes the sound bug go away, but comes back after a few minutes again.

Saved the Augustus logs from both 3.1.0 and 3.2.0 and saw a difference with the "loading audio files".

3.1.0
INFO: Loading audio files

3.2.0
INFO: Using default audio driver: wasapi
INFO: Loading audio files.

I dont know what wasapi is and my knowledge in troubleshooting is very limited sadly.

**Comment by crudelios** [comment]
Yeah I added that log information line to know what audio engine is being used.

Do you know how to set an environment variable? If you do, cab you try setting `SDL_AUDIODRIVER` to `dsound` and see if it helps?

You can go back to the original dlls as well...

**Comment by HerrManson** [comment]
Nope but googled it. Is it in advanced system settings then environment variables?

**Comment by crudelios** [comment]
There's a section on "Building Julius" that explains how to do it ([link](https://github.com/bvschaik/julius/wiki/Building-for-Windows#installing-the-prerequesite-programs), you just need to set the above variable instead of the one listed on those instructions.

**Comment by HerrManson** [comment]
Tried that. Augustus wont start, leaving this in the log.

INFO: Augustus version 3.2.0
INFO: Initializing SDL
ERROR: Could not initialize SDL: Audio target 'dsound' not available
INFO: Exiting: SDL init failed

**Comment by crudelios** [comment]
Sorry for this, can you try `directsound` instead?

**Comment by HerrManson** [comment]
That did it, the audio is now fine!!

Thanks for taking your time with this one.

**Comment by crudelios** [comment]
No problem, glad to have helped.

Have fun with the game!

**Comment by crudelios** [comment]
I went ahead and made windows use directsound by default on the latest unstable, so in the future you shouldn't need that environment variable anymore.

I'm also thinking about allowing people to select their audio driver in the config window to prevent such issues in the future.

**Comment by HerrManson** [comment]
The one thing that I am curious about, did you change the audiodriver from 3.1.0 to 3.2.0?
Im wondering what made my game bug out, since there is no reported bug about it on 3.2.0?

**Comment by crudelios** [comment]
No we didn't change the driver.

The game uses the SDL library for graphics/audio/input, and we updated the library between v3.1.0 and v3.2.0.

The library itself started using the new audio driver by default between those updates, which started causing the issues.

Apparently they're working on fixing the issues but it's been an uphill battle for them.

From our end, the newest versions of SDL are useful as they provide new features/performance improvements, so the best way to fix your issue while using the latest SDL version is to force it to use the old audio driver.

**Comment by HerrManson** [comment]
Thanks for shedding some light on my issue. 
Guess that sums it up.

Keep up the good work.
