### ISSUE TITLE
Assign hotkey crash

### ISSUE THREAD

**Issue by RID54** [Keriew/augustus#807]
Describe the bug, the steps to reproduce, and if possible attach a saved game that show the wrong behavior and augustus.ini file to show which options are being used.
Assigning any hotkey to "Messages" makes the game unable to open again after closing. By that I mean that the hotkey works initially but on trying to open the game the next time you want to play, you can't.
Simply removing the last line in the hotkeys file makes the game usable again.
Every other hotkey I've assigned works perfectly.
Thank you so much for all the incredible work you have done on this mod.
I am playing augustus-3.2.0.262-d13f09b1-windows
[augustus-log.txt](https://github.com/Keriew/augustus/files/10473621/augustus-log.txt)
[augustus-hotkeys.txt](https://github.com/Keriew/augustus/files/10473623/augustus-hotkeys.txt)
[augustus.txt](https://github.com/Keriew/augustus/files/10473624/augustus.txt)

**Comment by RID54** [comment]
I have just noticed that although I have assigned a hotkey to Show Empire (and it works) it shows up in the hotkeys file as "show messages". I have attached the hotkeys file and it is the last entry.

[augustus-hotkeys.txt](https://github.com/Keriew/augustus/files/10473748/augustus-hotkeys.txt)

**Comment by crudelios** [comment]
Good catch, turns out all of the overlay hotkeys had such an issue.

**Comment by RID54** [comment]
Glad I could help.
