### ISSUE TITLE
Non-available source of food in 3.2.0.267-171ae576-windows

### ISSUE THREAD

**Issue by RID54** [Keriew/augustus#809]
After watching a live stream of a custom scenario I noticed that two farm food sources were available (vegetables and pigs). However, in my game (using the same scenario) there was only vegetables. When I reverted to augustus-3.2.0-windows, pig farms became available to build.
The downloaded scenario can be found at: https://caesar3.heavengames.com/downloads/showfile.php?fileid=1872
Have attached the .ini file.

[augustus.txt](https://github.com/Keriew/augustus/files/10503710/augustus.txt)

**Comment by RID54** [comment]
On further investigation it seems to be a pig problem!
Pigs are also unavailable for me in the following scenario:
https://caesar3.heavengames.com/downloads/showfile.php?fileid=1869
No problem in 3.2.0-windows, but in 3.2.0.267-171ae576-windows pig farms can't be built.

**Comment by crudelios** [comment]
Seems to happen on maps that used to allow both meat and fish.

A fix is in the way 👍

**Comment by RID54** [comment]
OK. Thank you.

**Comment by RID54** [comment]
Thank you!
________________________________
