### ISSUE TITLE
Crash after army attacking the bugged gatehouse

### ISSUE THREAD

**Issue by martinapro112** [Keriew/augustus#812]
So the army came to attack me, I had a gatehouse and a double wall, they were attacking the first layer of the wall, then apparently started attacking the gatehouse. At that moment I rotated the view to see how many are there, which is probably what broke it - the gatehouse looked rotated 90 degrees and they could not break it even after attacking it for months :D. So I deleted part of the wall, which made them stop attacking the gatehouse, my army destroyed the other army with great honor (those suckers had no chance). Then I wanted to remove all the broken parts and when I attempted to destroy the weirdly rotated gatehouse, it crashed.
![image](https://user-images.githubusercontent.com/33609638/216162699-9996e255-0c69-4f5a-b2d7-d0f3c36e3b54.png)
[autosave.zip](https://github.com/Keriew/augustus/files/10561626/autosave.zip)
PS: Thank you all for giving me my most favorite game back, I love all the changes you did.

**Comment by crudelios** [comment]
What an weirdly specific bug!

I'm willing to bet this would also happen in Julius.

I'll try to reproduce this, thanks!

**Comment by martinapro112** [comment]
![image](https://user-images.githubusercontent.com/33609638/216164048-3f9e95ac-d025-4ce9-adc5-999d7c694d54.png)
This is fun :)

**Comment by crudelios** [comment]
This suspiciously reminds me of a similar bug we had with docks.. you're running on v3.2.0, right?

**Comment by martinapro112** [comment]
Yes, found it in augustus-log.txt

**Comment by crudelios** [comment]
Ok I think I found the cause of the issue and posted the fix.

I didn't test it but I have a strong suspicion I got it fixed.

Note that this won't prevent the crash on your saved game if you saved it with the glitched gatehouse, but it should prevent similar glitchning in the future.
