### ISSUE TITLE
How many trade routes on custom empires?

### ISSUE THREAD

**Issue by Salve970** [Keriew/augustus#816]
How many trade routes on custom empires?  Thanks.

**Comment by crudelios** [comment]
Hello!

Right now there's a hard coded limit of 200 overall objects, 41 cities and 20 trade routes.

I'm planning on removing all of those limits soon (I do mean allowing as many trade routes as you want, without any limit whatsoever), so this answer is only valid while I don't do that.

Meanwhile, I'm going to keep this issue open until I remove the limits.

**Comment by Salve970** [comment]
Thanks for fast reply.  I look forward to you removing all those limits.

**Comment by crudelios** [comment]
The limits have been removed, so I'm closing this now.
