### ISSUE TITLE
Custom Empire Trading Cities Bug [Latest Master as of 7/02/23]

### ISSUE THREAD

**Issue by XLightningStormL** [Keriew/augustus#817]
The bug prevents the last (or first if there is only one trade city defined) trade city specified from having it's trading route line drawn. If however you have multiple...it's hard to describe, it seems the game renders the city instead of the trade wagon/ship icon, causing "upper" defined cities to be moved to replace the wagon/ship icon of later cities.

To replicate make a new map, and choose the test_empire.xml in the custom empires popup, Zargoville will be shown as about 335, 150 x/y instead of the 550, 50 defined (and Mistyvale outright ceases to exist)

This bug doesn't seem to affect old scenarios saved with custom empires

**Comment by crudelios** [comment]
Yeah I'm on the prices of fixing this, thanks!

**Comment by crudelios** [comment]
Should be fixed by [9af63b0](https://github.com/Keriew/augustus/commit/9af63b004628f52eaf0481f00b21950cea7bac82)
