### ISSUE TITLE
Grand temple of Neptune

### ISSUE THREAD

**Issue by florin27x** [Keriew/augustus#821]
Describe the bug, the steps to reproduce, and if possible attach a saved game that show the wrong behavior and augustus.ini file to show which options are being used.
It makes all fountains empty or alternating as the priest passes by, even without any selected option.
I've attacked in augustus.ini in the zip file.
Anyone else got this issue ?
[augustus.zip](https://github.com/Keriew/augustus/files/10716773/augustus.zip)

**Comment by Keriew** [comment]
On both latest stable and unstable build I'm unable to reproduce the issue. Could you provide a save where this situation happens?

Typically flickering fountains mean there's not enough employment for water services. But also the Grand Temple benefits stop if the temples aren't fully staffed, which could lead to fountains connected to Neptune Grand Temple to flicker.

**Comment by florin27x** [comment]
Sure, i'll attach a save game just enable employment to the temple all houses will devolve and re-evolve no employment issues.
[save1.zip](https://github.com/Keriew/augustus/files/10819302/save1.zip)

**Comment by Keriew** [comment]
Hmm, this is most confusing. Even with that save, I can't observe the reported behaviour, both on the newest and the latest stable version. What's your OS and what version are you playing?

**Comment by florin27x** [comment]
Windows 11 latest updates / Augustus ver. 3.2.0 stable
I've attached screenshots with the issue (water services go to 0 even tho they're locked)
[screenshots.zip](https://github.com/Keriew/augustus/files/10831605/screenshots.zip)

**Comment by florin27x** [comment]
Found the issue files needs to be unblocked before copied over otherwise it corrupts the game, haven't realized that the other temples did nothing till i tested them one at a time in a VM and finally got to see what the issue was.

If anyone gets this encounter this issue when things aren't working properly or can't save maps make sure to unblock the file and give permission "full access" for the folder to everyone/user.
