### ISSUE TITLE
Combat music

### ISSUE THREAD

**Issue by bdiethelmv** [Keriew/augustus#83]
Hello! 

First off, thanks for this amazing version of Caesar 3. This is a dream come true.

I have a small question regarding the combat music. For small invasions, I'm always getting the "Combat Long" theme, that is, the more dramatic version (sample here: https://www.youtube.com/watch?v=5i_wvvuSSLQ). On the other hand, large invasions play the short, arguably less interesting theme. This is opposite than what happens in vanilla Caesar 3.

Is this an intended feature? Can it be changed? It is by no means a deal breaker, and I'd say it's not even bothersome, but I was wondering.

Thanks, and keep up the amazing work! You have rekindled one of my favorite games ever.

-Ben

**Comment by Keriew** [comment]
They are switched. Thanks for the report, I'll fix it promptly.

**Comment by bdiethelmv** [comment]
Thanks!
