### ISSUE TITLE
Augustus game crashed soon after big game was loaded

### ISSUE THREAD

**Issue by rdelangh** [Keriew/augustus#836]
A fairly big game has been saved on disk. When I startup the game and load this file, then let it proceed at a normal pace, the game crashes fairly soon after. Just the message "unrecoverable error in Augustus", no further details.
The city-file is attached.
[Rome-10b.zip](https://github.com/Keriew/augustus/files/10924415/Rome-10b.zip)

**Comment by rdelangh** [comment]
The logfile only contains this:

> ...
> INFO: Loading saved game  Rome-10b.svx
> INFO: Savegame version  139
> ERROR: Oops, crashed :(
> INFO: No stack trace available

**Comment by UberWaffe** [comment]
What version of Augustus are you on?

**Comment by rdelangh** [comment]
hi UberWaffe, thanks for replying;
my version seems to be 1.1

**Comment by UberWaffe** [comment]
How soon after loading does it crash?

I was able to run the savegame for more than two years (sped up) using both Augustus 3.2.0 and the latest dev version.

**Comment by rdelangh** [comment]
it crashed after one month, and when I play it now again it crashes at Feb-484BC

**Comment by rdelangh** [comment]
another stage of the game in attach, that crashes after less than one month (speed 90%)
[Rome-11b.zip](https://github.com/Keriew/augustus/files/10933619/Rome-11b.zip)

**Comment by UberWaffe** [comment]
Tried the new savegame and didn't get the crash.

What settings are you playing with? (Under Difficulty and City Management)
Want to see if I get a crash if I use the same.

**Comment by crudelios** [comment]
I need to look at those saves, but @UberWaffe do you get any warnings regarding buildings being looted?

There was a crash related to that that was fixed in the meantime.

**Comment by rdelangh** [comment]
yes indeed buildings are being looted regularly (angry citiy, too many people, no enough jobs).
Difficulty is set to "easy"; 
"City Management" options are all ticked off

**Comment by crudelios** [comment]
This is most likely a bug that has been fixed on the latest unstable of Augustus.

What operating system are you using? Windows?

**Comment by rdelangh** [comment]
hi crudelios,
yes, Windows-7.
With this latest 'unstable' version of the program, it does not crash anymore. Good stuff !
Case closed, I guess. Thanks for your time !

**Comment by crudelios** [comment]
Great to know!

I'll fix this then.
