### ISSUE TITLE
Voice customization

### ISSUE THREAD

**Issue by bdiethelmv** [Keriew/augustus#84]
Hi! I have a minor quality of life suggestion.

Not sure if this counts as UI, but I was wondering if there was any way to prevent both the legion movement and invasion sounds from playing at all. I'm talking about that yell that plays whenever you move troops around, as well as the loud horn or war drums whenever an enemy army gets into the city. On most military assignments, those get old very quickly.

Thanks for the great work!

-Ben

**Comment by crudelios** [comment]
That's very easy for you to fix.

In the game directory there is a folder called `wavs`. You can open all the audio files inside that folder with a media player. Search for the sounds you don't want to hear and simply move them out of the `wavs` folder. Problem solved!

**Comment by bdiethelmv** [comment]
Cool, thanks!
