### ISSUE TITLE
When deleting a game (savefile), next file should be chosen after deleting selected file

### ISSUE THREAD

**Issue by felagund** [Keriew/augustus#841]
When deleting a savefile, the file gets deleted but is still selected. To delete another file, I need to select it and then pres delete (so it is a lot of shuffling of mouse around). If next file in alphabet order were selected, that would greatly improve things.

After finishing a map, I get a lot of intermediate saves that I want to get rid of, this would help it.

**Comment by crudelios** [comment]
Will look into it. 

@bvschaik actually this would be nice even for Julius!
