### ISSUE TITLE
Long (forced) walks for engineers, tax collectors and entertainers from venues

### ISSUE THREAD

**Issue by tmancini85** [Keriew/augustus#842]
Hi,

first of all thanks for your big effort in these great projects: Julius and Augustus brought new life to my favourite game of all time, and I'm sure lots of people are saying you the same.

After watching some GamerZakh's Augustus playthrough using forced walkers, I tried to make some tests with tax collectors and roadblocks. So I played August 3.2.0 (AppImage on Ubuntu Mate 22.04, just for reference), but I discovered that engineers, tax collectors and entertainers from venues can't make their special long (forced) walks anymore (i.e., about 500 tiles in _destination mode_ to the target tile before disappearing/being teleported home): even in a road without roadblocks, they walk their maximum pre-established distance before converting in go-home mode.

Then I found in the 3.2.0 changelog this:

> Fixed some walkers occasionally disappearing.
> [...]
> Fixed when tax collectors, engineers and entertainers sometimes walk in a straight line through the terrain when returning.

which should explains what happened (and to be sure, I tested with last version of Julius and with Augustus 3.1.0, and engineers, etc., can still do long walks there and also made _confused walks_ leaving the terrain).

So my question is if it is possible to make those fixes optional (like others are in the options panel), to preserve the original behaviours of all kind of walkers.

(I searched for this subject in issues, pull requests and discussions, but if I missed it, sorry about that).

**Comment by crudelios** [comment]
AFAIK engineers, tax collectors and prefects could never be used as forced walkers before. They've always been the exception to the rule.

My fix doesn't change that at all.

**Comment by tmancini85** [comment]
Hi Crudelios, thanks for the reply (and, again, for Julius and Augustus).

Prefects can't make any kind of forced walks indeed.

In vanilla Caesar 3 and Julius, and also in Augustus till version 3.1.0, engineers, tax collectors and entertainers from venues can't make the normal kind of forced walk (the one in go-home mode), but they can do up to 500 tiles in destination mode if the target tile is beyond 35 tiles from the spawning point; after reaching the tile, they disappear.

You can find a brief description of the algorithm for this kind of forced walks in reply 12 of [this thread](https://caesar3.heavengames.com/cgi-bin/caeforumscgi/display.cgi?action=st&fn=2&tn=4454&st=11#post12), and there are further information in replies 19 and 22 (maximum distance before disappearing) and in reply 44 (engineers, etc., are _confused_).

Let me know if you need some .sav files to show what i saw.

**Comment by crudelios** [comment]
@tmancini85 They should still be able to do this, I believe. Destination walkers have a max range of 500 tiles, which is actually something I intend to fix (instead of 500 tiles they could easily support 500 direction changes of any length).

**Comment by crudelios** [comment]
Closed due to inactivity.

**Comment by tmancini85** [comment]
Sorry, I missed your reply. Anyway, as a reference, here's a .sav file which shows how in Caesar 3/Julius/Augustus 3.1.0
the tax collector makes a (very) long walk till the eastern plaza tile, whereas in Augustus 3.2.0 he never makes it:
[Tax collector long forced walk.zip](https://github.com/Keriew/augustus/files/13271441/Tax.collector.long.forced.walk.zip).

For the sake of completeness, here's a .sav file where the tax collector makes a _confused_ walk in Caesar 3/etc., but not in Augustus 3.2.0:
[Tax collector confuesd walk.zip](https://github.com/Keriew/augustus/files/13271524/Tax.collector.confuesd.walk.zip).
