### ISSUE TITLE
Strange thing with legions

### ISSUE THREAD

**Issue by ArtySh0ck** [Keriew/augustus#85]
[BugWithLegionClass.zip](https://github.com/Keriew/augustus/files/4783751/BugWithLegionClass.zip)
playing Londinium (savefile attached)

i had only one fort - spearmen. but later i had to delete this to change it for legioners (my own ocd xD ). so i delete spearmen fort, and fort is deleted but spearmans DIDNT DIE, or disappear... they stay on GROUND. well... then i just try to build my first fort as legioners (i thought these spearmens will switch to legioners, at least...), and i build it in far-far away another place from previous spear-fort. what u think? these spearmans start to run to LEGIONERS fort! and they stay there and i can controll them lol.

thanks!
ver: 1.4.1a-204
highlight hovered legion option is ON

screenshot:
![image](https://user-images.githubusercontent.com/46932541/84720351-7fa1a580-af86-11ea-9b8a-4c0d2f4d233b.png)

**Comment by ArtySh0ck** [comment]
upd:

i tried to do something same, but in Sarmizegetusa i havent that bug. maybe reason is pause. i deleted that fort on pause and create new one while paused. and they stay alive. OR reason is map...

**Comment by Keriew** [comment]
Hey, thanks for the report. I'm looking into it.

**Comment by cdsmith-umn** [comment]
I thought I would add that I have confirmed that this happens if you pause the game, destroy a fort, create a new fort, and then unpause the game. If you destroy the fort either without pausing the game or if you unpause the game for a few seconds after destroying the fort, then the legion attached to the destroyed fort does die.

**Comment by Keriew** [comment]
Should be fixed with e061e63.
