### ISSUE TITLE
Augustus 3.2.0 not working on android 5 anymore.

### ISSUE THREAD

**Issue by Bacte** [Keriew/augustus#857]
First, thanks for your impressive work so far.

Tried Augustus 3.1.0 in my ancient tablet (android 5) and worked flawlessly, but after updating to version 3.2.0 I get a black screen, with background music playing.

After uninstalling everything and reinstalling from scratch, the game refuses to run and closes after selecting game folder.

If I reinstall prior version (3.1.0) game runs perfectly again.

Maybe it's related to the new hardware rendering?

**Comment by crudelios** [comment]
Hi,

It's possible the new sdl version has broken support. Even though it claims support for android 5, that is a very old version.

However, can you check if you have an `augustus-log.txt` file on the same folder of the C3 install? If you do, please post its contents here.

**Comment by Bacte** [comment]
Sorry, can't find file augustus-log.txt :(

**Comment by Ouaz** [comment]
> Sorry, can't find file augustus-log.txt :( 

The file is located in the "Caesar 3" folder (containing the whole game) you copied from your PC to your Android device.

You can use your device File Manager to find it.

**Comment by Bacte** [comment]
In my installation the folder "Caesar3" contains 6 subfolders:

555
assets
manual
maps
smk
wavs

And several files. There is an "augustus.ini" file, autosave.svx etc etc, but the file "augustus-log.txt" is nowhere to be found.

As a side note, I have installed OpenTTD and CataclismDDA latest versions. As far as I'm aware both uses SDL, and both games works, although sadly, the poor performance makes them unplayable.

**Comment by Ouaz** [comment]
> And several files. There is an "augustus.ini" file, autosave.svx etc etc, but the file "augustus-log.txt" is nowhere to be found.

Oh ok, I thought that as at least the game starts (black screen, but with the music playing), the log file would have been created.
It seems not. ^^

**Comment by crudelios** [comment]
@Bacte I have since updated SDL. Maybe the new versions will work?

I finally attemped to run an ancient version of android. The earliest thing I can use is the android emulator, which has android 5.1.

That version is working fine.

Do try the latest unstable, please. If that doesn't work, then I'm afraid it's something that can't really be fixed.

**Comment by Bacte** [comment]
Just tested the android dev version as advised and...

Still no log file but...

It works, aaaand runs smoother than ever. This definitely makes me think twice about throwing the relic to the trash. Thank you so much for your hard work.

Android 5.0.2 btw ^^

**Comment by crudelios** [comment]
Great that it works!

And yeah, the main idea with the hardware renderer was to make the whole thing smoother. 

Have fun!!!
