### ISSUE TITLE
Clicking on the Save Button makes the PS Vita version crash

### ISSUE THREAD

**Issue by Kadir1K** [Keriew/augustus#867]
![2023-05-15-102054](https://github.com/Keriew/augustus/assets/106933960/70f0f421-3345-45ee-98a4-6a172e418dfc)
/
![IMG_20230515_102840](https://github.com/Keriew/augustus/assets/106933960/abff7d74-0a65-40bc-a4fa-a3b7d49cb613)

**Comment by Kadir1K** [comment]
Happens on stable and unstable

**Comment by crudelios** [comment]
@Kadir1K What about trying to load a game on the main menu? Or opening the CCK?

**Comment by Kadir1K** [comment]
@crudelios Loading a save file from the main menu works just fine

**Comment by crudelios** [comment]
This is really strange. The dialog window is exactly the same.

I only tested on vita3k right now and saving worked fine, I need to dig up my original vita.

**Comment by crudelios** [comment]
I managed to reproduce the crash.

It only happens when there are no save files, hence I was getting no crash.

Will fix ASAP.
