### ISSUE TITLE
package name in Debian

### ISSUE THREAD

**Issue by josch** [Keriew/augustus#87]
Hi,

I packaged augustus for Debian but unfortunately, there is already a package in Debian called augustus, namely this software: http://bioinf.uni-greifswald.de/augustus/

Do you have some preferences of how your software should be named as a package in the Debian archive? Some examples would be `augustus-game` or `julius-augustus` because it's a julius fork.

What do you think?

**Comment by Keriew** [comment]
I think augustus-game would work better, I'd rather avoid having Julius in name, because many people are already somewhat confused between the two projects and I wouldn't want to add that.

**Comment by bvschaik** [comment]
Are you also going to package Julius for Debian? As far as I know there's no package yet.
For Julius there's also a clash with some speech recognition software. At least one other distribution also uses `julius-game`.
