### ISSUE TITLE
Disallowed small temples can still be cloned

### ISSUE THREAD

**Issue by UberWaffe** [Keriew/augustus#887]
When a small temple is disabled via events (i.e. no longer available in the build menu), the player can still hover over the building and use the shortcut key to 'Clone building under cursor' and place down more of the building.

I suspect it is because in `int scenario_building_allowed(int type)` it checks for `case BUILDING_MENU_SMALL_TEMPLES:` and not individual temples.
I suspect other 'group' buildings will have the same behaviour.

Edit: Originally discovered by Marek during his stream of Cloud's map.

**Comment by crudelios** [comment]
How are you disabling individual buildings from working on the scenario events?

**Comment by UberWaffe** [comment]
The scenario events do not disable individual buildings. It uses the allowed_buildings.
`scenario.allowed_buildings[allowed_id] = allowed;` from `int scenario_action_type_change_allowed_buildings_execute(scenario_action_t *action)`

In the specific map the event fires after the player has built several small temples.
Marek pointed out that he was able to (even though no longer available via menu) to use the clone tool on existing small temples to build more of them.

**Comment by crudelios** [comment]
Okay nos I understand it better, the fix should be easy anyway.
