### ISSUE TITLE
Buildings like "Mint" aren't being displayed

### ISSUE THREAD

**Issue by prithvikukillaya** [Keriew/augustus#892]
When I select this building all that shows up in 4 squares and one of them looks like the roadblock graphic.

**Comment by Keriew** [comment]
If you're running the unstable version you need to download the development assets from [the main page](https://github.com/Keriew/augustus). You'll also need to delete the old assets folder first, just overwriting may not be enough.

**Comment by crudelios** [comment]
I'm going to close this as it isn't really a bug,.
