### ISSUE TITLE
Crackling sound in Augustus.

### ISSUE THREAD

**Issue by Elo-than** [Keriew/augustus#895]
When starting and using Augustus 3.2 with the GOG version of the game (on Win 11) all sounds are crackling and noticably degraded compared to when launching the basic C3.exe.

Basic Caesar 3 plays audio without issue

This affects all audio.

Tried running as administrator, in compability modes, but no change.
Tried resinstalling, moving install directory in case of folder permission issues, but nothing seems to resolve the issue.

Unstable release do not have this issue as fair as I can tell.

**Comment by crudelios** [comment]
This is a known issue related to the audio subsystem that has been fixed since, as you mention.

Closing as fixed on unstable.
