### ISSUE TITLE
Highway has Artifact on augustus-3.2.0.490-43c14871-windows

### ISSUE THREAD

**Issue by Frank-FYC** [Keriew/augustus#908]
When opening a new map, Augustus based or not, highways have an artifact.
![image](https://github.com/Keriew/augustus/assets/16265543/8ca9cdd2-0bea-4d77-a4bc-8521b3e15b6c)

**Comment by Keriew** [comment]
If you're running the unstable version you need to download the development assets from [the main page](https://github.com/Keriew/augustus). You'll also need to delete the old assets folder first, just overwriting may not be enough.

**Comment by Frank-FYC** [comment]
Understood. Was this information stated somewhere I missed?

**Comment by Frank-FYC** [comment]
Fixed, thank you! 
![image](https://github.com/Keriew/augustus/assets/16265543/3964a4e4-eaa4-4547-9edb-f7e6c95863e6)

**Comment by Keriew** [comment]
The game displays an error if you start the game without having any assets. I guess it doesn't really show any message if you've updated from the older version. This could always be improved... Anyway, glad that it works.
