### ISSUE TITLE
Hippodrome producing Chariots???

### ISSUE THREAD

**Issue by subatron** [Keriew/augustus#91]
So... 2 things that are weird in the 1.4 update:

1) Hippodrome's appear to generate Chariots... but I thought the Chariot Makers generated the walker that would walk to the Hippodrome? That's how it works in plain Caesar and I'm sure it worked that way in v1.3.1 of Augustus.

2) Chariot walkers appear to be stopped by road blocks. Since when? I've build plenty of cities where I use the walker mechanic (as seen by GamerZakh on any map that has a bunch of villas/palaces) to build huge villa blocks (like a 60 villa area on Londinium). So this one bugs me a lot (no pun intended).

So... building my amazing villa line (or multiples of them) are hindered by road blocks and the fact that the Hippodrome is generating the walker, not the Chariot Maker.

I've attached a zip that has the augustus.ini file and the save game that I have that has a city, from the City Construction Kit "Caesarea", with a Hippodrome in the left corner. I've tried that Hippodrome in 2 spots... it's not a road issue as all roads lead to the Hippodrome. And I have confirmed that my Chariot Makers, for the time being, are just there for aesthetics, not generating Chariots. I'll try this on another map and see if this bug extends to other cities.

Side note - I've been noticing a lot of issues commenting on behavior that's peculiar when the game is paused. Not sure if that makes a difference (as I do quite a bit of building and modifying while paused). I'll try to build the Hippodrome and Chariot Makers while unpaused and see if that fixes things. Either way, these pause issues seem to be a real pain in all of our rear ends :P 

As always, thanks for your hard work. From one dev to another, I appreciate what you're doing. Love the updates!

Edit: Definitely a bug on Caesarea (the city from the City Construction Kit). The Hippodrome is producing the Chariots and they are being stopped by road blocks. They also appear to have a limit walker range. So strange. However, things are working correctly on Londinium.

[Hippodrome Glitch.zip](https://github.com/Keriew/augustus/files/4809170/Hippodrome.Glitch.zip)

**Comment by Keriew** [comment]
Both chariot makers and the hippodrome spawn chariots. Chariot makers, as well as other schools, like actor colony, gladiator school, etc. spawn destination walkers - they will ignore roadblocks and go straight to the venue. Aside from that, entertainment buildings will also spawn entertainment walkers - but they'll be roaming walkers, so they are stopped by the roadblocks. That's intended as explained in the manual. Moreover, they will also spawn entertainment walkers even if they didn't get any from the respective school - though they won't provide as much entertainment then. That's also intended and that's how it works in normal C3 as well.

The problem you are facing here with chariot makers not spawning walkers is, that unlike any other building in the game, walkers need an access to the specific point to reach it - the part of the hippodrome that has a gate, i.e. the top left part of the building if played with standard rotation. Charioteers won't go to hippodrome unless they can reach that point. I assume this was intended by C3 devs, as it somewhat makes sense but I'm not sure.
