### ISSUE TITLE
Game is crashing on mission 5

### ISSUE THREAD

**Issue by speller** [Keriew/augustus#914]
I'm trying to run mission 5. But when I choose any on the mission 5 variants, the app crashes in a few moments after clicking on the shield. I can see the black screen and hear the beginning of the mission description sound. But very soon after it starts, the app crashes.
Game version: 3.2.0, Russian 1C, the patch is applied.
Android version: 11
Device: Lenovo Tab P11 (TB-J606L).
How to fix it?

Nothing specific in the log:

```none
...
INFO: Detected encoding:  1251
INFO: Creating screen 2000 x 1200, fullscreen, driver: Android
INFO: pixel format wanted SDL_PIXELFORMAT_RGBX8888 (2), got SDL_PIXELFORMAT_RGBX8888 (2)
INFO: Creating renderer
INFO: Loaded renderer: opengles2
INFO: Auto-setting scale to 150
INFO: Render texture created (1333 x 800)
```

**Comment by crudelios** [comment]
Hi,

I would suggest you try the latest unstable.

Some crashes on the beginning of the mission have been fixed since.

If you don't want to do it, do your mission briefings usually have a background image or are they black?

**Comment by speller** [comment]
@crudelios 
> do your mission briefings usually have a background image or are they black?

They usually have a background image (actually a border around black screen) and a dialog window with scrollable text and a start button. But here I can't see anything of this. Only hear the background music a bit and then it crashes. 

I will try an unstable version.

**Comment by crudelios** [comment]
Thanks.

Just to make sure, what's the mission you're trying to run?

There's an issue with the original russian translation, it's missing the background images.

You should be seeing not just a border, but an actuall fullscreen image, before the dialog appears.

That may be the cause of the crash.

Still, please let me know if the unstable version fixes the crash.

**Comment by speller** [comment]
The latest unstable version works, but the graphics quality became much worse...

**Comment by speller** [comment]
This is how it looks like in the latest stable version:

![image](https://github.com/Keriew/augustus/assets/1829515/57186bbf-c0b0-4327-8985-f90c3b04f5b9)

![image](https://github.com/Keriew/augustus/assets/1829515/38e6b3d4-2fb1-4a21-bdaa-62569110328d)

This is in the latest unstable:

![image](https://github.com/Keriew/augustus/assets/1829515/0e158de9-bc36-4c07-a400-f00f3fc7a0af)

![image](https://github.com/Keriew/augustus/assets/1829515/3f05c87b-705c-4c7c-85b4-6a5905ddee4c)


Here is the briefing screen for mission 5 made from the unstable version (I was able to see the black background with the border but not the dialog):

![image](https://github.com/Keriew/augustus/assets/1829515/fcd3e9ec-c874-4838-a948-c5e342625767)

BTW, I was able to play normally for the first four missions and the briefing screen was the same.

**Comment by crudelios** [comment]
Yeah this is a issue that has since been fixed.

Russian 1C version doesn't provide the proper background images, which used to cause the crash.

You may possibly improve the image quality on the unstable by moving the display scale slider a bit.

**Comment by speller** [comment]
Also, I'm not sure if I should write it here, but when I put original mp3 files as described here: https://github.com/bvschaik/julius/wiki/MP3-Support - the sound is crackling both on Windows and Android. The files are playing normally in any player app I tried on both OSes.

**Comment by crudelios** [comment]
Closing as a seemingly duplicate of #881 and also due to inactivity.
