### ISSUE TITLE
Question: How Can We Reward your Daily effort?

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#92]
I'm a huge fan of Caesar 3 since it came out on 1998. You've made, so far, the game even better and better, respecting its core and caracter. For that reason, i thank you for your daily effort.

Do you intent to publish your work on Steam for we to buy it?

**Comment by cdsmith-umn** [comment]
OK. I'm glad that someone else asked this because I wanted to ask something like this, and I wasn't sure what the etiquette of such a question might be. Patreon would be acceptable to me, too.

**Comment by arkimedes1967** [comment]
> OK. I'm glad that someone else asked this because I wanted to ask something like this, and I wasn't sure what the etiquette of such a question might be. Patreon would be acceptable to me, too.

One thing that a learned is that there's no free lunches. I think your commitment and effort must be appreciated and, why not, rewarded.

**Comment by cdsmith-umn** [comment]
Completely agree. I'm already contributing via Patreon to the continuing development of Tasker, which I use for lots of things on my phone. I'm happy to contribute in some way to the continuing development of this project.

**Comment by Keriew** [comment]
Hey! Thank you for the support. Augustus will always remain available free of charge. Hearing that people are enjoying the project is the biggest reward for me, I do appreciate the thought, though!
