### ISSUE TITLE
Is online wasm build match the latest offline release (mac)?

### ISSUE THREAD

**Issue by dsazonoff** [Keriew/augustus#922]
I can see some options to draw a range of walkers in wasm build, but I don't see this option (or it's not working) in the mac os latest release. What I'm doing wrong?

**Comment by crudelios** [comment]
The online wasm build provides the latest unstable.

If you also download the latest unstable for mac, you'll gain access to those options as well.

**Comment by dsazonoff** [comment]
Thanks, anyway waiting for the new release, will try unstable for now

**Comment by crudelios** [comment]
You can also use the stable build of emscripten here:

https://augustus.josecadete.net/download/augustus-3.2.0-emscripten.html
