### ISSUE TITLE
Recently deleted building list

### ISSUE THREAD

**Issue by jfkonecn** [Keriew/augustus#933]
Often when you're rearranging your city you'll delete a few buildings to make room for something else. At the moment you have to remember everything you deleted. I was thinking you could have a list of deleted buildings which are buttons so you can click on them and quickly add back what you deleted.

Maybe it'll clutter the UI too much, but I thought I'd suggest this anyway in case someone has a better way of solving the problem.

By the way this is great work you've done! Thanks for all the hard work! No hard feelings if you don't think this a good idea.

**Comment by crudelios** [comment]
This is not really easy to implement.

The game would have to keep track of whether the place where you've deleted the building is still clear or not.

Undo already does that to an extent, and it's so bug prone that I'd rather not add such a feature.

**Comment by jfkonecn** [comment]
Makes sense. Thanks for the thorough explanation!
