### ISSUE TITLE
Monuments not getting built

### ISSUE THREAD

**Issue by TheRealAyCe** [Keriew/augustus#936]
Somehow the workers and architects refuse to build the monuments. I always use the latest version of Augustus. This used to work, but somehow now nothing gets done. I disabled 2 of the monuments with the hope that they would at least start building the third one, but no.

Someone seems to "steal" the stone, so the warehouses will become empty, but it seems it's never transported to the construction site.

[nomonuments.zip](https://github.com/Keriew/augustus/files/12307265/nomonuments.zip)

![monumentsnobuilt](https://github.com/Keriew/augustus/assets/11407231/7e395f1a-3077-4a70-86f3-912fefb6a017)

**Comment by crudelios** [comment]
Will fix ASAP
