### ISSUE TITLE
New Garden Wall or Hedge 'roadblocks' on top of a road that already has Plaza start as un-interactable via right-click

### ISSUE THREAD

**Issue by Suprcheese** [Keriew/augustus#938]
Newly-placed Garden Wall or Hedge gates/roadblocks on top of a road that already has Plaza are un-interactable via right-click until another regular Roadblock or Plaza is placed.

This seems to be quite an edge case or other strange behavior, perhaps related to some road calculations that aren't being properly recalculated at the expected time?
Steps to reproduce, as demonstrated in attached brief video:
1. On a new map, build a stretch of road, then cover it with plaza
2. Build one of the following structures across the road, such that a gate appears:
	\<x> Hedge
	\<x> garden wall
	Palisade
3. Attempt to interact via right click with the gate, and observe that this fails to happen as expected. Instead only the Plaza interaction popup appears.

Video reproduction is on base map Tarentum on Augustus unstable version v3.2.0.634-a70db8b2.

The 'regular' Roadblocks are not affected by this bug and behave as expected straightaway when placed on top of plaza.

https://github.com/Keriew/augustus/assets/17792069/76830d0f-81b0-4c9d-9278-727c3a2eaf52

**Comment by Keriew** [comment]
Indeed, that has been an oversight. Thanks for reporting this!

Fixed in 5448c2d.
