### ISSUE TITLE
Option to select default behavior for newly-placed roadblock-alike objects

### ISSUE THREAD

**Issue by Suprcheese** [Keriew/augustus#939]
In this commit: https://github.com/Keriew/augustus/commit/0641ebaf3760b0351bbe16905563bf011817b1c4#diff-62f8a2d0854b9a7c106495c17c07c084df28b9aa02b9f15c6e24a6dee6c4b759R230-R235

The default behavior for newly-constructed hedge/palisade/garden wall roadblocks was changed to Allow All by default. I am not happy with this and would like them to Disallow All by default, but I can certainly see how people would want it the other way. As such, I'd like to request a new Option to toggle the default behavior. Perhaps under the City Management tab in the Options screen?

**Comment by Keriew** [comment]
I've added it as an option in 0a65be5.
