### ISSUE TITLE
I am getting a garden+cart pusher glitch in which they get stuck on gardens sometimes.

### ISSUE THREAD

**Issue by Zeg4** [Keriew/augustus#942]
I often get a glitch in which my cart pushers try to cut across gardens with their goods, but get stuck on them. When right-clicking them, they just say there is no space anywhere in the city, but it is clearly not true, and they stay like that forever or until I delete the building they came from (deleting the pusher and the goods on the cart in the process).

This does NOT happen on the original unmodded game, meaning that the glitch is on Augustus' side, the mod I am playing with. Is this a known glitch? It happens often for me, almost unavoidable unless I plan my building layout around the bug, which is annoying and often results in money loss. I suspect that it may have something to do with road layouts - the pushers stop in a separate road not connected to the destination. I believe that this may have something to do with the way cart pushers were adjusted to detect city space on Augustus, where they check that at all times instead of only when going out or arriving at their destination like they do in the unmodded game. Since they check for that all the time on Augustus, they do that on smaller roads too, resulting in the glitch that seems to be partially connected with the known garden glitch and making cart pushers unable to detect anything not connected to roads not directly connected to a valid destination while crossing a road after a garden shortcut was taken. Indeed, the cart pushers can be unstuck if the road they get stuck on is connected to the road they are supposed to head towards with an actual road instead of a garden.

Oh, and I also get a similar glitch with market ladies trying to cut across gardens to buy something with the same trigger conditions and then they either disappear there or return to their market before buying any goods, then repeat that action infinitely, effectively bricking that market until something is changed, be the market, destination or the road connection as described above.

[This Dropbox link](https://www.dropbox.com/scl/fi/x929ahwb9dugmlp0f2ya3/bug-report.svx?rlkey=9n22wi4l2mbtoa5ml9ls3gjr4&dl=0) contains a save file that I have prepared with the glitch ready to happen shortly after on the position the camera is on, with vegetable farm cart pushers. They would normally use the granary on the left, but I blocked vegetable trade on that granary to force them to use the granary on the right, which will make them cut across the gardens there, making the bug happen. The market on that neighborhood will also recreate the bug once the market lady tries to buy from the granary on the right (she will return to the market before getting to the granary). Connecting the middle road with the outer road does "fix" the bug as well.

Perhaps the weirdest part of this glitch is that it does not ALWAYS happen for all garden path cuts. They sometimes cut across them just fine and I cannot quite tell what the trigger difference is. The rest of my city on this save file does contain some cart pushers and market ladies that do exactly this, if that helps.

That is all for now. The glitch can happen with just about any cart pusher and market lady regardless of good type and destination building (granary, warehouse, workshop, even barracks), from what I can tell. Also, I am using the latest unstable version, 3.2.0.638, for Windows. I was told that the bug should be fixed there, but not only did I test it and it is still happening, but also, it happens MORE often here than on the stable version, as NPCs are more likely to take garden shortcuts on the latest version.

**Comment by crudelios** [comment]
Thanks for the save and for posting this on the correct place. I'll investigate.

**Comment by crudelios** [comment]
If the issue is always similar to your city save, then it's due to a quirk in the way c3 detects road networks as well as the fact that, as you mentioned, Augustus rechecks for a better destination every now and then.

In your save, the inner road network is different than the source and destination road network, causing the issue.

The fix should be relatively easy - don't check the road network if finding a better path - so I'll look into it.

**Comment by Zeg4** [comment]
Cool, good to know. Thanks for looking into it. I have built my cities this way since before Augustus, so having this possibly fixed would be a great help.

**Comment by crudelios** [comment]
This should now be fixed, at least your example save is now working fine.

Hopefully this doesn't break anything else...

**Comment by Zeg4** [comment]
Can confirm the fix, and everything else regarding gardens and road networks seems to be unaffected from what I can tell.

Thanks a lot.

**Comment by crudelios** [comment]
Glad it's fixed! Enjoy!
