### ISSUE TITLE
Game crash upon loading a save state.

### ISSUE THREAD

**Issue by Zeg4** [Keriew/augustus#948]
The crash log reads as follows:

_INFO:  Loading saved game  3 Data.svx
INFO:  Savegame version  155
INFO:  Window 1 exposed
INFO:  Window 1 exposed
INFO:  Window 1 exposed
INFO:  Window 1 exposed
INFO:  Window 1 exposed
INFO:  Window 1 exposed
INFO:  Window 1 exposed
INFO:  Window 1 exposed
**ERROR:  Oops, crashed :(**
INFO:  Exception: Access violation (0xc0000005)
INFO:  Saving game  3 Data.svx (message repeats 9 times)
INFO:  Loading saved game  3 Data.svx (message repeats 10 times)
INFO:  Savegame version  155 (message repeats 10 times)
INFO:  Exception Address: 0x0045b05a
INFO:  Stacktrace:
INFO:  (0) src\figure\formation_layout.c L:38(formation_layout_position_x+0) [0x0045b05a]
INFO:  (1) src\figuretype\enemy.c L:370(figure_enemy_elephant_action+0) [0x0046774a]
INFO:  (2) src\figure\action.c L:142(figure_action_handle+0) [0x00453ece]
INFO:  (3) src\game\tick.c L:205(game_tick_run+0) [0x0047b576]
INFO:  (4) src\game\game.c L:184(game_run+0) [0x00479b2c]
INFO:  (5) src\platform\augustus.c L:166(run_and_draw+0) [0x00401918]
INFO:  (6) src\platform\augustus.c L:393(SDL_main+0) [0x00401f60]_

I simply loaded a previous save as usual and the game crashed. The save file still works and I cannot reproduce the error again, so it would be pointless to provide the save and my own game suffered no consequence. I just report this for optimization purposes to help development in case this may be of any concern.

As one of the lines suggest, I loaded a save right after defeating an enemy army that had an elephant troop among them. Not sure what else I can say that is relevant, and the crash happened only once - the save works just fine now.

**Comment by crudelios** [comment]
Hi,

Does the loaded save also have elephants in it?

**Comment by crudelios** [comment]
Do you still have the save? I think it would be useful actually!

**Comment by Zeg4** [comment]
Unfortunately not. Since the crash itself was not game-disrupting and I could not replicate it, I kind of moved on without thinking much of it.

I know I will get more fights with elephants on this map, so I can try saving under similar conditions again and see what happens.

**Comment by Zeg4** [comment]
Got it. The map is Military 5, if that happens to be relevant (Quaestor-level campaign map).

**Comment by Zeg4** [comment]
Wow, that is very... specific. And odd that I never got that on the original game. I also wonder why I could not reproduce the crash, although that is good since it would have locked my save otherwise.

Guess we dodged a bullet here. Thanks for looking into it.
