### ISSUE TITLE
Request: Add a Line on Load Menu

### ISSUE THREAD

**Issue by arkimedes1967** [Keriew/augustus#95]
Please exclude this thread.

**Comment by crudelios** [comment]
I had done this once, I'll implement it again.

**Comment by arkimedes1967** [comment]
And what about my #75 suggestion, is it doable?

Actually, it needs one more item: "Continue game" or Esc key again.

**Comment by arkimedes1967** [comment]
About this subject, i updated the text on the main menu from 'Continue game' to 'Resume last game'.

This option would retrieve the last saved game.

![Resume Game](https://user-images.githubusercontent.com/64329357/105893573-29f8a580-600b-11eb-8795-a2dfeeaea378.jpg)
