### ISSUE TITLE
The Desirability overlay gets a bit glitchy when visualizing it while having "Clear land" selected.

### ISSUE THREAD

**Issue by Zeg4** [Keriew/augustus#955]
![image](https://github.com/Keriew/augustus/assets/143092909/07449248-a4a6-4e70-bb1b-613889dbf046)
This is how it normally looks.

![image](https://github.com/Keriew/augustus/assets/143092909/dfd32e81-c74f-4bb4-bbf1-06ee22408356)
And this is how it looks while having "Clear land" selected. All tiles with buildings on them look visually janky.

No idea why this happens, though I believe it is not a thing on the vanilla game. It is also based on the "height" of the tiles, so it does not affect tiles below a certain desirability value (orange and below are fine).

I tested this on the latest Augustus unstable build for desktop uploaded today.

**Comment by crudelios** [comment]
This is due to "improve visual feedback when clearing land" setting. This one can't be disabled in Augustus. In Julius, the glitch manifests only if the setting is enabled.

I'm going to check if it's an easy fix. If it isn't I won't fix it as it is a really small and specific visual glitch.

**Comment by Zeg4** [comment]
Got it. It just looks slightly unpleasing at most, so that is OK if the best approach is to not touch anything.

**Comment by crudelios** [comment]
I just checked the code and it should be easy to fix.
