### ISSUE TITLE
UndefinedBehavior when mouse cursor near the bottom of the map

### ISSUE THREAD

**Issue by PrettyFlower** [Keriew/augustus#958]
Seems to happen on any large map when zoomed out slightly. For reference my cursor was about here:
![image](https://github.com/Keriew/augustus/assets/2081059/ed08cd00-e332-40bb-b046-f4f7660898b0)
on this map:
[valentiablockybackuphighway.zip](https://github.com/Keriew/augustus/files/12570628/valentiablockybackuphighway.zip)

I'm getting a tile->y value of 325, but the maximum size of the array is 325 so the index is out of bounds.
![image](https://github.com/Keriew/augustus/assets/2081059/97637716-4098-415f-9f61-e6892e55cd26)

I think it may be due to these two lines in `city_view_pixels_to_view_tile()`:
![image](https://github.com/Keriew/augustus/assets/2081059/6ea4c678-12d4-43ac-988a-27ca7606a552)

**Comment by crudelios** [comment]
Fixed by c180739

**Comment by PrettyFlower** [comment]
Confirmed, fixed! Thx crudelios.
