### ISSUE TITLE
Mac Build: "macOS cannot verify the developer of 'augustus'" error.

### ISSUE THREAD

**Issue by eternalstorms** [Keriew/augustus#960]
When double-clicking the augustus app for Mac, I receive the following error in Finder:

macOS cannot verify the developer of “augustus”. Are you sure you want to open it?

Any plans on re-signing it with a new macOS developer identity?

**Comment by crudelios** [comment]
We don't intend on signing it as a developer identity costs $100 and we don't want to spend such money.

You probably know this but you can still right click the app and select open and you'll be able to launch the game.

**Comment by eternalstorms** [comment]
I understand. Thank you for getting back to me so quickly. I was just confused, as I was informed about augustus on macsourceports, and it is stated there that the Mac build is signed and notarized.

**Comment by crudelios** [comment]
I'm not into mac development but I think it's self signed?

I'm not sure but there's some signing going on, but it's not a registered developer signature.

That may be the root cause of the confusion.

**Comment by eternalstorms** [comment]
I'm an idiot. MacSourcePorts apparently has their own fork/build of augustus, with a signed/notarized build, and they're referring to their build, of course, not this one. And theirs indeed is signed.
My apologies for the confusion.
