### ISSUE TITLE
House on roadblocks

### ISSUE THREAD

**Issue by githubfan1** [Keriew/augustus#961]
I am a little surprised to get a house on roadblocks; at that time, I was skeptical to put down the house thinking that couldn't be possible.
![house-on-roadblock](https://github.com/Keriew/augustus/assets/6599012/de5acfb8-85ea-4f50-994e-6ef5b3115803)

**Comment by crudelios** [comment]
Actually I don't see why it shouldn't be possible - you can even put houses 1 tile away from a road, with stuff in the middle.

But for consistency sake, maybe we should check how pharaoh handles it.

**Comment by Keriew** [comment]
Verified that you can do the same thing in Pharaoh. While it does feel weird, there doesn't really seem to be a reason to disallow it.
