### ISSUE TITLE
Warehouses deliver materials based on priority, leading them to ignore nearby workshops even if they have materials for them.

### ISSUE THREAD

**Issue by Zeg4** [Keriew/augustus#968]
If a warehouse handles more than one material type (clay, timber, olives, iron, etc.), the material type has a higher priority than workshop distance or whether or not those workshops already have materials on them, making it virtually impossible to have multi-material workshops and have them work properly, which would force the player to have single-material workshops only. I know many people already play like this, but I would rather not be forced to play a certain way because of what seems to be an oversight, since I see no functional purpose to warehouses having material priority for their workshop deliveries to the point they even ignore empty workshops and distance. It is a net negative with no upsides.

[On this save,](https://www.dropbox.com/scl/fi/4dt5llq2smirxliesijqg/material-priority-issue.svx?rlkey=83edqvnoaz6qymfx0rkngobb4&dl=0) the issue can be seen easily. I have a few warehouses accepting olives and clay imported overseas; the camera is focused on one such warehouse ("Warehouse 1" if the camera is not focused, the one furthest south of the city). Load the save and pause it immediately. The warehouse has both clay and olives, and the cart pusher is ready to deliver either. Select the "Sickness" overlay to see cart pushers easily. There are 3 pottery workshops and 3 oil workshops near it, and one of the oil workshops is empty, while the pottery workshops already have 2 clay each. The warehouse then proceeds to completely ignore the oil workshops and instead decides to go to a pottery workshop on the far north end of the city, one that is not even empty. If you were to order the warehouse to not deliver materials until all 3 oil workshops near it are empty and then resume delivery, it **still** ignores them, instead refilling the nearby pottery workshops back to 2 each and, once done with that, yet again chooses to deliver clay to a faraway potter workshop. This effectively means that this workshop will not deliver any olives until all pottery workshops in the city are either full and/or mothballed for as long as the warehouse has clay, as clay overrides olives in priority.

I hope that this one is an easy fix, as the only fix for it otherwise would be to build more warehouses and essentially relocate workshops and play around that new layout all over. I am playing on the latest unstable build.

**Comment by crudelios** [comment]
To be honest I'm not sure how/if we should change this.

There's a reason warehouses prioritise workshops, which is, the city running out of pottery would be even worse than it running out of oil, for example. If the only priority was distance, you could risk getting a lot of oil but no pottery.

Also, I do not consider this to be a bug, but rather a gameplay mechanic.

Still, I'm open to suggestions: how would we change this? Would it be purely distance-based? Distance and number of raw materials? Should there be a max distance? Or maybe a "distribution roadblock" that blocks road access to some destination walkers such as cartpushers, thereby segmenting the city without the need to actually cut off roads?

**Comment by Zeg4** [comment]
Personally, my only issue is when cart pushers travel too far back to deliver a material to some empty workshop the other side of the city, which would force the player to have designated spaces for that one material, which would not be possible on all map layouts.

The simplest solution to this would be to add an option similar, but stricter than the _"Farms and wharves deliver only to nearby granaries"_  option already in the game. Even if the material priority is kept, such an option would help get rid of the main issue of cart pushers delivering materials too far and delaying production as a result. And perhaps this can be added for raw material buildings too? The same applies to them, albeit less often since they only handle one material. If this could be a thing, then the raw material priority system would have no downsides to it, I believe.

**Comment by crudelios** [comment]
A proper way to do this would likely be to use some sort of heuristic with actual pathfinding instead of bird's eye distance to detect a valid destination building.

The heuristic would consider both the number of stored raw materials, the resource priority and the distance to the source.

While we're at it, maybe buildings could also store the number of goods which are being delivered to it, in order to prevent cartpushers overfilling a workshop.

This is a big gameplay change that would definitely make things easier/more intuitive but it would be a lot of work to implement.

**Comment by Zeg4** [comment]
_"While we're at it, maybe buildings could also store the number of goods which are being delivered to it, in order to prevent cartpushers overfilling a workshop."_

I am glad you mentioned this, as I did wonder some time ago if this was possible to implement. That would be a "super fix" just by itself, so if this **is** actually viable, I would be OK with that being the solution even if it means a delayed implementation given the increased workload involved. Thinking in the long term would actually be better than just applying small changes that may not stay, after all.

I imagine whichever one is decided by the team to be the most efficient and viable approach would be fine by most people here. Both of the proposed changes you mentioned also address other more important issues than the one I bring up here, so that would naturally take priority over this.

I am perfectly OK with the "slow and steady" approach on my end 👍

**Comment by crudelios** [comment]
Since this is a gameplay feature request and not really a bug, I'll be closing this.

But it's actually an useful addition for the future.
