### ISSUE TITLE
Game auto-rotate

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [Keriew/augustus#972]
Can I disable auto-rotate? The game will auto-rotate regardless of the phone rotation lock settings.
It is irritating. Can we disable it or put an option for that?

**Comment by crudelios** [comment]
Just posted a potential fix for this, hopefully it works!

**Comment by bvschaik** [comment]
It unfortunately doesn't. SDL uses native C code to deal with rotation, it doesn't even look at this setting.

**Comment by crudelios** [comment]
Ah, shame. Thanks!

**Comment by crudelios** [comment]
Yeah I just confirmed, this is unfixable as of now as it is a problem with the library we use to handle  graphics, input etc.
