### ISSUE TITLE
Unable to load development assets with latest patch.

### ISSUE THREAD

**Issue by Salve970** [Keriew/augustus#973]
Describe the bug, Unable to load development assets with latest patch.. Anyone know how to fix? Thanks.

**Comment by crudelios** [comment]
If you're using the latest unstable, you should also use the latest development assets.

To do that, you should delete the `assets` folder and not just overwrite it.

Also, the game searches for the assets in the same folder as `augustus.exe`, and only if it doesn't find the assets there it will look for the original C3 folder. So make sure you don't have two assets folder and are only replacing the wrong one!

**Comment by Salve970** [comment]
Thanks for advice. That worked.
