### ISSUE TITLE
When is next official release?

### ISSUE THREAD

**Issue by Salve970** [Keriew/augustus#974]
When is next official release? Thanks

**Comment by crudelios** [comment]
Very good question!

I'm overloaded with work right now and basically stopped working on Augustus. Unfortunately I'm also not sure when work will relent.

A lot of not too gamebreaking, but difficult to debug bugs have been found recently, which should be fixed before release.

So honestly I've been more optimistic about a release date. Right now I can't really answer that.

So I'll only give the old, usual answer: it will be released when it is released 😉
