### ISSUE TITLE
Unknown glitch involving farm cart pushers, granaries and bridges.

### ISSUE THREAD

**Issue by Zeg4** [Keriew/augustus#976]
[On this save,](https://www.dropbox.com/scl/fi/oz8sytnrvzo7of6t25v5w/bridge-cart-pusher-glitch.svx?rlkey=szptx7au0sow7nbculayvsmkc&dl=0) I have the conditions for a glitch already occurring upon load on the city's only low bridge connected with roads. My farms overproduced food, so they do what they usually do on this instance and push their cargo to a faraway granary, in this case, one past a low bridge. For some reason, however, some cart pushers are stuck at the bridge. When right-clicked, they say "there is no space anywhere in the city", which is clearly wrong.

![image](https://github.com/Keriew/augustus/assets/143092909/64c6aff2-a4c2-448c-9faa-d4b22a14650c)

The window says that they are still trying to go to that granary on the screenshot, and indeed, if you were to delete the granary or tell it to not receive wheat anymore, the cart pushers get fixed and go to the other granary past that one instead as usual.

I tried a number of things here:

- I did as described above, but then told the granary to accept wheat again once the cart pushers are off the bridge. This makes them stuck again, this time on proper land.
- I tried deleting all roadblocks along the way to see if that affected anything. It did not.
- I tested with other granaries. Oddly enough, the other granary also past the low bridge does not replicate the glitch, at least not on this specific scenario.
- I tried re-doing the road connections alongside the glitched granary to see if anything changed. It did not.
- I waited until no walkers were on the bridge so I could delete it to see if that changed anything. **It only worked halfway, unstucking the cart pushers, but they still go to the other granary and not the one nearby.** This means that whatever the glitch is, it is related to the bridge in question.
- As mentioned earlier, deleting the nearby granary or blocking the food type from stuck cart pushers unstucks them, going to the other granary past the bridge instead.
- Just in case, I deleted the ship bridge on the other side just to make sure it had nothing to do with this. I was right: it is unrelated.
- I deleted the 2 road tiles adjacent to the bridge, effectively unlinking it that way. This behaved the same way as deleting the bridge did, once again confirming that the glitch is bridge-related (though still not explaining why only that one granary is affected).

And I also believe that not ALL cart pushers going to that granary crossing the bridge got stuck there, just some of them did.

Whatever this may be, it is bridge-related, and that granary on the screenshot also has something weird going for it, as it just refuses to accept wheat from those cart pushers no matter what I do.

I have not seen this happen for other cart pushers. I am on the latest unstable build of Augustus.

**Comment by Keriew** [comment]
Hey, sorry for taking time to get to this issue.

I've loaded the save and I can't replicate the issue of cart pushers getting stuck on the bridge. The ones already there seem to move briefly after loading the save.

It's possible that the underlying problem could have been fixed since you reported the issue. Could you confirm if it persists on your end on the latest build?

**Comment by Zeg4** [comment]
I installed the latest version and indeed, I still got the glitch.

I remembered that a player's settings do NOT get carried over save files, them instead being stored locally on each player's install, so I instantly thought that it may be a game option causing the issue. I was right: I immediately found the option causing the issue. I am playing with "Farms and wharves deliver only to nearby granaries" option ON by default. I turned it OFF and the cart pushers were instantly fixed. I loaded the save with the option still off and what you described happened too, so I am guessing the option is turned off on your end by default, which also means we now know what is causing the glitch to happen, or at least where to look for it. Something about it seems janky when interacting with bridges.

I have seen people unable to replicate reported glitches from other people's save files before on the Discord server, so I think this incidence of a glitch being caused by ingame options is not an uncommon one. May be worth taking into consideration next time an on-load glitch is not happening from a player's save file for other people.

**Comment by crudelios** [comment]
I think there's a broader issue here: maybe we should store gameplay settings in savegames, and then alert the user on city load of the differing settings which can cause gameplay compatibility issues.

Things like fixed workforce, +10 years workforce, walkers skip corners and this one cartpushers don't deliver to faraway farms seem like good candidates for the alert.

**Comment by Zeg4** [comment]
That would be a very useful addition if that is a thing that can be done, yes. I basically always run into that issue when people link their saves for any reason - the first thing I run into is figuring out what the player's settings were for it. I play without global labor pool, so the most common one is loading a save and immediately watching unemployment skyrocket if it is a big city, having over half of the buildings brickednow until you change that setting.

**Comment by crudelios** [comment]
Though I think the gameplay alerts would be useful (and will eventually be added), there isn't an actual bug, so I'll be closing this.
