### ISSUE TITLE
How to get Favor to work on custom made games

### ISSUE THREAD

**Issue by Salve970** [Keriew/augustus#980]
Ask your question here.
I created a new map and setup to add  +99 per emperor request met.  Every I met a request there is no change in Emperor favor rating. 
My rating is stuck at 50. Thanks for any help.

**Comment by Keriew** [comment]
Do you have the map set to open play in win criteria? That makes it so that favor is permanently set to 50.

**Comment by Salve970** [comment]
Yes. I try without open play. Thanks for quick response.

**Comment by Salve970** [comment]
Thanks for advice Keriew. It works now.
