### ISSUE TITLE
With the recent Update, How do you get wolves attack enemy troops?

### ISSUE THREAD

**Issue by Salve970** [Keriew/augustus#982]
With the recent Update, How do you get wolves attack enemy troops?  Do wolves also attack Caesar's troops as well?  Thanks for reply.

**Comment by Keriew** [comment]
Wolves will fight anything they run across, including Caesar's troops. I imagine it's not going to happen all that often, but it felt like a fun overall change.

**Comment by Salve970** [comment]
Thanks
