### ISSUE TITLE
Variable Edge Directed Interpolation for upscaling pixel art resources depending on zoom level

### ISSUE THREAD

**Issue by Syst3mSh0ck** [Keriew/augustus#99]
First of all thanks for all the work. I was wondering if a graphical enhancement could be implemented. Zoom is a great feature but the pixel art can start to look very pixelated. Could we perhaps implement an Edge Directed Interpolation algorithm (such as SuperRes) at variable levels of strength depending on the zoom level. A simpler alternative would be Nearest-neighbour rounding.

I've not looked at the rendering path in Julius/Augustus but I should imagine it would be possible to pass the assets to another library for image processing ie triple buffering (Backbuffer (SDL?) > Upscaling algorithm (intermediate library)> Frontbuffer (DX9?), or perhaps use of Shaders. Thanks.

**Comment by crudelios** [comment]
Given the complexity this would add, I'm not really sure it would be a good idea.

**Comment by Keriew** [comment]
I feel like regardless of how well it looks, zooming in is not going to be practical. So considering that would be a lot of work for little benefit, I think it's not worth the effort.
