### ISSUE TITLE
Small temple to all, creates temple to Ceres

### ISSUE THREAD

**Issue by capsicumw** [Keriew/augustus#991]
Selecting lightning bolt menu button -> small temple -> All. Results in a temple to Ceres. 
Selecting Ceres also creates a temple to Ceres. All of the other individual-god small temples seem to be correct.
Linux appimage 3.2.0 using original 1998 CD and Julius 1.0.1.0 update patch.

**Comment by crudelios** [comment]
Small temple to all allow you to create all temples in succession. The first will be to Ceres but if you keep building temples it will then build one to Neptune, then Mercury, then Mars and finally Venus, before cycling back to Ceres.
