### ISSUE TITLE
Mouse wheel now working on MacOS

### ISSUE THREAD

**Issue by dsazonoff** [Keriew/augustus#997]
Version: 3.2.0.726
Os: intel based MacOS 14.2 (Sonoma)

It is not possible to zoom in/out the map with the mouse wheel. But wheel is working in settings dialogs.

And mouse cursor periodically converts to the system, resetting this settings is a workaround.

**Comment by Ouaz** [comment]
You need to reassign the mouse wheel to `Zoom in`, `Zoom out`, and `Reset Zoom`, in `Options > Controls > Hotkeys`.

Click each of them, then assign respectively mouse wheel scroll up, scroll down, and middle click.

As zoom controls can be assigned to any keys now, mouse wheel is not anymore the defaut setting, and needs to be re-assigned manually.

**Comment by dsazonoff** [comment]
Thanks for the clarification. It was my mistake. Big respect for the job!
